import { createRef, useEffect, useId, useMemo, useRef, useState } from 'react';
import type { CSSProperties, KeyboardEvent, PointerEvent as ReactPointerEvent, ReactNode, RefObject } from 'react';
import { OverlayPortal, useAnchoredOverlay, useOverlayDismiss, useOverlayPresence, useOverlayScope } from './overlays.js';

export interface CommentAuthor { id:string; name:string; avatar?:string }
export interface CommentReaction { emoji:string; users:string[] }
export interface ThreadComment { id:string; author:CommentAuthor; body:string; createdAt:string; edited?:boolean; deleted?:boolean; reactions?:CommentReaction[]; replies?:ThreadComment[] }
export type CommentThreadEvent = {type:'reply';comment:ThreadComment;parentId:string|null}|{type:'edit';id:string;body:string}|{type:'delete';id:string}|{type:'react';id:string;emoji:string;added:boolean};
export interface CommentThreadProps { comments?:ThreadComment[]; defaultComments?:ThreadComment[]; onCommentsChange?:(comments:ThreadComment[],event:CommentThreadEvent)=>void; currentUser:CommentAuthor; people?:CommentAuthor[]; resolved?:boolean; defaultResolved?:boolean; onResolvedChange?:(resolved:boolean)=>void; title?:ReactNode; reactions?:string[]; placeholder?:string; nowLabel?:string; className?:string }
const REACTIONS=['👍','❤️','🎉','👀','🚀','✅'];let sequence=0;const makeId=()=>`comment-${Date.now().toString(36)}-${(sequence++).toString(36)}`;
const countComments=(list:ThreadComment[]):number=>list.reduce((sum,c)=>sum+(c.deleted?0:1)+countComments(c.replies??[]),0);
function updateComment(list:ThreadComment[],id:string,fn:(comment:ThreadComment)=>ThreadComment|null):ThreadComment[]{return list.flatMap(c=>{if(c.id===id){const next=fn(c);return next?[next]:[]}return [{...c,replies:c.replies?updateComment(c.replies,id,fn):undefined}]})}
function allAuthors(list:ThreadComment[],out:CommentAuthor[]=[]):CommentAuthor[]{for(const c of list){if(!out.some(a=>a.id===c.author.id))out.push(c.author);allAuthors(c.replies??[],out)}return out}
function renderBody(text:string,people:CommentAuthor[]):ReactNode{const names=people.map(p=>p.name).filter(Boolean).sort((a,b)=>b.length-a.length).map(name=>name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'));if(!names.length)return text;const pattern=new RegExp(`(@(?:${names.join('|')})(?![\\p{L}\\p{N}_]))`,'gu');return text.split(pattern).map((part,index)=>part.startsWith('@')?<strong className="cap-comment-mention" key={index}>{part}</strong>:part)}
export function CommentThread(props:CommentThreadProps){return <CommentThreadContent {...props}/>;}
function CommentThreadContent({surface='raised',comments,defaultComments=[],onCommentsChange,currentUser,people,title='Comments',resolved,defaultResolved=false,onResolvedChange,reactions=REACTIONS,placeholder='Write a comment…',nowLabel='now',className=''}:CommentThreadProps & {surface?:'raised'|'floating'}){const [internal,setInternal]=useState(defaultComments),[internalResolved,setInternalResolved]=useState(defaultResolved),[draft,setDraft]=useState(''),[replyTo,setReplyTo]=useState<string|null>(null),[editing,setEditing]=useState<string|null>(null),[editText,setEditText]=useState(''),[picker,setPicker]=useState<string|null>(null),[mentionIndex,setMentionIndex]=useState(0),[dismissedMention,setDismissedMention]=useState<string|null>(null);const id=useId(),composer=useRef<HTMLTextAreaElement>(null),list=comments??internal,isResolved=resolved??internalResolved;
  const commit=(next:ThreadComment[],event:CommentThreadEvent)=>{if(comments===undefined)setInternal(next);onCommentsChange?.(next,event)};
  const resolve=(next:boolean)=>{if(resolved===undefined)setInternalResolved(next);onResolvedChange?.(next)};
  const knownPeople=useMemo(()=>{const sources=[...(people??[]),...allAuthors(list),currentUser];return sources.filter((person,i)=>sources.findIndex(x=>x.id===person.id)===i)},[people,list,currentUser]);
  const mention=draft.match(/(?:^|\s)@([\p{L}\p{N}_-]*(?: [\p{L}\p{N}_-]*){0,3})$/u),suggestions=mention&&draft!==dismissedMention?knownPeople.filter(p=>p.name.toLocaleLowerCase().startsWith(mention[1].toLocaleLowerCase())&&p.id!==currentUser.id).slice(0,5):[];
  const chooseMention=(person:CommentAuthor)=>{const start=draft.lastIndexOf('@');setDraft(`${draft.slice(0,start)}@${person.name} `);setMentionIndex(0);setDismissedMention(null);requestAnimationFrame(()=>composer.current?.focus())};
  const send=()=>{const body=draft.trim();if(!body)return;const comment:ThreadComment={id:makeId(),author:currentUser,body,createdAt:nowLabel,replies:[]};const next=replyTo?updateComment(list,replyTo,parent=>({...parent,replies:[...(parent.replies??[]),comment]})):[...list,comment];commit(next,{type:'reply',comment,parentId:replyTo});setDraft('');setReplyTo(null)};
  const saveEdit=(comment:ThreadComment)=>{const body=editText.trim();if(!body){setEditing(null);return}commit(updateComment(list,comment.id,c=>({...c,body,edited:true})),{type:'edit',id:comment.id,body});setEditing(null)};
  const remove=(comment:ThreadComment)=>{const next=updateComment(list,comment.id,c=>c.replies?.length?({...c,deleted:true,body:''}):null);commit(next,{type:'delete',id:comment.id})};
  const react=(comment:ThreadComment,emoji:string)=>{const reaction=comment.reactions?.find(r=>r.emoji===emoji),added=!reaction?.users.includes(currentUser.id);const next=updateComment(list,comment.id,c=>{const reactions=[...(c.reactions??[])],at=reactions.findIndex(r=>r.emoji===emoji);if(at<0){if(added)reactions.push({emoji,users:[currentUser.id]})}else{const users=reactions[at].users.filter(user=>user!==currentUser.id);if(added)users.push(currentUser.id);if(users.length)reactions[at]={...reactions[at],users};else reactions.splice(at,1)}return {...c,reactions}});commit(next,{type:'react',id:comment.id,emoji,added})};
  const renderComment=(comment:ThreadComment,depth=0):ReactNode=><li className="cap-comment-item" key={comment.id}><article className="cap-comment"><div className="cap-comment-avatar" aria-hidden="true">{comment.author.avatar?<img src={comment.author.avatar} alt=""/>:comment.author.name.split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase()}</div><div className="cap-comment-main"><header className="cap-comment-meta"><strong>{comment.deleted?'Deleted comment':comment.author.name}</strong><time>{comment.createdAt}{comment.edited?' · edited':''}</time></header>{comment.deleted?<p className="cap-comment-deleted">This comment was deleted.</p>:editing===comment.id?<div className="cap-comment-edit"><textarea autoFocus aria-label="Edit comment" value={editText} onChange={e=>setEditText(e.target.value)}/><button type="button" onClick={()=>saveEdit(comment)}>Save</button><button type="button" onClick={()=>setEditing(null)}>Cancel</button></div>:<p className="cap-comment-body">{renderBody(comment.body,knownPeople)}</p>}{!comment.deleted&&<footer className="cap-comment-footer">{(comment.reactions??[]).map(r=><button type="button" key={r.emoji} aria-pressed={r.users.includes(currentUser.id)} aria-label={`${r.emoji} ${r.users.length}`} onClick={()=>react(comment,r.emoji)}>{r.emoji} {r.users.length}</button>)}<button type="button" onClick={()=>setPicker(picker===comment.id?null:comment.id)} aria-label="Add reaction">＋</button>{picker===comment.id&&<span className="cap-comment-reaction-picker" data-surface="floating" role="group" aria-label="Reactions">{reactions.map(emoji=><button type="button" key={emoji} aria-label={`React with ${emoji}`} onClick={()=>{react(comment,emoji);setPicker(null)}}>{emoji}</button>)}</span>}<button type="button" onClick={()=>{setReplyTo(comment.id);setDraft('');requestAnimationFrame(()=>composer.current?.focus())}}>Reply</button>{comment.author.id===currentUser.id&&<><button type="button" onClick={()=>{setEditing(comment.id);setEditText(comment.body)}}>Edit</button><button type="button" onClick={()=>remove(comment)}>Delete</button></>}</footer>}</div></article>{comment.replies&&comment.replies.length>0&&<ol className="cap-comment-replies" data-depth={depth+1}>{comment.replies.map(reply=>renderComment(reply,depth+1))}</ol>}</li>;
  return <section className={`cap-comment-thread cap-surface-boundary ${className}`} aria-label={typeof title==='string'?title:'Comment thread'} data-surface={surface}><header className="cap-comment-thread-header"><div><h3>{title}</h3><span>{countComments(list)} {countComments(list)===1?'comment':'comments'}</span></div><button type="button" onClick={()=>resolve(!isResolved)}>{isResolved?'Reopen':'Resolve'}</button></header>{isResolved?<button className="cap-comment-resolved" type="button" onClick={()=>resolve(false)}>Resolved · {countComments(list)} comments — Reopen</button>:<><ol className="cap-comment-list">{list.map(comment=>renderComment(comment))}</ol>{list.length===0&&<p className="cap-comment-empty">No comments yet. Start the conversation below.</p>}{replyTo&&<p className="cap-comment-replying">Replying to {findComment(list,replyTo)?.author.name}<button type="button" onClick={()=>setReplyTo(null)}>Cancel reply</button></p>}<div className="cap-comment-composer"><textarea ref={composer} aria-label="Write a comment" aria-autocomplete="list" aria-controls={suggestions.length?`${id}-mentions`:undefined} aria-activedescendant={suggestions.length?`${id}-mention-${mentionIndex}`:undefined} placeholder={placeholder} value={draft} onChange={e=>{setDraft(e.target.value);setMentionIndex(0);setDismissedMention(null)}} onKeyDown={(e:KeyboardEvent<HTMLTextAreaElement>)=>{if(suggestions.length&&e.key==='ArrowDown'){e.preventDefault();setMentionIndex(i=>(i+1)%suggestions.length)}else if(suggestions.length&&e.key==='ArrowUp'){e.preventDefault();setMentionIndex(i=>(i+suggestions.length-1)%suggestions.length)}else if(suggestions.length&&e.key==='Escape'){e.preventDefault();setDismissedMention(draft)}else if(suggestions.length&&e.key==='Enter'&&!e.shiftKey){e.preventDefault();chooseMention(suggestions[mentionIndex])}else if(e.key==='Enter'&&(e.metaKey||e.ctrlKey)){e.preventDefault();send()}}}/>{suggestions.length>0&&<div id={`${id}-mentions`} role="listbox" aria-label="People to mention" className="cap-comment-suggestions" data-surface="floating">{suggestions.map((person,i)=><button key={person.id} id={`${id}-mention-${i}`} type="button" role="option" aria-selected={i===mentionIndex} onPointerDown={event=>event.preventDefault()} onClick={()=>chooseMention(person)}>{person.name}</button>)}</div>}<button type="button" onClick={send} disabled={!draft.trim()}>Send</button></div></>}</section>
}
function findComment(list:ThreadComment[],id:string):ThreadComment|undefined{for(const c of list){if(c.id===id)return c;const found=findComment(c.replies??[],id);if(found)return found}return undefined}

export interface InlineCommentAnchor { id:string; x:number; y:number; comments:ThreadComment[]; title?:string; resolved?:boolean }
export interface InlineCommentsProps { children:ReactNode; currentUser:CommentAuthor; people?:CommentAuthor[]; anchors?:InlineCommentAnchor[]; defaultAnchors?:InlineCommentAnchor[]; onAnchorsChange?:(anchors:InlineCommentAnchor[])=>void; commentMode?:boolean; defaultCommentMode?:boolean; onCommentModeChange?:(enabled:boolean)=>void; className?:string }
function InlineThreadPopup({anchorRef,anchorId,anchorIndex,title,currentUser,people,comments,resolved,open,onCommentsChange,onResolvedChange,onClose}:{anchorRef:RefObject<HTMLButtonElement|null>;anchorId:string;anchorIndex:number;title?:string;currentUser:CommentAuthor;people?:CommentAuthor[];comments:ThreadComment[];resolved?:boolean;open:boolean;onCommentsChange:(next:ThreadComment[])=>void;onResolvedChange:(next:boolean)=>void;onClose:()=>void}){
  const panel=useRef<HTMLDivElement|null>(null);
  const scope=useOverlayScope(anchorRef),position=useAnchoredOverlay(open,anchorRef,panel,{align:'center',side:'bottom'}),present=useOverlayPresence(open);
  useOverlayDismiss(open,panel,anchorRef,restore=>{onClose();if(restore)requestAnimationFrame(()=>anchorRef.current?.focus())});
  useEffect(()=>{panel.current?.querySelector<HTMLTextAreaElement>('.cap-comment-composer textarea')?.focus()},[]);
  if(!present)return null;
  return <OverlayPortal anchor={anchorRef} panel={panel}><div ref={panel} id={`inline-thread-${anchorId}`} className="cap-inline-thread" style={position} {...scope} role="dialog" aria-label={`Inline comment ${anchorIndex+1}`} aria-hidden={!open} inert={!open} data-state={open?'open':'closed'}><button type="button" className="cap-inline-close" aria-label="Close comment thread" onClick={()=>{onClose();requestAnimationFrame(()=>anchorRef.current?.focus())}}>×</button><CommentThreadContent surface="floating" currentUser={currentUser} people={people} title={title} comments={comments} resolved={resolved} onResolvedChange={onResolvedChange} onCommentsChange={onCommentsChange}/></div></OverlayPortal>
}
export function InlineComments({children,currentUser,people,anchors,defaultAnchors=[],onAnchorsChange,commentMode,defaultCommentMode=false,onCommentModeChange,className=''}:InlineCommentsProps){const [innerAnchors,setInnerAnchors]=useState(defaultAnchors),[innerMode,setInnerMode]=useState(defaultCommentMode),[selected,setSelected]=useState<string|null>(null);const root=useRef<HTMLDivElement>(null),pinRefs=useRef(new Map<string,RefObject<HTMLButtonElement|null>>());const list=anchors??innerAnchors,mode=commentMode??innerMode;const setList=(next:InlineCommentAnchor[])=>{if(anchors===undefined)setInnerAnchors(next);onAnchorsChange?.(next)};const setMode=(next:boolean)=>{if(commentMode===undefined)setInnerMode(next);onCommentModeChange?.(next)};const active=list.find(item=>item.id===selected),lastActive=useRef<typeof active>(active),popupPresent=useOverlayPresence(!!active);if(active)lastActive.current=active;const pinRef=(id:string)=>{let ref=pinRefs.current.get(id);if(!ref){ref=createRef<HTMLButtonElement>();pinRefs.current.set(id,ref)}return ref};
  const place=(e:ReactPointerEvent<HTMLDivElement>)=>{const rect=root.current?.getBoundingClientRect();if(!rect||!rect.width||!rect.height)return;const id=makeId(),anchor:InlineCommentAnchor={id,x:Math.max(0,Math.min(1,(e.clientX-rect.left)/rect.width)),y:Math.max(0,Math.min(1,(e.clientY-rect.top)/rect.height)),comments:[],title:'Comment'};setList([...list,anchor]);setSelected(id);setMode(false)};
  const patchAnchor=(id:string,nextComments:ThreadComment[],resolved?:boolean)=>setList(list.map(item=>item.id===id?{...item,comments:nextComments,...(resolved!==undefined?{resolved}:{})}:item));
  return <div ref={root} className={`cap-inline-comments ${className}`} data-comment-mode={mode||undefined}><div className="cap-inline-content">{children}</div><div className="cap-inline-toolbar"><button type="button" aria-pressed={mode} onClick={()=>setMode(!mode)}>{mode?'Cancel placing':'Add comment'}</button></div>{mode&&<div className="cap-inline-placement" role="button" aria-label="Choose where to comment" onPointerDown={place} onKeyDown={e=>{if(e.key==='Escape'){setMode(false);requestAnimationFrame(()=>root.current?.querySelector<HTMLButtonElement>('.cap-inline-toolbar button')?.focus())}else if(e.key==='Enter'||e.key===' '){e.preventDefault();const rect=root.current?.getBoundingClientRect();if(rect)place({clientX:rect.left+rect.width/2,clientY:rect.top+rect.height/2} as ReactPointerEvent<HTMLDivElement>)}}} tabIndex={0}><span className="cap-inline-placement-hint">Click or press Enter to place a comment</span></div>}{list.map((item,i)=><button key={item.id} ref={pinRef(item.id)} type="button" className="cap-inline-pin" style={{left:`${item.x*100}%`,top:`${item.y*100}%`} as CSSProperties} aria-label={`Open comment ${i+1}`} aria-controls={selected===item.id?`inline-thread-${item.id}`:undefined} aria-expanded={selected===item.id} onClick={()=>setSelected(selected===item.id?null:item.id)}>{i+1}</button>)}{popupPresent&&lastActive.current&&<InlineThreadPopup key={lastActive.current.id} anchorRef={pinRef(lastActive.current.id)} anchorId={lastActive.current.id} anchorIndex={Math.max(0,list.indexOf(lastActive.current))} title={lastActive.current.title} currentUser={currentUser} people={people} comments={lastActive.current.comments} resolved={lastActive.current.resolved} open={!!active} onClose={()=>setSelected(null)} onResolvedChange={resolved=>patchAnchor(lastActive.current!.id,lastActive.current!.comments,resolved)} onCommentsChange={next=>patchAnchor(lastActive.current!.id,next)}/>}</div>
}
