import { MovingHighlight } from './moving-highlight.js';
import { useEffect, useId, useLayoutEffect, useRef, useState, type ReactNode } from 'react';
import { Button, Icon, cx, type Size } from './primitives.js';
import { OverlayPortal, useAnchoredOverlay, useOverlayDismiss, useOverlayPresence, useOverlayScope } from './overlays.js';

export interface NavigationMenuItem { id:string; label:string; href?:string; content?:ReactNode; disabled?:boolean; onSelect?:()=>void }
export interface NavigationMenuProps { label:string; items:NavigationMenuItem[]; activeId?:string; size?:Size; leading?:ReactNode; trailing?:ReactNode; className?:string }
/** Disclosure navigation, rather than ARIA tabs: panels may contain ordinary links and forms. */
export function NavigationMenu({label,items,activeId,size='md',leading,trailing,className}:NavigationMenuProps){
 const [open,setOpen]=useState<string|null>(null),id=useId(),root=useRef<HTMLElement>(null),track=useRef<HTMLDivElement>(null),lastTrigger=useRef<HTMLButtonElement>(null),panel=useRef<HTMLDivElement>(null),timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined),hoverClick=useRef<string|null>(null),focusPanelOnOpen=useRef(false);
 useEffect(()=>()=>clearTimeout(timer.current),[]);
 const current=items.find(item=>item.id===open),lastOpen=useRef<string|null>(null);if(current)lastOpen.current=current.id;
 const shown=current??items.find(item=>item.id===lastOpen.current),scope=useOverlayScope(root),position=useAnchoredOverlay(!!current,root,panel,{matchWidth:true}),present=useOverlayPresence(!!current);
 useLayoutEffect(()=>{if(!current||!focusPanelOnOpen.current)return;focusPanelOnOpen.current=false;panel.current?.querySelector<HTMLElement>('a[href],button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),[tabindex]:not([tabindex="-1"])')?.focus();},[current]);
 const close=(restore=false)=>{clearTimeout(timer.current);setOpen(null);if(restore)lastTrigger.current?.focus();};
 useOverlayDismiss(!!current,panel,root,restore=>close(restore));
 const show=(item:NavigationMenuItem,target?:HTMLButtonElement)=>{clearTimeout(timer.current);if(target)lastTrigger.current=target;setOpen(item.id);};
 const scheduleClose=()=>{clearTimeout(timer.current);timer.current=setTimeout(()=>{if(!root.current?.contains(document.activeElement)&&!panel.current?.contains(document.activeElement))setOpen(null);},120);};
 const moveFocus=(event:React.KeyboardEvent<HTMLDivElement>)=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;const enabled=Array.from(event.currentTarget.querySelectorAll<HTMLElement>('button:not(:disabled),a[href]:not([aria-disabled=true])'));let index=enabled.indexOf(document.activeElement as HTMLElement);if(index<0)return;event.preventDefault();index=event.key==='Home'?0:event.key==='End'?enabled.length-1:(index+(event.key==='ArrowRight'?1:-1)+enabled.length)%enabled.length;enabled[index]?.focus();};
 return <nav ref={root} className={cx('cap-navigation-menu',className)} data-size={size} aria-label={label} onPointerEnter={()=>clearTimeout(timer.current)} onPointerLeave={scheduleClose} onBlur={event=>{if(!root.current?.contains(event.relatedTarget as Node|null)&&!panel.current?.contains(event.relatedTarget as Node|null))close();}}>
 {leading}<div ref={track} className="cap-navigation-items cap-shared-hover" onKeyDown={moveFocus}><MovingHighlight root={track} hover target="button:not(:disabled):not([aria-current=page]),a[href]:not([aria-current=page])"/>{items.map(item=>item.content?<Button key={item.id} size={size} variant="ghost" disabled={item.disabled} aria-expanded={item.id===open} aria-controls={item.id===open?`${id}-panel`:undefined} aria-current={activeId===item.id?'page':undefined} onClick={event=>{const justHovered=hoverClick.current===item.id;hoverClick.current=null;if(justHovered){show(item,event.currentTarget);return;}if(item.id===open)close();else show(item,event.currentTarget);}} onPointerEnter={event=>{if(event.pointerType!=='touch'){hoverClick.current=item.id;show(item,event.currentTarget);}}} onFocus={event=>{if(open!==null&&open!==item.id)show(item,event.currentTarget);}} onKeyDown={event=>{if(event.key==='ArrowDown'){event.preventDefault();lastTrigger.current=event.currentTarget;focusPanelOnOpen.current=true;if(open===item.id)panel.current?.querySelector<HTMLElement>('a[href],button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),[tabindex]:not([tabindex="-1"])')?.focus();else show(item,event.currentTarget);}}} trailing={<Icon name="down" size={12}/ >}>{item.label}</Button>:<a key={item.id} href={item.disabled?undefined:item.href} aria-disabled={item.disabled||undefined} aria-current={activeId===item.id?'page':undefined} className="cap-text-action" onFocus={()=>close()} onPointerEnter={event=>{if(event.pointerType!=='touch')close();}} onClick={event=>{if(item.disabled){event.preventDefault();return;}item.onSelect?.();}}>{item.label}</a>)}</div>{trailing}
 {present&&shown&&<OverlayPortal anchor={root} panel={panel}><div {...scope} id={`${id}-panel`} ref={panel} className="cap-navigation-panel cap-shared-hover" role="region" aria-label={shown.label} aria-hidden={!current} inert={!current} data-state={current?'open':'closed'} style={position} onPointerEnter={()=>clearTimeout(timer.current)} onPointerLeave={scheduleClose} onKeyDown={event=>{if(event.key==='Escape'){event.preventDefault();close(true);}}} onBlur={event=>{if(!panel.current?.contains(event.relatedTarget as Node|null)&&!root.current?.contains(event.relatedTarget as Node|null))close();}}><MovingHighlight root={panel} hover target=".cap-navigation-grid > a[href]"/>{shown.content}</div></OverlayPortal>}
 </nav>;
}

export interface HoverPanelProps { label:string; summary:ReactNode; children:ReactNode; size?:Size; open?:boolean; onOpenChange?:(open:boolean)=>void; openDelay?:number; closeDelay?:number; className?:string }
/** Hover previews remain reachable by focus and click on touch screens. */
export function HoverPanel({label,summary,children,size='md',open:controlled,onOpenChange,openDelay=220,closeDelay=100,className}:HoverPanelProps){
 const [local,setLocal]=useState(false),open=controlled??local,id=useId(),root=useRef<HTMLDivElement>(null),trigger=useRef<HTMLButtonElement>(null),panel=useRef<HTMLDivElement>(null),timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined),openTimer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined),pointerInside=useRef(false),openedByFocus=useRef(false),openedByPointer=useRef(false),restoringFocus=useRef(false);
 const setOpen=(next:boolean)=>{if(controlled===undefined)setLocal(next);onOpenChange?.(next);};
 const scope=useOverlayScope(root),position=useAnchoredOverlay(open,root,panel,{matchWidth:true}),present=useOverlayPresence(open);
 const close=(restore=false)=>{clearTimeout(timer.current);clearTimeout(openTimer.current);setOpen(false);if(restore){restoringFocus.current=true;trigger.current?.focus();queueMicrotask(()=>{restoringFocus.current=false;});}};
 const enterPointer=()=>{pointerInside.current=true;clearTimeout(timer.current);};
 const scheduleClose=()=>{pointerInside.current=false;clearTimeout(openTimer.current);clearTimeout(timer.current);timer.current=setTimeout(()=>{if(!pointerInside.current&&!root.current?.contains(document.activeElement)&&!panel.current?.contains(document.activeElement))setOpen(false);},Math.max(0,closeDelay));};
 useOverlayDismiss(open,panel,trigger,restore=>close(restore));
 useEffect(()=>()=>{clearTimeout(timer.current);clearTimeout(openTimer.current)},[]);
 return <div ref={root} className={cx('cap-hover-panel',className)} onPointerEnter={event=>{enterPointer();if(event.pointerType!=='touch'){clearTimeout(openTimer.current);openTimer.current=setTimeout(()=>{if(pointerInside.current){openedByPointer.current=true;setOpen(true);}},Math.max(0,openDelay));}}} onPointerLeave={scheduleClose}>
 <Button ref={trigger} size={size} aria-expanded={open} aria-controls={open?id:undefined} onClick={()=>{clearTimeout(openTimer.current);if(openedByFocus.current||openedByPointer.current){openedByFocus.current=false;openedByPointer.current=false;setOpen(true);return;}setOpen(!open);}} onFocus={()=>{clearTimeout(openTimer.current);if(restoringFocus.current){restoringFocus.current=false;return;}openedByFocus.current=true;setOpen(true);}} onBlur={event=>{if(!panel.current?.contains(event.relatedTarget as Node|null)&&!root.current?.contains(event.relatedTarget as Node|null)&&!pointerInside.current)close();}}>{summary}</Button>
 {present&&<OverlayPortal anchor={root} panel={panel}><div {...scope} ref={panel} id={id} role="region" aria-label={label} aria-hidden={!open} inert={!open} data-state={open?'open':'closed'} className="cap-hover-panel-content" style={position} onPointerEnter={()=>{enterPointer();openedByPointer.current=true;}} onPointerLeave={scheduleClose} onBlur={event=>{if(!panel.current?.contains(event.relatedTarget as Node|null)&&!root.current?.contains(event.relatedTarget as Node|null)&&!pointerInside.current)close();}}>{children}</div></OverlayPortal>}
 </div>;
}
