import { useState } from 'react';
import { Badge, Button, IconBox, Tag, TypeLabel, Icon, colors, type Color } from '../src/components/primitives';
import { Card, CodeBlock } from '../src/components/layout';
import { Select } from '../src/components/forms';
import palettes from '../src/tokens/accents.json';
import catalog from '../src/tokens/catalog.json';
const steps = Array.from({ length: 12 }, (_, i) => i + 1);
export default function ColorsV2({ theme, copy }: { theme: 'light' | 'dark'; copy: (value: string) => void }) {
  const [accent, setAccent] = useState<Color>('blue');
  return <><header className="page-intro"><div className="eyebrow">ОСНОВЫ / ЦВЕТ</div><h1>Одна шкала. Любой акцент.</h1><p>Neutral остаётся серым. Accent переключает цвет выбранного контейнера. Light и Dark задают внешний вид; поверхность регулирует плотность вторичных заливок.</p></header>
    <section className="v2-color-section"><div className="section-heading"><h2>Neutral</h2><span className="muted">Постоянная grayscale-шкала</span></div><div className="v2-ramp">{steps.map(n => <button key={n} onClick={() => copy(`var(--cap-neutral-${n})`)} aria-label={`Скопировать neutral ${n}`}><span style={{ background: `var(--cap-neutral-${n})` }} /><strong>{n}</strong><small>{palettes.neutral[n as unknown as keyof typeof palettes.neutral]}</small></button>)}</div></section>
    <section className="v2-color-section"><div className="section-heading"><h2>Accent</h2><label className="v2-mode-select">Мод<Select aria-label="Акцентный мод" value={accent} onValueChange={v => setAccent(v as Color)} options={colors.map(c => ({ value: c, label: c }))} /></label></div><div className="v2-mode-pills">{colors.map(c => <button key={c} data-accent={c} aria-pressed={accent === c} onClick={() => setAccent(c)}><span />{c}</button>)}</div>
      <div className="v2-accent-scope" data-accent={accent}><div className="v2-ramp">{steps.map(n => <button key={n} onClick={() => copy(`var(--cap-accent-${n})`)} aria-label={`Скопировать accent ${n}`}><span style={{ background: `var(--cap-accent-${n})` }} /><strong>{n}</strong><small>accent/{n}</small></button>)}</div>
      <div className="v2-mode-preview"><div className="v2-mode-object"><IconBox icon="cube" size="lg" /><div><TypeLabel icon="cube">Проект</TypeLabel><h3>Сад идей</h3><p>Одинаковая разметка. Цвет наследуется от контейнера.</p><div className="demo-row"><Tag>Исследование</Tag><Badge variant="outline">В процессе</Badge></div></div></div><div className="demo-stack"><Button variant="accent" leading={<Icon name="plus" />}>Акцентное действие</Button><Button>Нейтральное действие</Button><Badge variant="solid">Solid badge</Badge></div></div>
      <div className="v2-role-chips">{['soft','bg','block','border','text','ink','solid','solid-hover','on-solid'].map(role => <button key={role} onClick={() => copy(`var(--cap-accent-${role})`)}><span style={{background:`var(--cap-accent-${role})`}}/><code>{role}</code></button>)}</div></div>
    </section>
    <section className="v2-color-section"><div className="section-heading"><h2>Цвет относительно поверхности</h2></div><div className="v3-surface-comparison" data-accent={accent}>{(['raised','canvas','base'] as const).map(surface => <div key={surface} data-surface={surface} style={{background:'var(--cap-surface-current)',padding:20,borderRadius:14}}><h3>{surface === 'raised' ? 'Приподнятая' : surface === 'canvas' ? 'Фоновая' : 'Базовая'}</h3><div className="demo-row"><Button>Secondary</Button><Tag>Accent</Tag></div><p style={{color:'var(--cap-content-muted)'}}>Поддерживающий текст</p></div>)}</div><p className="muted">Одинаковые компоненты получают разную плотность заливки через data-surface. Режим «Обводки» меняет рамки и нейтральную заливку; фокус и ошибки всегда остаются видимыми.</p></section>
    <div className="example-grid"><Card><h2>Два независимых переключателя</h2><div className="v2-variable-flow"><span>Neutral <small>12 фиксированных значений</small></span><Icon name="arrow"/><span>Accent <small>12 имён × 18 модов</small></span><Icon name="arrow"/><span>Appearance <small>Light / Dark → роли</small></span></div><p className="muted">В Figma — 48 Variables в трёх коллекциях. Цвет не зашит в имя компонента или переменной роли.</p></Card><CodeBlock label="Наследование локального мода">{'<html data-theme="dark">\n  <section data-accent="purple">\n    <Tag>Исследование</Tag>\n    <Button variant="accent">Создать</Button>\n    <div data-accent="teal">\n      <Badge>Локальный мод</Badge>\n    </div>\n  </section>\n</html>'}</CodeBlock></div>
    <div className="section-heading"><h2>Базовые роли Figma</h2></div><div className="token-list"><div className="token-list-head"><span>Переменная</span><span>{theme} · neutral</span></div>{catalog.map(t => <button className="token-row" key={t.name} onClick={() => copy(`var(${t.name})`)}><span className="token-swatch" style={{background:t[theme]}}/><code>{t.name}</code><span className="token-value">{t[theme]}</span><Icon name="copy" size={13}/></button>)}</div>
  </>;
}
