import { useEffect, useRef, useState } from 'react';
import * as UI from '../src';
import { preserveMarkdownSourceEdit } from '../src/components/rich-text-markdown';
import { MarkdownRichTextEditor } from '../src/components/markdown-rich-text-editor';
import { documentFiles, type DocumentFile } from './document-files';
const documentErrors: Record<string,string> = {"Symbolic links cannot be edited.": "Ссылки на другие файлы не редактируются.", "Document text and revision are required.": "Нужны текст и версия документа.", "Document exceeds 256 KB.": "Документ превышает 256 КБ.", "The file changed in another editor. Your draft is preserved; compare the current version.": "Файл изменён другим редактором. Ваш текст сохранён в черновике; откройте актуальную версию для сравнения.", "The editor is only available locally.": "Редактор доступен только локально.", "Method not supported.": "Метод не поддерживается.", "Use the local editor to save documents.": "Сохраняйте документ из локального редактора.", "Invalid request.": "Некорректный запрос.", "Could not read or save the file.": "Не удалось прочитать или сохранить файл.", "Instruction parent cannot be a symbolic link.": "Папка инструкций не может быть ссылкой.", "Instruction directory cannot be a symbolic link.": "Папка инструкций не может быть ссылкой.", "Document not found.": "Документ не найден.", "Use a filename with letters, numbers, hyphens or underscores, ending in .md.": "Имя должно содержать буквы, цифры, дефисы или подчёркивания и заканчиваться на .md.", "Document content must be text.": "Содержимое должно быть текстом.", "A file with this name already exists.": "Файл с таким именем уже существует.", "Core instructions cannot be deleted.": "Основные инструкции нельзя удалить.", "The file changed. Read the current version before deleting.": "Файл изменился. Прочитайте актуальную версию перед удалением."};
type Doc={path:string;content:string;revision:string};
const draftKey=(path:string)=>'cap-document-draft:'+path;
function draft(path:string){try{return sessionStorage.getItem(draftKey(path));}catch{return null;}}
export default function Documents(){
 const t=UI.useTranslate();
 const errorText=(value:string)=>t(documentErrors[value]??value,value);
 const [files,setFiles]=useState<DocumentFile[]>(documentFiles),[creating,setCreating]=useState(false),[filename,setFilename]=useState(''),[deleting,setDeleting]=useState(false);
 const [path,setPath]=useState<string>('AGENTS.md'),[doc,setDoc]=useState<Doc>(),[text,setText]=useState(''),[editing,setEditing]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState(''),[discard,setDiscard]=useState(false),[latest,setLatest]=useState<Doc>(),[savedDraft,setSavedDraft]=useState<string|null>(null);
 const [sourceMode,setSourceMode]=useState(false);
 const refresh=async()=>{const response=await fetch(import.meta.env.DEV?'/__docs':'./documents.json');const data=await response.json();if(!response.ok)throw Error(data.error);setFiles(data.files);};
 useEffect(()=>{void refresh().catch(e=>setError(e.message));},[]);
 const mutate=async(method:'POST'|'DELETE')=>{setBusy(true);setError('');try{const target=method==='POST'?'docs/instructions/'+filename:path;const response=await fetch('/__docs?path='+encodeURIComponent(target),{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(method==='POST'?{content:'# '+filename.replace(/\.md$/,'')+'\n'}:{revision:doc?.revision})});const data=await response.json();if(!response.ok)throw Error(data.error);await refresh();setCreating(false);setDeleting(false);if(method==='DELETE'){try{sessionStorage.removeItem(draftKey(path));}catch{}setPath('AGENTS.md');setDoc(undefined);}else{setPath(target);setDoc(undefined);setFilename('');}}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 const generation=useRef(0),dirty=!!doc&&text!==doc.content;
 const remember=(value:string)=>{setText(value);setSavedDraft(value);try{sessionStorage.setItem(draftKey(path),value);}catch{}};
 const load=async(file:string)=>{
  const id=++generation.current;setBusy(true);setError('');setMessage('');setLatest(undefined);
  try{let value:Doc;if(import.meta.env.DEV){const response=await fetch('/__docs?path='+encodeURIComponent(file));const data=await response.json();if(!response.ok)throw Error(data.error);value=data;}else{const response=await fetch('./documents.json');const data=await response.json();value=data.files.find((item:Doc)=>item.path===file);}
   if(id!==generation.current)return;setDoc(value);setText(value.content);setSavedDraft(draft(file));setEditing(false);setSourceMode(false);
  }catch(e){if(id===generation.current)setError(String((e as Error).message));}finally{if(id===generation.current)setBusy(false);}
 };
 useEffect(()=>{void load(path);},[path]);
 useEffect(()=>{const leave=(e:BeforeUnloadEvent)=>{if(editing&&dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',leave);return()=>window.removeEventListener('beforeunload',leave);},[editing,dirty]);
 const save=async()=>{
  if(!doc||busy)return;setBusy(true);setError('');setMessage('');
  try{const response=await fetch('/__docs?path='+encodeURIComponent(path),{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({content:text,revision:doc.revision})});const data=await response.json();if(!response.ok)throw Error(data.error);setDoc(data);setEditing(false);setMessage(t('Сохранено в ','Saved to ')+path);setSavedDraft(null);try{sessionStorage.removeItem(draftKey(path));}catch{}
  }catch(e){setError((e as Error).message);}finally{setBusy(false);}
 };
 const cancel=()=>{setText(doc?.content??'');setEditing(false);setDiscard(false);setLatest(undefined);setError('');setSavedDraft(null);try{sessionStorage.removeItem(draftKey(path));}catch{}};
 return <><header className="page-intro"><h1>{t('Инструкции','Instructions')}</h1><p>{t('Правила и примеры для использования системы.','Rules and examples for using the system.')}</p></header><div className="catalog-documents">
  <nav aria-label={t('Документы','Documents')} className="catalog-document-nav">{files.map(file=>{const dot=file.label.lastIndexOf('.');return <UI.Button key={file.path} variant="ghost" size="sm" title={file.label} aria-label={file.label} aria-current={path===file.path?'page':undefined} disabled={editing||busy} onClick={()=>{setDoc(undefined);setPath(file.path);}}><span className="catalog-document-nav-name"><span className="catalog-document-nav-base">{dot>0?file.label.slice(0,dot):file.label}</span>{dot>0&&<span className="catalog-document-nav-ext">{file.label.slice(dot)}</span>}</span></UI.Button>;})}{import.meta.env.DEV&&<UI.Button size="sm" variant="ghost" disabled={editing||busy} onClick={()=>{setError('');setCreating(true);}}>{t('Создать файл','Create file')}</UI.Button>}</nav>
  <section className="catalog-document cap-surface-boundary" data-surface="raised" aria-busy={busy}><div className="catalog-document-toolbar"><code>{path}</code><div>{!editing&&import.meta.env.DEV&&<UI.Button size="sm" variant="ghost" disabled={busy||!doc||files.find(file=>file.path===path)?.protected} title={files.find(file=>file.path===path)?.protected?t("Основной контракт защищён от удаления","Core contract is protected from deletion"):undefined} onClick={()=>{setError('');setDeleting(true);}}>{t("Удалить","Delete")}</UI.Button>}{editing?<><UI.Button size="sm" variant="ghost" disabled={busy} onClick={()=>dirty?setDiscard(true):cancel()}>{t('Отмена','Cancel')}</UI.Button><UI.Button size="sm" disabled={busy||!dirty} onClick={save}>{busy?t('Сохранение…','Saving…'):t('Сохранить','Save')}</UI.Button></>:<UI.Button size="sm" disabled={busy||!doc||!import.meta.env.DEV} title={!import.meta.env.DEV?t('Редактирование доступно в npm run dev','Editing is available with npm run dev'):undefined} onClick={()=>{setEditing(true);setSourceMode(false);setMessage('');}}>{t('Редактировать','Edit')}</UI.Button>}</div></div>
   {error&&<UI.Callout color="red" title={editing?t('Не удалось сохранить изменения','Changes could not be saved'):t('Документ недоступен','Document unavailable')}>{errorText(error)}{editing&&<UI.Button size="sm" variant="ghost" onClick={async()=>{const response=await fetch('/__docs?path='+encodeURIComponent(path));if(response.ok)setLatest(await response.json());}}>{t('Показать версию на диске','Show disk version')}</UI.Button>}</UI.Callout>}
   {message&&<p role="status" className="catalog-document-status">{message}</p>}
   {doc&&!editing&&savedDraft&&savedDraft!==doc.content&&<UI.Callout title={t('Есть несохранённый черновик','An unsaved draft is available')}><UI.Button size="sm" variant="ghost" onClick={()=>{setText(savedDraft!);setSourceMode(false);setEditing(true);}}>{t('Восстановить','Restore')}</UI.Button><UI.Button size="sm" variant="ghost" onClick={cancel}>{t('Удалить черновик','Delete draft')}</UI.Button></UI.Callout>}
   {!doc&&!error?<p role="status">{t('Загрузка…','Loading…')}</p>:editing?<><UI.Tabs label={t('Режим редактирования инструкций','Instruction editing mode')} variant="segment" items={[{value:'rich',label:t('Форматированный текст','Rich text'),content:null},{value:'markdown',label:'Markdown',content:null}]} value={sourceMode?'markdown':'rich'} onValueChange={value=>setSourceMode(value==='markdown')}/>{sourceMode?<UI.Textarea value={text} onChange={event=>remember(preserveMarkdownSourceEdit(text,event.target.value))} label={t('Редактор ','Editor ')+path} disabled={busy} rows={24} className="catalog-document-editor"/>:<MarkdownRichTextEditor value={text} onValueChange={remember} label={t('Редактор ','Editor ')+path} disabled={busy} className="catalog-document-editor"/>}</>:doc&&<UI.MarkdownPreview value={doc.content}/>}
   {latest&&<section className="catalog-conflict"><h2>{t('Версия на диске','Disk version')}</h2><UI.MarkdownPreview value={latest.content}/><UI.Button size="sm" onClick={()=>{setDoc(latest);setLatest(undefined);setError('');setMessage(t('Актуальная версия прочитана. Проверьте ваш текст перед сохранением.','Current version loaded. Review your text before saving.'));}}>{t('Продолжить с моим текстом','Continue with my text')}</UI.Button></section>}
  </section></div>
  <UI.Dialog open={discard} onOpenChange={setDiscard} title={t('Отменить изменения?','Discard changes?')} footer={<><UI.Button variant="ghost" onClick={()=>setDiscard(false)}>{t('Продолжить редактирование','Continue editing')}</UI.Button><UI.Button variant="danger" onClick={cancel}>{t('Отменить изменения','Discard changes')}</UI.Button></>}>{t('Несохранённый черновик этого файла будет удалён.','The unsaved draft for this file will be deleted.')}</UI.Dialog>
 <UI.Dialog open={creating} onOpenChange={setCreating} title={t("Создать инструкцию","Create instruction")} footer={<UI.Button disabled={busy||!filename} onClick={()=>mutate("POST")}>{t("Создать","Create")}</UI.Button>}>{error&&<UI.Callout color="red" title={t("Не удалось создать файл","File could not be created")}>{errorText(error)}</UI.Callout>}<UI.Input label={t("Имя файла","Filename")} hint={t("Например: project-rules.md. Сохраняется в docs/instructions.","Example: project-rules.md. Saved in docs/instructions.")} value={filename} onChange={event=>setFilename(event.target.value)}/></UI.Dialog>
 <UI.Dialog open={deleting} onOpenChange={setDeleting} title={t("Удалить инструкцию?","Delete instruction?")} footer={<UI.Button variant="danger" disabled={busy} onClick={()=>mutate("DELETE")}>{t("Удалить файл","Delete file")}</UI.Button>}>{error&&<UI.Callout color="red" title={t("Не удалось удалить файл","File could not be deleted")}>{errorText(error)}<UI.Button size="sm" variant="ghost" disabled={busy} onClick={()=>load(path)}>{t("Прочитать актуальную версию","Read current version")}</UI.Button></UI.Callout>}{t("Файл и его локальный черновик будут удалены с диска. Действие нельзя отменить в редакторе.","The file and its local draft will be deleted. The editor cannot undo this action.")}</UI.Dialog>
 </>;
}
