import { useState } from 'react';
import * as UI from '../src';
import './layers.css';
const surfaces = ['canvas','base','raised','floating'] as const;
export default function Layers() {
 const [shadow,setShadow]=useState('soft');
 const [message,setMessage]=useState('Выберите действие в любой панели.'),[dialog,setDialog]=useState<string|null>(null);
 const options=[{value:'normal',label:'Обычный пункт'},{value:'second',label:'Следующий пункт'},{value:'disabled',label:'Недоступно',disabled:true}];
 return <><header className="page-intro"><div className="eyebrow">ОСНОВЫ / СЛОИ</div><h1>Границы и всплывающие слои</h1><p>Толщина — 0,5 px. Оттенок зависит от поверхности и назначения: мягкая граница панели, граница контрола, усиление и значимый индикатор. Floating светлее Raised в тёмной теме; мягкая тень лишь поддерживает отделение слоёв.</p></header>
 <section className="catalog-foundation-section"><h2>Степени контраста</h2><div className="layer-grid">{surfaces.map(surface=><section key={surface} className="layer-surface" data-surface={surface}><h3>{surface}</h3><div className="border-levels">{['subtle','default','strong','emphasis'].map(level=><div key={level} style={{border:`var(--cap-border-width) solid var(--cap-border-${level})`}}>{level}</div>)}</div><p>Последняя степень — для значимого выделения, а не для каждой рамки.</p></section>)}</div></section>
 <section className="catalog-foundation-section"><h2>Окна и поверхности</h2><UI.SegmentedControl label="Тень" value={shadow} onValueChange={setShadow} options={[{value:"soft",label:"Мягкая"},{value:"compact",label:"Компактная"}]}/><p>В каждой паре слева обводки выключены, справа включены. Откройте меню, подсказку или вложенный список; тема переключается в плавающей панели.</p><div className="layer-grid" data-shadow={shadow}>{surfaces.map(surface=><section key={surface} className="layer-surface" data-surface={surface}><h3>{surface}</h3><div className="layer-pair">{(['off','on'] as const).map(borders=><div key={borders} data-borders={borders} className="layer-case"><h4>Borders {borders}</h4><UI.ButtonGroup label={`${surface} ${borders} представление`} prefix="99+"><UI.IconButton label={`${surface} ${borders} фильтр`} icon="filter" variant="ghost" onClick={()=>setMessage('Фильтр применён')}/><UI.IconButton label={`${surface} ${borders} карточки`} icon="grid" variant="ghost" aria-pressed/><UI.IconButton label={`${surface} ${borders} список`} icon="list" variant="ghost" disabled/></UI.ButtonGroup><UI.FloatingActionBar label={`${surface} ${borders} действия`} position="static" size="sm"><UI.Menu label={`${surface} ${borders} меню`} icon="menu" items={[{id:'open',label:'Открыть',onSelect:()=>setMessage('Открыто')},{id:'copy',label:'Дублировать',onSelect:()=>setMessage('Копия создана')},{id:'disabled',label:'Недоступно',disabled:true}]}/><UI.Tooltip content="Подсказка над панелью"><UI.IconButton label={`${surface} ${borders} помощь`} icon="info" variant="ghost"/></UI.Tooltip><UI.Popover label="Фильтр"><div className="catalog-stack"><UI.Field label="Показать">{props=><UI.Select {...props} aria-label={`${surface} ${borders} вложенный выбор`} defaultValue="normal" options={options}/>}</UI.Field><UI.Button onClick={()=>setDialog(surface+'-'+borders)}>Открыть диалог</UI.Button></div></UI.Popover></UI.FloatingActionBar><UI.Select aria-label={`${surface} ${borders} выбор`} defaultValue="normal" options={options}/><UI.Tag color="purple" onClick={()=>setMessage('Тег выбран')}>Тег</UI.Tag><UI.Dialog open={dialog===surface+'-'+borders} onOpenChange={open=>setDialog(open?surface+'-'+borders:null)} title="Настройки представления" footer={<UI.Button onClick={()=>setDialog(null)}>Готово</UI.Button>}><UI.Select aria-label="Выбор внутри диалога" defaultValue="normal" options={options}/></UI.Dialog></div>)}</div></section>)}</div><p role="status">{message}</p></section>

 <section className="catalog-foundation-section"><h2>Figma</h2><p>Primitives содержит number/border/width = 0.5. Semantic определяет цвет границы по теме, поверхности и элементу. Отдельная служебная коллекция Borders переключает Off / On на элементе или родительском фрейме.</p></section></>;
}
