import { ControlList } from './ControlList';
import { ArcPlayground, arcPlaygrounds } from './PlaygroundArc';
import type { ArcComponentName } from './catalog-arc';
import { useId, useState, type ReactNode } from 'react';
import * as UI from '../src';
import { useIconCatalogue } from './useIconCatalogue';
import { CardComposer, ReorderExample } from './CardComposer';
import { scheduleEvents } from '../examples/CalendarSchedule';
import type { ComponentName } from './catalog';
import { revisionFiles,revisionRailItems } from './stories-revision';

type Value = string | number | boolean;
type Values = Record<string, Value>;
type Control = { key: string; label: string; initial: Value; options?: readonly string[]; min?: number; max?: number };
type Context = { set: (key: string, value: Value) => void; notify: (message: string) => void; id: string; icons: readonly UI.IconOption[] };
type Spec = { controls: Control[]; render: (p: Values, c: Context) => ReactNode };
const option = (key: string, label: string, options: readonly string[], initial = options[0]): Control => ({key,label,options,initial});
const toggle = (key: string, label: string, initial = false): Control => ({key,label,initial});
const text = (key: string, label: string, initial: string): Control => ({key,label,initial});
const number = (key: string, label: string, initial: number, min = 0, max = 100): Control => ({key,label,initial,min,max});
const size = option('size','Размер',['xs','sm','md','lg','xl'],'md');
const focusControls = [number('focusWidth','Толщина',1,1,4),number('focusOffset','Отступ',1,0,4)];
const focusRing = (p: Values) => ({width:n(p,'focusWidth'),offset:n(p,'focusOffset')});
const fieldLabel = [...focusControls,option('variant','Подложка',['surface','ghost']),text('label','Подпись','Название'),option('labelPlacement','Положение подписи',['outside','inside'],'inside'),toggle('showLabel','Показывать подпись',true)];
const fieldProps = (p: Values) => ({focusRing:focusRing(p),variant:s(p,'variant') as 'surface'|'ghost',label:b(p,'showLabel')?s(p,'label'):undefined,labelPlacement:s(p,'labelPlacement') as 'inside'|'outside'});
const contrast = toggle('contrast','Primary-заливка');
const feedbackControls = [option('tone','Статус',['neutral','info','success','warning','danger'],'success'),option('color','Цвет статуса',['auto','inherit',...UI.colors]),option('appearance','Заливка',['neutral','soft','solid']),toggle('feedbackContrast','Усилить контраст'),option('feedbackSurface','Поверхность сообщения',['inherit','base','canvas','raised','floating'])];
const feedbackProps=(p:Values)=>({tone:s(p,'tone') as UI.FeedbackTone,color:s(p,'color')==='auto'?undefined:s(p,'color') as UI.Color|'inherit',appearance:s(p,'appearance') as 'neutral'|'soft'|'solid',contrast:b(p,'feedbackContrast'),surface:s(p,'feedbackSurface') as 'inherit'|'base'|'canvas'|'raised'|'floating'});
const primaryContrast = toggle('contrast','Primary-заливка',true);
const disabled = toggle('disabled','Disabled');
const label = text('label','Текст','Сад идей');
const icon = option('icon','Иконка',UI.iconNames,'folder');
const variant = option('variant','Стиль',['primary','secondary','accent','accent-secondary','outline','ghost','danger'],'secondary');
const color = option('color','Акцент',['inherit',...UI.colors]);
const s = (p: Values, key: string) => String(p[key] ?? '');
const b = (p: Values, key: string) => p[key] === true;
const n = (p: Values, key: string) => Number(p[key]);
const sz = (p: Values) => s(p,'size') as UI.Size;
const hue = (p: Values) => !p.color || p.color === 'inherit' ? undefined : s(p,'color') as UI.Color;
const glyph = (p: Values, c: Context): UI.IconSource => c.icons.find(option=>option.name===s(p,'icon'))?.icon ?? 'folder';
const buttonStyle = (p: Values) => s(p,'variant') as UI.ButtonProps['variant'];
const make = (controls: Control[], render: Spec['render']): Spec => ({controls,render});
const event = (c: Context, name = 'Действие выполнено') => () => c.notify(name);
const menuItems = (c: Context) => [{id:'open',label:'Открыть',icon:'page' as const,onSelect:event(c,'Объект открыт')},{id:'copy',label:'Дублировать',icon:'copy' as const,onSelect:event(c,'Копия создана')}];
const choices = [{value:'project',label:'Проект'},{value:'note',label:'Заметка'},{value:'book',label:'Книга'}];
const content = 'Здесь можно собрать идеи и вернуться к ним позже.';
const markdown = '# Сад идей\n\nКороткая **заметка** и [ссылка](#Tag).\n\n- Наблюдение\n- Следующий шаг';
const orientation = option('orientation','Направление',['horizontal','vertical']);
const count = text('count','Счётчик','99+');
const boolSlots = [toggle('leading','Иконка слева',true),toggle('trailing','Иконка справа'),toggle('showText','Текст',true)];
const calendarControls = [option('mode','Выбор',['single','range']),text('value','Дата ISO','2026-10-07'),text('rangeEnd','Конец периода',''),option('months','Месяцев',['1','2'],'2'),toggle('showAgenda','Список событий',true),toggle('events','События',true),option('agendaPosition','Расположение событий',['bottom','side']),option('eventEmphasis','Главное в событии',['title','time']),toggle('showEventPreview','Подсказка дня',true),toggle('highlights','Отмеченные даты',true),toggle('limited','Ограничить месяц'),number('fromYear','Годы от',2000,1900,2100),number('toYear','Годы до',2050,2000,2200)];
const calendarProps = (p: Values, c: Context): UI.CalendarSelectionProps => ({
 today:'2026-10-07',defaultMonth:'2026-10',numberOfMonths:Number(s(p,'months')) as 1|2,
 min:b(p,'limited')?'2026-10-01':undefined,max:b(p,'limited')?'2026-10-31':undefined,
 showAgenda:b(p,'showAgenda'),agendaPosition:s(p,'agendaPosition') as 'bottom'|'side',eventEmphasis:s(p,'eventEmphasis') as 'title'|'time',showEventPreview:b(p,'showEventPreview'),
 events:b(p,'events')?scheduleEvents:[],highlightedDates:b(p,'highlights')?[{date:'2026-10-09',label:'Срок передачи',color:'orange'},{date:'2026-10-15',label:'Важная дата',color:'purple'}]:[],
 yearRange:[Math.min(n(p,'fromYear'),n(p,'toYear')),Math.max(n(p,'fromYear'),n(p,'toYear'))],
 ...(s(p,'mode')==='range'?{mode:'range',range:s(p,'value')?{start:s(p,'value'),end:s(p,'rangeEnd')||undefined}:undefined,onRangeChange:(range:UI.CalendarRange)=>{c.set('value',range.start);c.set('rangeEnd',range.end??'');}}:{value:s(p,'value'),onValueChange:(value:string)=>c.set('value',value)}),
});
const actionChildren = (p: Values,c: Context) => <><UI.IconButton icon="filter" label="Фильтр" variant="ghost" onClick={event(c,'Фильтр применён')}/><UI.IconButton icon="list" label="Список" variant="ghost" aria-pressed/><UI.IconButton icon="sliders" label="Настройки" variant="ghost" onClick={event(c,'Настройки открыты')}/></>;
const cardControls = [label,toggle('description','Описание',true),option('density','Плотность',['comfortable','compact']),option('orientation','Направление',['vertical','horizontal']),toggle('selectable','Мультивыбор'),toggle('selected','Выбрано'),option('selectionPosition','Угол выбора',['top-start','top-end'])];
const cardProps = (p: Values,c: Context) => ({title:s(p,'label'),description:b(p,'description')?content:undefined,density:s(p,'density') as 'comfortable'|'compact',orientation:s(p,'orientation') as 'vertical'|'horizontal',selectionPosition:s(p,'selectionPosition') as UI.ContentCardProps['selectionPosition'],selectable:b(p,'selectable'),selected:b(p,'selected'),onSelectedChange:(v:boolean)=>c.set('selected',v),onOpen:event(c,'Карточка открыта')});
const modalControls = [text('label','Заголовок','Настройки'),option('size','Размер',['sm','md','lg','xl'],'md'),toggle('description','Описание',true),toggle('footer','Нижние действия',true),toggle('dismiss','Закрытие по фону',true)];
const modalContent = <UI.Field label="Название">{props=><UI.Input {...props} defaultValue="Сад идей"/>}</UI.Field>;
const modalProps = (p: Values,c: Context) => ({title:s(p,'label'),open:b(p,'open'),onOpenChange:(v:boolean)=>c.set('open',v),size:s(p,'size') as 'sm'|'md'|'lg'|'xl',description:b(p,'description')?'Настройте параметры проекта.':undefined,dismissOnOutside:b(p,'dismiss'),footer:b(p,'footer')?<UI.Button onClick={()=>c.set('open',false)}>Готово</UI.Button>:undefined});

/** One explicit, typed entry per canonical component. Controls mutate real public props. */
export const playgrounds = {
 Button: make([size,variant,label,icon,...boolSlots,disabled,toggle('loading','Loading')],(p,c)=><UI.Button size={sz(p)} variant={buttonStyle(p)} disabled={b(p,'disabled')} loading={b(p,'loading')} aria-label={!b(p,'showText')?s(p,'label'):undefined} leading={b(p,'leading')?<UI.Icon name={glyph(p,c)}/>:undefined} trailing={b(p,'trailing')?<UI.Icon name="down"/>:undefined} onClick={event(c)}>{b(p,'showText')?s(p,'label'):(!b(p,'leading')&&!b(p,'trailing')?<UI.Icon name={glyph(p,c)}/>:null)}</UI.Button>),
 IconButton: make([size,variant,icon,disabled,toggle('loading','Loading')],(p,c)=><UI.IconButton size={sz(p)} variant={buttonStyle(p)} icon={glyph(p,c)} label="Действие" disabled={b(p,'disabled')} loading={b(p,'loading')} onClick={event(c)}/>),
 Icon: make([icon,number('pixels','Размер, px',24,12,64),number('stroke','Толщина штриха',1.65,.5,4)],(p,c)=><UI.Icon name={glyph(p,c)} size={n(p,'pixels')} strokeWidth={n(p,'stroke')}/>),
 ButtonGroup: make([size,orientation,option('color','Цвет',['neutral','inherit',...UI.colors.filter(color=>color!=='neutral')]),toggle('attached','Общая подложка',true),toggle('prefix','Счётчик',true),count],(p,c)=><UI.ButtonGroup label="Действия группы" color={s(p,'color') as UI.Color|'inherit'} size={sz(p)} orientation={s(p,'orientation') as 'horizontal'|'vertical'} attached={b(p,'attached')} prefix={b(p,'prefix')?s(p,'count'):undefined}>{actionChildren(p,c)}</UI.ButtonGroup>),
 SplitButton: make([size,variant,option('layout','Соединение',['joined','separated']),label,toggle('leading','Иконка слева',true),disabled,toggle('loading','Loading')],(p,c)=><UI.SplitButton label={s(p,'label')} size={sz(p)} variant={buttonStyle(p)} layout={s(p,'layout') as 'joined'|'separated'} leading={b(p,'leading')?<UI.Icon name="plus"/>:undefined} disabled={b(p,'disabled')} loading={b(p,'loading')} items={menuItems(c)} onClick={event(c)}/>),
 ActionBar: make([size,orientation,toggle('roving','Навигация стрелками',true)],(p,c)=><UI.ActionBar label="Действия" size={sz(p)} orientation={s(p,'orientation') as 'horizontal'|'vertical'} rovingFocus={b(p,'roving')}>{actionChildren(p,c)}</UI.ActionBar>),
 FloatingActionBar: make([option('size','Размер',['xs','sm','md','lg','xl'],'lg'),orientation,option('variant','Стиль',['surface','divided']),option('position','Положение',['static','sticky']),option('action','Правое действие',['accent','primary','none'],'accent'),toggle('leading','Счётчик слева',true)],(p,c)=>{
  const bar=<UI.FloatingActionBar label="Плавающие действия" position="static" size={s(p,'size') as UI.FloatingActionBarProps['size']} orientation={s(p,'orientation') as 'horizontal'|'vertical'} leading={b(p,'leading')?<UI.Counter value="99+" variant="plain"/>:undefined} variant={s(p,'variant') as 'surface'|'divided'} action={s(p,'action')!=='none'?{label:'Готово',icon:'check',variant:s(p,'action') as 'accent'|'primary',onClick:event(c,'Сохранено')}:undefined}>{actionChildren(p,c)}</UI.FloatingActionBar>;
  return s(p,'position')==='sticky'?<UI.ScrollArea className="playground-floating-stage" label="Прокрутка с действиями" floating={bar}><div className="catalog-long-note">{Array.from({length:8},(_,i)=><p key={i}>{content}</p>)}</div></UI.ScrollArea>:<div className="playground-floating-static">{bar}</div>;
 }),
 Kbd: make([text('label','Клавиши','⌘ K')],p=><UI.Kbd>{s(p,'label')}</UI.Kbd>),
 Input: make([...fieldLabel,size,text('value','Значение',''),text('placeholder','Placeholder','Название'),option('type','Тип',['text','email','password','search']),disabled,toggle('invalid','Ошибка'),toggle('readOnly','Read only')],(p,c)=><UI.Input {...fieldProps(p)} aria-label={b(p,'showLabel')?undefined:"Поле в песочнице"} size={sz(p)} value={s(p,'value')} onChange={e=>c.set('value',e.target.value)} placeholder={s(p,'placeholder')} type={s(p,'type')} disabled={b(p,'disabled')} readOnly={b(p,'readOnly')} aria-invalid={b(p,'invalid')||undefined}/>),
 FloatingField: make([...focusControls,label,text('value','Значение',''),toggle('leading','Иконка слева'),toggle('trailing','Иконка справа'),toggle('error','Ошибка'),disabled],(p,c)=><UI.FloatingField focusRing={focusRing(p)} label={s(p,'label')} value={s(p,'value')} onChange={e=>c.set('value',e.target.value)} leading={b(p,'leading')?<UI.Icon name="search"/>:undefined} trailing={b(p,'trailing')?<UI.Icon name="check"/>:undefined} error={b(p,'error')?'Проверьте значение':undefined} disabled={b(p,'disabled')}/>),
 Textarea: make([...fieldLabel,size,text('value','Значение',content),number('rows','Строки',3,2,10),disabled,toggle('readOnly','Read only')],(p,c)=><UI.Textarea {...fieldProps(p)} size={sz(p)} aria-label={b(p,'showLabel')?undefined:"Заметка в песочнице"} value={s(p,'value')} onChange={e=>c.set('value',e.target.value)} rows={n(p,'rows')} disabled={b(p,'disabled')} readOnly={b(p,'readOnly')}/>),
 Select: make([...fieldLabel,size,option('value','Выбрано',['project','note','book']),toggle('groups','Группы',true),toggle('longOptions','Длинные значения'),disabled,toggle('invalid','Ошибка')],(p,c)=><UI.Select {...fieldProps(p)} aria-label={b(p,'showLabel')?undefined:"Тип объекта в песочнице"} value={s(p,'value')} onValueChange={v=>c.set('value',v)} size={sz(p)} options={choices.map((o,i)=>({...o,label:b(p,'longOptions')?`${o.label} — исследование пользовательского опыта`:o.label,group:b(p,'groups')?(i<2?'Объекты':'Коллекции'):undefined}))} disabled={b(p,'disabled')} aria-invalid={b(p,'invalid')||undefined}/>),
 Field: make([label,toggle('hint','Подсказка',true),toggle('error','Ошибка'),toggle('required','Обязательное')],p=><UI.Field label={s(p,'label')} hint={b(p,'hint')?'Короткое имя проекта':undefined} error={b(p,'error')?'Введите название':undefined} required={b(p,'required')}>{props=><UI.Input {...props}/>}</UI.Field>),
 Checkbox: make([size,primaryContrast,label,toggle('checked','Checked',true),toggle('indeterminate','Indeterminate'),disabled],(p,c)=><UI.Checkbox label={s(p,'label')} contrast={b(p,'contrast')} size={sz(p)} checked={b(p,'checked')} indeterminate={b(p,'indeterminate')} disabled={b(p,'disabled')} onChange={e=>c.set('checked',e.target.checked)}/>),
 Radio: make([size,primaryContrast,option('value','Выбрано',['private','team']),disabled],(p,c)=><fieldset className="playground-radio"><legend className="cap-sr-only">Доступ к проекту</legend>{['private','team'].map((v,i)=><UI.Radio contrast={b(p,'contrast')} key={v} name={c.id} label={i?'Команда':'Только я'} value={v} checked={s(p,'value')===v} size={sz(p)} disabled={b(p,'disabled')} onChange={()=>c.set('value',v)}/>)}</fieldset>),
 Switch: make([size,primaryContrast,label,option('variant','Стиль',['accent','neutral']),toggle('checked','Checked',true),disabled],(p,c)=><UI.Switch label={s(p,'label')} size={sz(p)} contrast={b(p,'contrast')} variant={s(p,'variant') as 'accent'|'neutral'} checked={b(p,'checked')} disabled={b(p,'disabled')} onChange={e=>c.set('checked',e.target.checked)}/>),
 Slider: make([size,contrast,number('value','Значение',48),number('step','Шаг',1,1,25),toggle('showValue','Показывать значение',true),disabled],(p,c)=><UI.Slider contrast={b(p,'contrast')} label="Плотность" size={sz(p)} value={n(p,'value')} onChange={e=>c.set('value',Number(e.target.value))} step={n(p,'step')} showValue={b(p,'showValue')} disabled={b(p,'disabled')}/>),
 SegmentedControl: make([size,option('variant','Стиль',['surface','outline','accent','ghost']),option('value','Выбрано',['grid','list']),toggle('icons','Иконки',true),toggle('disabled','Второй недоступен')],(p,c)=><UI.SegmentedControl size={sz(p)} variant={s(p,'variant') as UI.SegmentedControlProps['variant']} label="Представление в песочнице" value={s(p,'value')} onValueChange={v=>c.set('value',v)} options={['grid','list'].map((v,i)=>({value:v,label:i?'Список':'Карточки',icon:b(p,'icons')?<UI.Icon name={v as 'grid'|'list'}/>:undefined,disabled:i===1&&b(p,'disabled')}))}/>),
 Calendar: make(calendarControls,(p,c)=><UI.Calendar {...calendarProps(p,c)} label="Календарь в песочнице"/>),
 DatePicker: make(calendarControls,(p,c)=><UI.DatePicker {...calendarProps(p,c)} label="Дата в песочнице"/>),
 BottomSheet: make([text('title','Заголовок','Детали проекта'),option('variant','Край',['inset','edge']),number('gap','Отступ от края',12,0,32),option('snap','Высота',['0','1']),toggle('draggable','Перетаскивание',true),toggle('footer','Нижние действия',true)],(p,c)=><><UI.Button onClick={()=>c.set('open',true)}>Открыть нижнюю панель</UI.Button><UI.BottomSheet open={b(p,'open')} onOpenChange={value=>c.set('open',value)} title={s(p,'title')} variant={s(p,'variant') as 'inset'|'edge'} edgeGap={n(p,'gap')} snap={n(p,'snap')} onSnapChange={value=>c.set('snap',String(value))} draggable={b(p,'draggable')} footer={b(p,'footer')?<UI.Button onClick={()=>c.set('open',false)}>Готово</UI.Button>:undefined}><UI.Input label="Название" defaultValue="Сад идей"/><p>Перемещайте ручку или используйте стрелки на клавиатуре.</p></UI.BottomSheet></>),
 FileTree: make([size,toggle('guides','Направляющие',true),toggle('preview','Предпросмотр',true),toggle('empty','Пустое дерево'),toggle('expanded','Раскрыть папки',true)],(p,c)=><UI.FileTree key={String(b(p,'expanded'))} label="Файлы проекта" nodes={b(p,'empty')?[]:revisionFiles} size={sz(p)} showGuides={b(p,'guides')} showPreview={b(p,'preview')} defaultExpandedIds={b(p,'expanded')?revisionFiles.filter(node=>node.type==='folder').map(node=>node.id):[]} onSelect={node=>c.notify(node.name)}/>),
 PreviewRail: make([orientation,option('previewSide','Сторона превью',['before','after'],'after'),toggle('preview','Предпросмотр',true),toggle('active','Выделять выбранный'),toggle('empty','Пустой список')],(p,c)=><UI.PreviewRail label="Разделы проекта" items={b(p,'empty')?[]:revisionRailItems} value={s(p,'selected')||undefined} onValueChange={value=>c.set('selected',value)} orientation={s(p,'orientation') as 'horizontal'|'vertical'} previewSide={s(p,'previewSide') as 'before'|'after'} showPreview={b(p,'preview')} highlightActive={b(p,'active')}/>),
 Chip: make([size,text('label','Текст','Engineering'),option('shape','Форма',['rounded','pill']),toggle('selected','Выбран'),toggle('icon','Иконка',true),toggle('remove','Удаление',true),toggle('count','Счётчик'),disabled],(p,c)=><UI.Chip size={sz(p)} shape={s(p,'shape') as 'rounded'|'pill'} selected={b(p,'selected')} icon={b(p,'icon')?'code':undefined} count={b(p,'count')?12:undefined} disabled={b(p,'disabled')} onClick={()=>c.set('selected',!b(p,'selected'))} onRemove={b(p,'remove')?event(c,'Метка удалена'):undefined}>{s(p,'label')}</UI.Chip>),
 Tag: make([size,option('shape','Форма',['rounded','pill']),option('variant','Стиль',['soft','solid','outline']),label,color,icon,toggle('leading','Иконка слева',true),toggle('showCount','Счётчик',true),count,option('counter','Стиль счётчика',['translucent','plain','accent','white','black']),option('action','Действие',['close','more','none']),toggle('interactive','Интерактивный',true),disabled],(p,c)=><UI.Tag shape={s(p,'shape') as 'rounded'|'pill'} size={sz(p)} variant={s(p,'variant') as 'soft'|'solid'|'outline'} color={hue(p)} icon={b(p,'leading')?glyph(p,c):undefined} count={b(p,'showCount')?s(p,'count'):undefined} counter={{variant:s(p,'counter') as UI.CounterVariant}} interactive={b(p,'interactive')} disabled={b(p,'disabled')} onClick={event(c,'Тег выбран')} action={s(p,'action')==='none'?undefined:{icon:s(p,'action') as 'close'|'more',label:s(p,'action')==='close'?'Удалить тег':'Действия тега',onClick:event(c,s(p,'action')==='close'?'Тег удалён':'Действия тега')}}>{s(p,'label')}</UI.Tag>),
 Counter: make([size,text('value','Значение','99+'),option('variant','Стиль',['neutral','translucent','accent','white','black','plain']),option('shape','Форма',['round','rounded']),color],p=><UI.Counter value={s(p,'value')} size={sz(p)} variant={s(p,'variant') as UI.CounterVariant} shape={s(p,'shape') as 'round'|'rounded'} color={hue(p)}/>),
 TextAction: make([label,toggle('icon','Иконка',true),disabled],(p,c)=><UI.TextAction disabled={b(p,'disabled')} onClick={event(c)}>{b(p,'icon')&&<UI.Icon name="external"/>}{s(p,'label')}</UI.TextAction>),
 ResizableCard: make([number('width','Ширина',360,160,800),number('height','Высота',240,120,800),option('variant','Подложка',['default','subtle','elevated']),toggle('resizable','Изменение размера',true),disabled],(p,c)=><UI.ResizableCard label="Карточка в песочнице" size={{width:n(p,'width'),height:n(p,'height')}} onSizeChange={value=>{c.set('width',value.width);c.set('height',value.height);}} variant={s(p,'variant') as UI.ResizableCardProps['variant']} resizable={b(p,'resizable')} disabled={b(p,'disabled')}><h3>Сад идей</h3><p>Потяните за угол карточки или используйте стрелки, когда ручка в фокусе.</p><UI.Tag color="neutral" interactive={false}>Заметка</UI.Tag></UI.ResizableCard>),
 ContentLayout: make([option('orientation','Ось',['horizontal','vertical']),option('divider','Разделитель',['always','hover','none'],'hover'),toggle('stretch','Растягивать контент',true),toggle('autoStack','Автокомпоновка',true),number('paneHeight','Высота панели',180,100,400),toggle('left','Левая панель',true),toggle('right','Правая панель'),number('leftWidth','Левая ширина',180,160,400),number('rightWidth','Правая ширина',240,160,400),number('contentWidth','Ширина контента',480,200,900)],(p,c)=><UI.ContentLayout collapseAt={b(p,'autoStack')?600:0} minContentSize={200} style={s(p,'orientation')==='vertical'?{height:620}:undefined} orientation={s(p,'orientation') as 'horizontal'|'vertical'} divider={s(p,'divider') as 'always'|'hover'|'none'} stretch={b(p,'stretch')} label="Документ в песочнице" contentWidth={n(p,'contentWidth')} left={{label:'Коллекции',height:n(p,'paneHeight'),onHeightChange:v=>c.set('paneHeight',v),content:<UI.SidebarItem icon="folder" active>Проект</UI.SidebarItem>,open:b(p,'left'),onOpenChange:v=>c.set('left',v),width:n(p,'leftWidth'),onWidthChange:v=>c.set('leftWidth',v)}} right={{label:'Свойства',height:n(p,'paneHeight'),onHeightChange:v=>c.set('paneHeight',v),content:<UI.PropertyRow label="Статус">В работе</UI.PropertyRow>,open:b(p,'right'),onOpenChange:v=>c.set('right',v),width:n(p,'rightWidth'),onWidthChange:v=>c.set('rightWidth',v)}}><div className="catalog-stack"><h3>Сад идей</h3><p>Перетащите разделитель рядом с панелью или нажмите Tab и используйте стрелки. На узком экране автокомпоновка складывает панели.</p><UI.ContentCard title="Следующий шаг" description={content}/></div></UI.ContentLayout>),
 IconPicker: make([size,...focusControls,option('variant','Вид',['combobox','grid']),number('iconSize','Размер иконок',20,12,36),disabled],(p,c)=><UI.IconPicker size={sz(p)} focusRing={focusRing(p)} variant={s(p,'variant') as 'grid'|'combobox'} options={c.icons} value={s(p,'value')} onValueChange={v=>c.set('value',v)} iconSize={n(p,'iconSize')} disabled={b(p,'disabled')} label="Иконка в песочнице"/>),
 IconBox: make([size,icon,color],(p,c)=><UI.IconBox icon={glyph(p,c)} color={hue(p)} size={sz(p)}/>),
 Avatar: make([size,text('label','Имя','Анна Иванова')],p=><UI.Avatar name={s(p,'label')} size={sz(p)}/>),
 Separator: make([orientation,number('length','Длина, px',160,8,600),option('contrast','Контраст',['subtle','normal','strong']),option('reveal','Появление',['always','hover'])],p=><div style={{padding:20,display:'flex',minWidth:60,minHeight:60,maxWidth:'100%'}}><UI.Separator orientation={s(p,'orientation') as 'horizontal'|'vertical'} length={n(p,'length')} contrast={s(p,'contrast') as 'subtle'|'normal'|'strong'} reveal={s(p,'reveal') as 'always'|'hover'}/></div>),
 Card: make([option('variant','Поверхность',['default','subtle','elevated']),label,toggle('description','Описание',true)],p=><UI.Card variant={s(p,'variant') as 'default'|'subtle'|'elevated'}><h3>{s(p,'label')}</h3>{b(p,'description')&&<p>{content}</p>}</UI.Card>),
 ObjectCard: make([label,icon,color,toggle('description','Описание',true),toggle('meta','Свойства',true),disabled],(p,c)=><UI.ObjectCard title={s(p,'label')} icon={glyph(p,c)} color={hue(p)} description={b(p,'description')?content:undefined} meta={b(p,'meta')?'Обновлено сегодня':undefined} disabled={b(p,'disabled')} onClick={event(c,'Объект открыт')}/>),
 CollectionRow: make([label,icon,color,toggle('meta','Счётчик',true),disabled],(p,c)=><UI.CollectionRow title={s(p,'label')} icon={glyph(p,c)} color={hue(p)} meta={b(p,'meta')?<UI.Counter value="99+" size="xs" variant="plain"/>:undefined} disabled={b(p,'disabled')} onClick={event(c,'Коллекция открыта')}/>),
 PropertyRow: make([label,text('value','Значение','В работе'),icon,toggle('leading','Иконка',true)],(p,c)=><UI.PropertyRow label={s(p,'label')} icon={b(p,'leading')?glyph(p,c):undefined}>{s(p,'value')}</UI.PropertyRow>),
 Table: make([text('label','Подпись','Проекты'),number('rows','Строки',3,0,8)],p=><UI.Table caption={s(p,'label')} columns={['Название','Статус']} rows={Array.from({length:n(p,'rows')},(_,i)=>[`Проект ${i+1}`,<UI.Tag key={i}>В работе</UI.Tag>])}/>),
 CodeBlock: make([option('variant','Стиль',['auto','surface','outline','filled-outline'],'surface'),option('language','Язык',['text','tsx','ts','js','json','css','bash']),option('color','Цвет',['neutral','inherit',...UI.colors.filter(color=>color!=='neutral')]),text('filename','Название файла','example.tsx'),toggle('lineNumbers','Номера строк',true),toggle('languageSelector','Выбор языка в блоке',true),toggle('copyable','Копирование',true),toggle('wrap','Перенос строк'),toggle('actions','Дополнительные действия',true)],(p,c)=><UI.CodeBlock filename={s(p,'filename')||undefined} lineNumbers={b(p,'lineNumbers')} language={s(p,'language') as UI.CodeBlockProps['language']} onLanguageChange={value=>c.set('language',value)} color={s(p,'color') as UI.CodeBlockProps['color']} showLanguageSelector={b(p,'languageSelector')} variant={s(p,'variant') as UI.CodeBlockProps['variant']} copyable={b(p,'copyable')} wrap={b(p,'wrap')} showActionsMenu={b(p,'actions')} onWrapChange={value=>c.set('wrap',value)}>{'// Счётчик проекта\nconst count = 99;\n<Tag size="sm" count={count}>Проект</Tag>'}</UI.CodeBlock>),
 MarkdownPreview: make([text('value','Markdown',markdown),number('headingOffset','Сдвиг заголовков',1,0,3)],p=><UI.MarkdownPreview value={s(p,'value')} headingOffset={n(p,'headingOffset') as 0|1|2|3}/>),
 MarkdownEditor: make([text('value','Markdown',markdown),option('mode','Режим',['edit','preview','split']),disabled,toggle('readOnly','Read only')],(p,c)=><UI.MarkdownEditor key={s(p,'mode')} label="Редактор в песочнице" value={s(p,'value')} onValueChange={v=>c.set('value',v)} defaultMode={s(p,'mode') as 'edit'|'preview'|'split'} disabled={b(p,'disabled')} readOnly={b(p,'readOnly')} onSave={event(c,'Заметка сохранена')}/>),
 ContentCard: make(cardControls.filter(control=>control.key!=='description'),(p,c)=><CardComposer {...cardProps(p,c)}/>),
 ReorderableList: make([disabled,toggle('cards','Карточки',true)],p=><ReorderExample disabled={b(p,'disabled')} cards={b(p,'cards')}/>),
 TaskCard: make([...cardControls,color,toggle('completed','Завершена')],(p,c)=><UI.TaskCard {...cardProps(p,c)} color={hue(p)} completed={b(p,'completed')} onCompletedChange={v=>c.set('completed',v)} menuItems={menuItems(c)}/>),
 KanbanColumn: make([label,option('color','Цвет заголовка',['neutral','inherit',...UI.colors.filter(c=>c!=='neutral')]),number('count','Карточки',2,0,5),toggle('action','Кнопка добавления',true)],(p,c)=><UI.KanbanColumn color={s(p,'color') as UI.Color|'inherit'} title={s(p,'label')} count={n(p,'count')} action={b(p,'action')?<UI.IconButton label="Добавить карточку" icon="plus" variant="ghost" onClick={()=>c.set('count',n(p,'count')+1)}/>:undefined}>{Array.from({length:n(p,'count')},(_,i)=><UI.TaskCard key={i} title={`Задача ${i+1}`}/>)}</UI.KanbanColumn>),
 KanbanBoard: make([option('column','Колонка задачи',['todo','done']),toggle('completed','Завершена'),toggle('add','Добавление',true)],(p,c)=><UI.KanbanBoard label="Доска в песочнице" columns={[{id:'todo',title:'В работе'},{id:'done',title:'Готово'}]} items={[{id:'one',columnId:s(p,'column'),title:'Собрать идеи',completed:b(p,'completed')}]} onMove={(_,v)=>c.set('column',v)} onCompletedChange={(_,v)=>c.set('completed',v)} onAdd={b(p,'add')?event(c,'Добавлена карточка'):undefined}/>),
 DailyHeader: make([text('date','Дата ISO','2026-10-07'),toggle('showWeek','Номер недели',true),toggle('tags','Теги',true)],p=><UI.DailyHeader date={s(p,'date')||'2026-10-07'} showWeek={b(p,'showWeek')} tags={b(p,'tags')?<UI.Tag icon="book">Заметки</UI.Tag>:undefined}/>),
 SidebarItem: make([label,icon,color,toggle('active','Активен',true),toggle('showCount','Счётчик',true),number('count','Значение',99,0,999),disabled],(p,c)=><UI.SidebarItem color={s(p,'color') as UI.Color|'inherit'} icon={glyph(p,c)} active={b(p,'active')} count={b(p,'showCount')?n(p,'count'):undefined} disabled={b(p,'disabled')} onClick={()=>c.set('active',!b(p,'active'))}>{s(p,'label')}</UI.SidebarItem>),
 Breadcrumbs: make([number('depth','Уровни',3,1,5)],p=><UI.Breadcrumbs label="Путь в песочнице" items={['Проекты','Коллекции','Сад идей','Заметки','Эскиз'].slice(0,n(p,'depth')).map((label,i,all)=>({label,href:i<all.length-1?'#Breadcrumbs':undefined}))}/>),
 Accordion: make([option('variant','Стиль',['default','navigation','bouncy']),label,toggle('open','Раскрыт',true),toggle('long','Длинный контент')],(p,c)=><UI.Accordion variant={s(p,'variant') as UI.AccordionProps['variant']} title={s(p,'label')} open={b(p,'open')} onToggle={e=>c.set('open',e.currentTarget.open)}>{b(p,'long')?Array(5).fill(content).join(' '):content}</UI.Accordion>),
 Tabs: make([size,option('variant','Стиль',['line','pills','segment','outline','accent']),option('value','Активная',['overview','notes']),toggle('disabled','Вторая недоступна'),toggle('counts','Счётчики',true),option('firstColor','Акцент первой',['inherit',...UI.colors],'blue'),option('secondColor','Акцент второй',['inherit',...UI.colors],'purple')],(p,c)=><UI.Tabs size={sz(p)} label="Разделы в песочнице" variant={s(p,'variant') as UI.TabsProps['variant']} value={s(p,'value')} onValueChange={v=>c.set('value',v)} items={[{value:'overview',label:'Обзор',count:b(p,'counts')?0:undefined,color:s(p,'firstColor') as UI.Color|'inherit',content:<p>{content}</p>},{value:'notes',label:'Заметки',count:b(p,'counts')?24:undefined,color:s(p,'secondColor') as UI.Color|'inherit',content:<p>Новая заметка</p>,disabled:b(p,'disabled')}]}/>),
 SidebarPanel: make([option('surface','Подложка панели',['base','canvas','raised','floating'],'canvas'),number('width','Ширина',280,160,480),toggle('header','Шапка',true),toggle('footer','Нижний блок',true),toggle('actions','Действия',true),option('footerAlign','Выравнивание действий',['start','center','end','stretch']),toggle('groups','Группы',true),toggle('expanded','Первая группа раскрыта',true),toggle('counts','Счётчики',true),toggle('accents','Акценты пунктов',true)],(p,c)=>{const items=<><UI.SidebarItem icon="folder" active={s(p,'active')!=='notes'} color={b(p,'accents')?'blue':'neutral'} count={b(p,'counts')?3:undefined} onClick={()=>c.set('active','project')}>Проект</UI.SidebarItem><UI.SidebarItem icon="book" active={s(p,'active')==='notes'} color={b(p,'accents')?'purple':'neutral'} count={b(p,'counts')?24:undefined} onClick={()=>c.set('active','notes')}>Заметки</UI.SidebarItem></>;return <UI.SidebarPanel surface={s(p,'surface') as 'base'|'canvas'|'raised'|'floating'} label="Панель в песочнице" width={n(p,'width')} header={b(p,'header')?'Навигация':undefined} footerAlign={s(p,'footerAlign') as UI.SidebarPanelProps['footerAlign']} footer={b(p,'footer')?<><span>Обновлено сегодня</span>{b(p,'actions')&&<UI.FloatingActionBar label="Действия пространства" size="sm" position="static"><UI.IconButton label="Добавить заметку" icon="plus" variant="ghost" onClick={()=>c.notify('Заметка добавлена')}/><UI.IconButton label="Настройки пространства" icon="settings" variant="ghost" onClick={()=>c.notify('Настройки открыты')}/></UI.FloatingActionBar>}</>:undefined}>{b(p,'groups')?<><UI.Accordion title="Рабочее пространство" variant="navigation" open={b(p,'expanded')} onToggle={event=>c.set('expanded',event.currentTarget.open)} expandLabel="Раскрыть рабочее пространство" collapseLabel="Свернуть рабочее пространство">{items}</UI.Accordion><UI.Accordion title="Архив" variant="navigation" expandLabel="Раскрыть архив" collapseLabel="Свернуть архив"><UI.SidebarItem icon="folder" count={0}>Завершённые</UI.SidebarItem></UI.Accordion></>:items}</UI.SidebarPanel>;}),
 ScrollArea: make([option('axis','Направление',['vertical','horizontal','both']),option('scrollbar','Скроллбар',['auto','hidden']),toggle('shadows','Подсказки у краёв',true),number('height','Высота',180,80,360)],p=><UI.ScrollArea label="Прокрутка в песочнице" axis={s(p,'axis') as 'vertical'|'horizontal'|'both'} scrollbar={s(p,'scrollbar') as 'auto'|'hidden'} shadows={b(p,'shadows')} style={{height:n(p,'height'),width:'100%'}}><div style={{width:s(p,'axis')==='vertical'?'auto':900}}>{Array.from({length:12},(_,i)=><p key={i}>Заметка {i+1}. {content}</p>)}</div></UI.ScrollArea>),
 Spinner: make([text('label','Доступная подпись','Загрузка'),number('size','Размер, px',20,12,48)],p=><UI.Spinner label={s(p,'label')} style={{width:n(p,'size'),height:n(p,'size')}}/>),
 Skeleton: make([number('width','Ширина',240,24,600),number('height','Высота',64,16,240),number('radius','Скругление',8,0,40)],p=><UI.Skeleton style={{width:n(p,'width'),maxWidth:'100%',height:n(p,'height'),borderRadius:n(p,'radius')}}/>),
 Progress: make([number('value','Прогресс',64),text('label','Подпись','Подготовка')],p=><UI.Progress value={n(p,'value')} label={s(p,'label')}/>),
 Callout: make([color,icon,label,toggle('title','Заголовок',true)],(p,c)=><UI.Callout color={hue(p)} icon={glyph(p,c)} title={b(p,'title')?s(p,'label'):undefined}>{content}</UI.Callout>),
 EmptyState: make([label,icon,toggle('showIcon','Показывать иконку',true),toggle('description','Описание',true),toggle('action','Действие',true)],(p,c)=><UI.EmptyState title={s(p,'label')} icon={b(p,'showIcon')?glyph(p,c):false} description={b(p,'description')?content:undefined} action={b(p,'action')?<UI.Button leading={<UI.Icon name="plus"/>} onClick={event(c,'Объект создан')}>Создать</UI.Button>:undefined}/>),
 Toast: make([label,...feedbackControls,toggle('description','Описание',true),toggle('dismiss','Закрытие',true)],(p,c)=>b(p,'hidden')?<UI.Button onClick={()=>c.set('hidden',false)}>Показать снова</UI.Button>:<UI.Toast {...feedbackProps(p)} title={s(p,'label')} description={b(p,'description')?content:undefined} onDismiss={b(p,'dismiss')?()=>c.set('hidden',true):undefined}/>),
 StatusBar: make([label,...feedbackControls,option('variant','Стиль',['plain','surface']),toggle('busy','Загрузка'),toggle('leading','Иконка слева',true),toggle('trailing','Счётчик справа')],p=><UI.StatusBar {...feedbackProps(p)} variant={s(p,'variant') as 'plain'|'surface'} busy={b(p,'busy')} leading={b(p,'leading')?<UI.Icon name="check"/>:undefined} trailing={b(p,'trailing')?<UI.Counter value="99+" size="xs"/>:undefined}>{s(p,'label')}</UI.StatusBar>),
 Alert: make([label,...feedbackControls,toggle('expandable','Раскрытие',true),toggle('expanded','Раскрыт',true),toggle('dismiss','Закрытие')],(p,c)=>b(p,'hidden')?<UI.Button onClick={()=>c.set('hidden',false)}>Показать снова</UI.Button>:<UI.Alert {...feedbackProps(p)} title={s(p,'label')} expandable={b(p,'expandable')} expanded={b(p,'expanded')} onExpandedChange={v=>c.set('expanded',v)} onDismiss={b(p,'dismiss')?()=>c.set('hidden',true):undefined}>{content}</UI.Alert>),
 Dialog: make(modalControls,(p,c)=><><UI.Button onClick={()=>c.set('open',true)}>Открыть диалог</UI.Button><UI.Dialog {...modalProps(p,c)}>{modalContent}</UI.Dialog></>),
 Drawer: make([...modalControls,option('side','Сторона',['right','left','bottom']),option('variant','Стиль',['inset','edge'])],(p,c)=><><UI.Button onClick={()=>c.set('open',true)}>Открыть панель</UI.Button><UI.Drawer {...modalProps(p,c)} side={s(p,'side') as 'right'|'left'|'bottom'} variant={s(p,'variant') as 'inset'|'edge'}>{modalContent}</UI.Drawer></>),
 Tooltip: make([text('label','Текст','Создать заметку'),text('caption','Лейбл',''),text('description','Подпись',''),option('variant','Стиль',['default','inverse']),toggle('arrow','Язычок'),option('side','Сторона',['top','bottom']),option('align','Привязка',['start','center','end'],'center'),toggle('shortcut','Клавиши',true),size],p=><UI.Tooltip content={s(p,'label')} caption={s(p,'caption')||undefined} description={s(p,'description')||undefined} variant={s(p,'variant') as UI.TooltipProps['variant']} arrow={b(p,'arrow')} side={s(p,'side') as 'top'|'bottom'} align={s(p,'align') as 'start'|'center'|'end'} shortcut={b(p,'shortcut')?['⌘','N']:undefined}><UI.IconButton label="Новая заметка" icon="plus" size={sz(p)} variant="ghost"/></UI.Tooltip>),
 Menu: make([size,variant,icon,disabled,toggle('danger','Опасное действие'),toggle('unavailable','Недоступный пункт')],(p,c)=><UI.Menu label="Меню в песочнице" size={sz(p)} variant={buttonStyle(p)} icon={glyph(p,c)} disabled={b(p,'disabled')} items={[...menuItems(c),{id:'delete',label:'Удалить',icon:'trash',separator:true,danger:b(p,'danger'),disabled:b(p,'unavailable'),onSelect:event(c,'Объект удалён')}]}/>),
 Popover: make([size,label,toggle('iconOnly','Кнопка-иконка'),icon,option('side','Сторона',['bottom','top']),option('align','Выравнивание',['start','center','end']),disabled],p=><UI.Popover label={s(p,'label')} triggerIcon={b(p,'iconOnly')?s(p,'icon') as UI.IconName:undefined} size={sz(p)} side={s(p,'side') as 'bottom'|'top'} align={s(p,'align') as 'start'|'center'|'end'} disabled={b(p,'disabled')}><div className="catalog-stack"><p>{content}</p><UI.Tag icon="folder" count="99+">Проект</UI.Tag><UI.Switch label="Уведомления" defaultChecked/></div></UI.Popover>),
 CommandPalette: make([text('placeholder','Placeholder','Найти команду…'),toggle('description','Описания',true),toggle('icons','Иконки',true)],(p,c)=><><UI.Button onClick={()=>c.set('open',true)}>Открыть команды</UI.Button><UI.CommandPalette open={b(p,'open')} onOpenChange={v=>c.set('open',v)} placeholder={s(p,'placeholder')} items={['Новая заметка','Новый проект','Открыть календарь'].map((label,i)=>({id:String(i),label,description:b(p,'description')?'Создание и навигация':undefined,icon:b(p,'icons')?'page':undefined,onSelect:()=>{c.set('open',false);c.notify(label);}}))}/></>),
} satisfies Record<Exclude<ComponentName,ArcComponentName>,Spec>;

export function Playground({name,notify,surface='base'}:{name:ComponentName;notify:(message:string)=>void;surface?:'base'|'canvas'|'raised'|'floating'}) {
 return Object.hasOwn(arcPlaygrounds,name)?<ArcPlayground name={name as ArcComponentName} notify={notify} surface={surface}/>:<BasePlayground name={name as Exclude<ComponentName,ArcComponentName>} notify={notify} surface={surface}/>;
}
function BasePlayground({name,notify,surface}:{name:Exclude<ComponentName,ArcComponentName>;notify:(message:string)=>void;surface:'base'|'canvas'|'raised'|'floating'}) {
 const spec:Spec=playgrounds[name], id=useId();
 const icons=useIconCatalogue(name==='IconPicker'||spec.controls.some(control=>control.key==='icon'&&control.options));
 const initial=()=>Object.fromEntries(spec.controls.map(c=>[c.key,c.initial]));
 const [values,setValues]=useState<Values>(initial),[revision,setRevision]=useState(0);
 const set=(key:string,value:Value)=>setValues(previous=>({...previous,[key]:value}));
 return <section className="catalog-playground cap-surface-boundary" data-surface="canvas" data-component={name} aria-labelledby={`${id}-title`}>
  <div className="playground-layout">
   <div className="playground-preview" data-surface={surface} role="group" aria-label={`${name}: интерактивный пример`} key={revision}><h2 className="cap-sr-only">Интерактивный пример</h2>{spec.render(values,{set,notify,id,icons})}</div>
   <div className="playground-settings" data-surface="raised">
    <header><h2 id={`${id}-title`}>Параметры</h2><UI.Button variant="ghost" size="sm" onClick={()=>{setValues(initial());setRevision(r=>r+1);}}>Сбросить</UI.Button></header>
    <div className="playground-controls" role="group" aria-label={`Параметры ${name}`}>
     <ControlList controls={spec.controls} render={control=>{
      if(typeof control.initial==='boolean')return <UI.Checkbox key={control.key} label={control.label} size="sm" checked={b(values,control.key)} onChange={e=>set(control.key,e.target.checked)}/>;
      if(typeof control.initial==='number')return <UI.NumberField key={control.key} label={control.label} compact size="sm" value={Number(values[control.key])} min={control.min} max={control.max} step={!Number.isInteger(control.initial)?.05:1} onValueChange={value=>set(control.key,value)}/>;
      if(control.label==='Дата ISO'||control.key==='rangeEnd')return <UI.DatePicker key={control.key} label={control.label} value={s(values,control.key)} onValueChange={value=>set(control.key,value)}/>;
      return <UI.Field key={control.key} label={control.label}>{props=>control.key==='icon'&&control.options?<UI.IconPicker {...props} label={control.label} size="sm" variant="combobox" value={s(values,control.key)} options={icons} onValueChange={value=>set(control.key,value)}/>:control.options?<UI.Select {...props} size="sm" value={s(values,control.key)} options={control.options.map(value=>({value,label:value}))} onValueChange={value=>set(control.key,value)}/>:<UI.Input {...props} size="sm" value={s(values,control.key)} onChange={e=>set(control.key,e.target.value)}/>}</UI.Field>;
     }}/>
    </div>
   </div>
  </div>
 </section>;
}
