import { ControlList } from './ControlList';
import { useId, useState, type ReactNode } from 'react';
import { Button, Checkbox, Input, Select, Tag, colors, type Color } from '../src';
import * as Navigation from '../src/components/navigation-menu';
import * as Tree from '../src/components/tree-view';
import * as Selection from '../src/components/selection';
import * as Scrubber from '../src/components/value-scrubber';
import * as Editor from '../src/components/rich-text-editor';
import * as Data from '../src/components/data-table';
import * as Messages from '../src/components/messages';
import * as Comments from '../src/components/comments';
import * as Charts from '../src/components/charts';
import type { ArcComponentName } from './catalog-arc';

type Value = string | number | boolean;
type Values = Record<string, Value>;
type Control = { key: string; label: string; initial: Value; options?: readonly string[]; min?: number; max?: number; step?: number };
type Context = { set: (key: string, value: Value) => void; notify: (message: string) => void };
type Spec = { controls: Control[]; render: (values: Values, context: Context) => ReactNode };
const text = (key: string, label: string, initial: string): Control => ({ key, label, initial });
const toggle = (key: string, label: string, initial = false): Control => ({ key, label, initial });
const number = (key: string, label: string, initial: number, min = 0, max = 100, step = 1): Control => ({ key, label, initial, min, max, step });
const option = (key: string, label: string, options: readonly string[], initial = options[0]): Control => ({ key, label, options, initial });
const make = (controls: Control[], render: Spec['render']): Spec => ({ controls, render });
const s = (p: Values, key: string) => String(p[key] ?? '');
const n = (p: Values, key: string) => Number(p[key] ?? 0);
const b = (p: Values, key: string) => p[key] === true;
const size = option('size', 'Размер', ['xs','sm','md','lg','xl'], 'md');
const disabled = toggle('disabled','Недоступен');
const fieldVariant = option('fieldVariant','Подложка',['surface','ghost']);
const focusControls = [number('focusWidth','Толщина',1,1,4),number('focusOffset','Отступ',1,0,4)];
const focusRing = (p: Values) => ({width:n(p,'focusWidth'),offset:n(p,'focusOffset')});
const sampleOptions: Selection.SelectionOption[] = [
  { value: 'project', label: 'Проект', icon: 'folder', aliases: ['workspace'] },
  { value: 'note', label: 'Заметка', icon: 'page' },
  { value: 'book', label: 'Книга', icon: 'book' },
  { value: 'task', label: 'Задача', icon: 'check' },
];
const sampleTree: Tree.TreeNode[] = [{ id: 'projects', label: 'Проекты', icon: 'folder', children: [{ id: 'garden', label: 'Сад идей', icon: 'page' }, { id: 'archive', label: 'Архив', icon: 'page' }] }, { id: 'notes', label: 'Заметки', icon: 'book', children: [{ id: 'today', label: 'Сегодня' }, { id: 'drafts', label: 'Черновики' }] }];
const sampleRows = [{ id: 'garden', name: 'Сад идей', score: 92, status: 'В работе' }, { id: 'archive', name: 'Архив', score: 64, status: 'Черновик' }, { id: 'notes', name: 'Заметки', score: 81, status: 'В работе' }, { id: 'library', name: 'Библиотека', score: null, status: 'Готово' }];
const sampleColumns: Data.DataTableColumn<typeof sampleRows[number]>[] = [{ id: 'name', header: 'Название', value: row => row.name }, { id: 'score', header: 'Оценка', value: row => row.score, numeric: true }, { id: 'status', header: 'Статус', value: row => row.status, cell: row => <Tag interactive={false} size="xs">{row.status}</Tag> }];
const fields: Data.FilterField[] = [{ id: 'status', label: 'Статус', options: [{ value: 'active', label: 'В работе' }, { value: 'draft', label: 'Черновик' }, { value: 'done', label: 'Готово' }] }, { id: 'type', label: 'Тип', options: [{ value: 'project', label: 'Проект' }, { value: 'note', label: 'Заметка' }] }];
const me: Comments.CommentAuthor = { id: 'me', name: 'Вы' }, reviewer: Comments.CommentAuthor = { id: 'reviewer', name: 'Анна' };
const comments: Comments.ThreadComment[] = [{ id: 'one', author: reviewer, body: 'Давайте уточним заголовок.', createdAt: 'Сегодня' }];
const days = ['Пн','Вт','Ср','Чт','Пт','Сб','Вс'];
const chartSeries = (scale: number): Charts.ChartSeries[] => [{ name: 'Заметки', values: [3,5,4,8,6,9,7].map(value=>value*scale) }, { name: 'Задачи', values: [5,3,7,4,8,6,10].map(value=>value*scale) }];
const chartData = (scale: number): Charts.ChartDatum[] => [{label:'Дизайн',value:42*scale},{label:'Исследование',value:30*scale},{label:'Планирование',value:18*scale},{label:'Другое',value:10*scale}];
const chartControls = (title: string) => [text('label','Подпись',title),number('height','Высота',240,140,420,10),number('scale','Масштаб данных',1,.2,3,.2)];
const chartSpec = (title: string, render: Spec['render']): Spec => make(chartControls(title), render);

function RichTextPreview({ p }: { p: Values }) {
  const [value, setValue] = useState<Editor.RichTextDocument>(() => ({ blocks: [Editor.createRichTextBlock('heading2', [{ text: 'Новая заметка' }]), Editor.createRichTextBlock('paragraph', [{ text: 'Выделите текст или начните блок с /.' }]), Editor.createRichTextBlock('paragraph', [{ text: 'Перетащите за ручку слева или нажмите для меню блока.' }])] }));
  const presets: Editor.RichTextPreset[] = [{ type: 'callout', label: 'Врезка', icon: 'info', keywords: ['note'], create: () => ({ data: { text: 'Важная мысль' } }), render: ({ block }) => <div data-accent={s(p,'blockColor')} className="cap-surface-boundary" style={{ display: 'flex', gap: 8, alignItems: 'center', flexWrap: 'wrap', padding: 12, background: 'var(--cap-accent-normal)', color: 'var(--cap-accent-text)', borderRadius: 'var(--cap-radius-md)' }}><span>{(block.data as { text: string })?.text}</span><Tag color="neutral" interactive={false} size="xs">Заметка</Tag></div> }];
  return <Editor.RichTextEditor label={s(p,'label')} value={value} onValueChange={setValue} presets={b(p,'preset')?presets:[]} placeholder={s(p,'placeholder')} toolbarSize={s(p,'toolbarSize') as Editor.RichTextEditorProps['toolbarSize']} disabled={b(p,'disabled')} readOnly={b(p,'readOnly')}/>;
}
function ToastPreview({ p, context }: { p: Values; context:Context }) {
  const [items, setItems] = useState<Messages.ToastStackItem[]>([{ id: 'save', title: 'Изменения сохранены', description: 'Документ готов к просмотру.' }, { id: 'archive', title: 'Объект архивирован', action: { label: 'Отменить', onAction: () => setItems(current => current.filter(item => item.id !== 'archive')) } }]);
  return <div style={{ display: 'grid', gap: 12 }}><Messages.ToastStack position="inline" label="Уведомления" limit={n(p,'limit')} expandDirection={s(p,'expandDirection') as Messages.StackDirection} expanded={b(p,'expanded')} onExpandedChange={value=>context.set('expanded',value)} items={items.map(item=>({...item,tone:s(p,'tone') as 'neutral'|'info'|'success'|'warning'|'danger',appearance:s(p,'appearance') as 'neutral'|'soft'|'solid',color:s(p,'statusColor')==='auto'?undefined:s(p,'statusColor') as Color|'inherit',contrast:b(p,'contrast')}))} onDismiss={id=>setItems(current=>current.filter(item=>item.id!==id))}/><Button size="sm" onClick={()=>setItems(current=>[...current,{id:crypto.randomUUID(),title:s(p,'title'),description:'Новое уведомление'}])}>Добавить уведомление</Button></div>;
}
function InlinePreview({ p, c }: { p: Values; c: Context }) {
  const [anchors, setAnchors] = useState<Comments.InlineCommentAnchor[]>([{ id: 'pin', x: .38, y: .36, title: 'Обложка', comments: [{ id: 'comment', author: reviewer, body: 'Проверим композицию на телефоне.', createdAt: 'Сегодня' }] }]);
  return <Comments.InlineComments currentUser={me} people={[reviewer]} anchors={anchors} onAnchorsChange={setAnchors} commentMode={b(p,'commentMode')} onCommentModeChange={value=>c.set('commentMode',value)}><div style={{ minHeight: 220, padding: 24, background: 'var(--cap-control-bg)', borderRadius: 'var(--cap-radius-md)' }}><h3>{s(p,'title')}</h3><p>Выберите маркер или включите режим комментариев.</p></div></Comments.InlineComments>;
}

export const arcPlaygrounds: Record<ArcComponentName, Spec> = {
  TreeView: make([size, option('selected','Выбранный узел',['garden','archive','today']), toggle('expandProjects','Раскрыть проекты',true),toggle('showGuides','Линии дерева',true)],(p,c)=><Tree.TreeView key={String(b(p,'expandProjects'))} label="Дерево в песочнице" nodes={sampleTree} showGuides={b(p,'showGuides')} size={s(p,'size') as 'xs'|'sm'|'md'|'lg'|'xl'} selectedId={s(p,'selected')} defaultExpandedIds={b(p,'expandProjects')?['projects']:[]} onSelect={node=>c.set('selected',node.id)}/>),
  NavigationMenu: make([size,option('active','Активный раздел',['projects','notes']),toggle('trailing','Счётчик справа',true)],(p,c)=><Navigation.NavigationMenu label="Навигация в песочнице" size={s(p,'size') as 'xs'|'sm'|'md'|'lg'|'xl'} activeId={s(p,'active')} trailing={b(p,'trailing')?<Tag interactive={false} size="xs" count={4}>Новые</Tag>:undefined} items={[{id:'projects',label:'Проекты',content:<div style={{display:'grid',gap:8}}><a href="#TreeView">Сад идей</a><a href="#DataTable">Все проекты</a></div>},{id:'notes',label:'Заметки',content:<a href="#RichTextEditor">Открыть редактор</a>},{id:'calendar',label:'Календарь',href:'#Calendar',onSelect:()=>c.notify('Открыт календарь')}]}/>),
  HoverPanel: make([size,text('summary','Кнопка','Сад идей'),toggle('open','Предпросмотр открыт')],(p,c)=><Navigation.HoverPanel label="Предпросмотр проекта" summary={s(p,'summary')} size={s(p,'size') as 'xs'|'sm'|'md'|'lg'|'xl'} open={b(p,'open')} onOpenChange={value=>c.set('open',value)}><div style={{display:'grid',gap:8}}><strong>Сад идей</strong><span>12 заметок · обновлено сегодня</span><Button size="sm" onClick={()=>c.set('open',false)}>Закрыть</Button></div></Navigation.HoverPanel>),
  ComboBox: make([size,...focusControls,fieldVariant,toggle('clearable','Очистка',true),text('description','Описание','Выберите тип или начните вводить название.'),text('label','Подпись','Тип объекта'),text('placeholder','Placeholder','Найти тип…'),option('value','Значение',['','project','note','book','task'],'project'),disabled],(p,c)=><Selection.ComboBox clearable={b(p,'clearable')} variant={s(p,'fieldVariant') as Selection.FieldVariant} description={s(p,'description')} focusRing={focusRing(p)} label={s(p,'label')} placeholder={s(p,'placeholder')} options={sampleOptions} value={s(p,'value')} onValueChange={value=>c.set('value',value)} size={s(p,'size') as 'xs'|'sm'|'md'|'lg'|'xl'} disabled={b(p,'disabled')}/>),
  MultiSelect: make([toggle('grouped','Группы',true),toggle('colorDots','Цветные точки',true),size,...focusControls,fieldVariant,text('values','Выбранные значения','project,note'),text('description','Описание','Можно выбрать несколько значений.'),text('label','Подпись','Типы объектов'),number('maxVisible','Показать меток',2,1,4),disabled],(p,c)=><Selection.MultiSelect variant={s(p,'fieldVariant') as Selection.FieldVariant} description={s(p,'description')} focusRing={focusRing(p)} label={s(p,'label')} options={sampleOptions.map((option,index)=>({...option,group:b(p,'grouped')?(index<3?'Объекты':'Действия'):undefined,color:b(p,'colorDots')?(['blue','purple','green','orange'] as const)[index]:undefined,icon:b(p,'colorDots')?undefined:option.icon}))} value={s(p,'values').split(',').filter(Boolean)} onValueChange={value=>c.set('values',value.join(','))} maxVisible={n(p,'maxVisible')} size={s(p,'size') as 'xs'|'sm'|'md'|'lg'|'xl'} disabled={b(p,'disabled')}/>),
  TagInput: make([size,...focusControls,fieldVariant,text('values','Метки','Дизайн,Исследование'),text('description','Описание','Enter добавляет метку, стрелки выбирают её.'),text('label','Подпись','Ключевые слова'),text('placeholder','Placeholder','Добавить метку…'),number('maxTags','Предел меток',5,1,12),disabled],(p,c)=><Selection.TagInput variant={s(p,'fieldVariant') as Selection.FieldVariant} description={s(p,'description')} focusRing={focusRing(p)} label={s(p,'label')} placeholder={s(p,'placeholder')} value={s(p,'values').split(',').filter(Boolean)} onValueChange={value=>c.set('values',value.join(','))} maxTags={n(p,'maxTags')} size={s(p,'size') as 'xs'|'sm'|'md'|'lg'|'xl'} disabled={b(p,'disabled')}/>),
  RadioGroup: make([size,...focusControls,text('label','Подпись','Режим просмотра'),option('variant','Стиль',['plain','cards'],'cards'),option('layout','Композиция',['list','grid']),option('orientation','Направление',['vertical','horizontal']),disabled],(p,c)=><Selection.RadioGroup layout={s(p,'layout') as 'list'|'grid'} focusRing={focusRing(p)} label={s(p,'label')} options={[{value:'grid',label:'Карточки',description:'Визуальный обзор'},{value:'list',label:'Список',description:'Плотная таблица'}]} value={s(p,'value')||'grid'} onValueChange={value=>c.set('value',value)} variant={s(p,'variant') as 'plain'|'cards'} orientation={s(p,'orientation') as 'horizontal'|'vertical'} size={s(p,'size') as 'xs'|'sm'|'md'|'lg'|'xl'} disabled={b(p,'disabled')}/>),
  ColorPicker: make([size,...focusControls,text('label','Подпись','Цвет проекта'),text('value','Цвет','#3E63DD'),option('format','Формат',['hex','rgb','hsl','oklch']),toggle('recent','Последние цвета'),disabled],(p,c)=><Selection.ColorPicker showRecent={b(p,'recent')} focusRing={focusRing(p)} label={s(p,'label')} value={s(p,'value')} onValueChange={value=>c.set('value',value)} format={s(p,'format') as Selection.ColorFormat} size={s(p,'size') as 'xs'|'sm'|'md'|'lg'|'xl'} disabled={b(p,'disabled')}/>),
  NumberField: make([size,...focusControls,text('label','Подпись','Лимит задач'),number('value','Значение',12,0,100),number('step','Шаг',1,1,10),number('largeStep','Большой шаг',10,1,50),text('prefix','Префикс',''),toggle('readOnly','Только чтение'),toggle('compact','Компактный вид'),toggle('scrubbable','Alt-перетаскивание',true),disabled],(p,c)=><Selection.NumberField largeStep={n(p,'largeStep')} prefix={s(p,'prefix')} readOnly={b(p,'readOnly')} focusRing={focusRing(p)} label={s(p,'label')} value={n(p,'value')} onValueChange={value=>c.set('value',value)} min={0} max={100} step={n(p,'step')} compact={b(p,'compact')} scrubbable={b(p,'scrubbable')} suffix="шт." size={s(p,'size') as 'xs'|'sm'|'md'|'lg'|'xl'} disabled={b(p,'disabled')}/>),
  ValueScrubber: make([text('label','Подпись','Масштаб просмотра'),number('value','Значение',100,0,200,1),number('min','Минимум',50,0,150,1),number('max','Максимум',200,100,500,1),number('step','Шаг',10,.1,50,.1),option('orientation','Направление',['horizontal','vertical']),toggle('percent','Показывать процент',true),disabled],(p,c)=><Scrubber.ValueScrubber label={s(p,'label')} value={n(p,'value')} onValueChange={value=>c.set('value',value)} min={n(p,'min')} max={n(p,'max')} step={n(p,'step')} orientation={s(p,'orientation') as 'horizontal'|'vertical'} disabled={b(p,'disabled')} formatValue={b(p,'percent')?value=>`${value}%`:undefined}/>),
  RichTextEditor: make([text('label','Подпись','Заметка'),text('placeholder','Placeholder','Начните писать или введите /'),option('toolbarSize','Размер панели',['xs','sm','md','lg','xl'],'sm'),toggle('preset','Пользовательский блок',true),option('blockColor','Цвет врезки',['blue','purple','amber','neutral'],'blue'),toggle('readOnly','Только чтение'),disabled],p=><RichTextPreview p={p}/>),
  DataTable: make([text('label','Подпись','Проекты'),number('pageSize','Строк на странице',2,1,4),toggle('selectable','Выбор строк',true),toggle('empty','Пустые данные')],(p,c)=><Data.DataTable label={s(p,'label')} rows={b(p,'empty')?[]:sampleRows} columns={sampleColumns} rowId={row=>row.id} selectable={b(p,'selectable')} selectedIds={s(p,'selected').split(',').filter(Boolean)} onSelectedIdsChange={ids=>c.set('selected',ids.join(','))} pageSize={n(p,'pageSize')}/>),
  FilterToolbar: make([text('label','Подпись','Фильтры проектов'),text('query','Поиск',''),option('status','Статус',['none','active','draft','done']),option('type','Тип',['none','project','note'])],(p,c)=><Data.FilterToolbar label={s(p,'label')} fields={fields} filters={[s(p,'status')==='none'?null:{fieldId:'status',value:s(p,'status')},s(p,'type')==='none'?null:{fieldId:'type',value:s(p,'type')}].filter((item):item is Data.ActiveFilter=>!!item)} onFiltersChange={items=>{c.set('status',items.find(item=>item.fieldId==='status')?.value??'none');c.set('type',items.find(item=>item.fieldId==='type')?.value??'none');}} query={s(p,'query')} onQueryChange={value=>c.set('query',value)}/>),
  JsonViewer: make([text('label','Подпись','Данные проекта'),number('pageSize','Узлов за раз',2,1,8),number('maxHeight','Высота',260,120,500),number('depth','Уровней раскрыто',1,0,5),toggle('searchable','Поиск по дереву',true),toggle('copyable','Копирование',true),toggle('showPath','Путь выбранного узла',true),text('query','Поиск','')],(p,c)=><Data.JsonViewer key={n(p,'depth')} defaultExpandDepth={n(p,'depth')} searchable={b(p,'searchable')} copyable={b(p,'copyable')} showPath={b(p,'showPath')} label={s(p,'label')} data={{project:'Сад идей',owner:{name:'Анна',team:'Дизайн'},tags:['идея','заметка','исследование','каталог'],published:false,extra:null}} pageSize={n(p,'pageSize')} maxHeight={n(p,'maxHeight')} query={s(p,'query')} onQueryChange={value=>c.set('query',value)}/>),
  ToastStack: make([option('expandDirection','Направление раскрытия',['up','down','left','right'],'down'),toggle('expanded','Раскрыт'),option('tone','Статус',['neutral','info','success','warning','danger'],'success'),option('appearance','Заливка',['neutral','soft','solid']),option('statusColor','Цвет статуса',['auto','inherit',...colors]),toggle('contrast','Усилить контраст'),text('title','Новое уведомление','Новая заметка'),number('limit','Видимых',3,1,5)],(p,c)=><ToastPreview p={p} context={c}/>),
  AnnouncementBar: make([text('message','Сообщение','Обновление рабочего пространства готово'),toggle('controls','Переключение',true),toggle('dismissible','Закрытие',true),toggle('open','Открыта',true)],(p,c)=><Messages.AnnouncementBar label="Настраиваемое объявление" messages={[{id:'release',message:s(p,'message'),action:{label:'Открыть',onClick:()=>c.notify('Открыты подробности')}},{id:'second',message:'Новые возможности редактора'}]} open={b(p,'open')} onOpenChange={value=>c.set('open',value)} controls={b(p,'controls')} dismissible={b(p,'dismissible')} autoPlay={false}/>),
  CardStack: make([option('expandDirection','Направление раскрытия',['up','down','left','right'],'down'),toggle('expanded','Раскрыт'),toggle('review','Разбор карточек',true),number('count','Карточки',3,0,5),number('activeIndex','Активная',0,0,4)],(p,c)=><Messages.CardStack expandDirection={s(p,'expandDirection') as Messages.StackDirection} expanded={b(p,'expanded')} onExpandedChange={value=>c.set('expanded',value)} label="Карточки для разбора" review={b(p,'review')} labels={{left:'Пропустить',right:'Сохранить'}} getKey={item=>String(item.id)} items={Array.from({length:n(p,'count')},(_,i)=>({id:i,title:`Идея ${i+1}`,body:'Следующий шаг для проекта.'}))} activeIndex={b(p,'review')?undefined:Math.min(n(p,'activeIndex'),Math.max(0,n(p,'count')-1))} onActiveIndexChange={value=>c.set('activeIndex',value)} getLabel={item=>item.title} renderCard={item=><article style={{padding:20,background:'var(--cap-surface-current)',borderRadius:'var(--cap-radius-md)'}}><h3>{item.title}</h3><p>{item.body}</p></article>} renderEmpty={reset=><div className="catalog-stack"><p>Все карточки разобраны.</p><Button size="sm" onClick={reset}>Начать заново</Button></div>}/>),
  TextShimmer: make([text('value','Текст','Собираем связанные заметки…'),toggle('active','В работе',true),number('duration','Длительность, с',1.8,.4,5,.2),option('as','Элемент',['span','p','h3'],'p')],p=><Messages.TextShimmer active={b(p,'active')} duration={n(p,'duration')} as={s(p,'as') as 'span'|'p'|'h3'}>{s(p,'value')}</Messages.TextShimmer>),
  CommentThread: make([text('title','Заголовок','Обсуждение страницы'),text('placeholder','Placeholder','Написать комментарий…'),toggle('resolved','Решено')],(p,c)=><Comments.CommentThread currentUser={me} people={[reviewer]} defaultComments={comments} title={s(p,'title')} placeholder={s(p,'placeholder')} resolved={b(p,'resolved')} onResolvedChange={value=>c.set('resolved',value)}/>),
  InlineComments: make([text('title','Заголовок','Обзор проекта'),toggle('commentMode','Режим комментариев')],(p,c)=><InlinePreview p={p} c={c}/>),
  LineChart: make([...chartControls('Активность по дням'),toggle('area','Заливка'),toggle('dashed','Пунктир'),toggle('loading','Загрузка'),toggle('empty','Пустые данные')],(p,c)=><Charts.LineChart area={b(p,'area')} dashed={b(p,'dashed')} loading={b(p,'loading')} label={s(p,'label')} labels={days} series={b(p,'empty')?[]:chartSeries(n(p,'scale'))} height={n(p,'height')} onPointSelect={(series,index)=>c.notify(`${series}: ${days[index]}`)}/>),
  BarChart: make([...chartControls('Задачи по дням'),toggle('showAverage','Среднее значение',true)],(p,c)=><Charts.BarChart showAverage={b(p,'showAverage')} averageLabel="Среднее" label={s(p,'label')} data={days.map((label,index)=>({label,value:[4,7,-2,10,8,3,11][index]*n(p,'scale')}))} height={n(p,'height')} onSelect={datum=>c.notify(`${datum.label}: ${datum.value}`)}/>),
  DonutChart: make([...chartControls('Распределение работы'),text('totalLabel','Подпись центра','Всего'),toggle('legend','Легенда',true),option('legendAction','Действие легенды',['select','toggle'])],(p,c)=><Charts.DonutChart legend={b(p,'legend')} legendAction={s(p,'legendAction') as 'select'|'toggle'} label={s(p,'label')} data={chartData(n(p,'scale'))} totalLabel={s(p,'totalLabel')} height={n(p,'height')} onSelect={datum=>c.notify(datum.label)}/>),
  Streamgraph: make([...chartControls('Состав работы'),option('offset','Базовая линия',['wiggle','silhouette','zero']),toggle('legend','Легенда',true),toggle('directLabels','Подписи слоёв',true)],(p,c)=><Charts.Streamgraph offset={s(p,'offset') as 'wiggle'|'silhouette'|'zero'} legend={b(p,'legend')} directLabels={b(p,'directLabels')} label={s(p,'label')} labels={days} series={chartSeries(n(p,'scale'))} height={n(p,'height')} onLayerSelect={name=>c.notify(name)}/>),
  BrushChart: make([text('label','Подпись','Активность за месяц'),number('height','Высота',260,160,420,10),number('points','Точек',30,8,60,1),toggle('events','События',true)],(p,c)=><Charts.BrushChart annotations={b(p,'events')?[{index:5,label:'Запуск проекта'},{index:15,label:'Обзор'}]:[]} formatRange={(start,end)=>`${start} — ${end}`} label={s(p,'label')} labels={Array.from({length:n(p,'points')},(_,i)=>`День ${i+1}`)} series={[{name:'Активность',values:Array.from({length:n(p,'points')},(_,i)=>Math.round(8+6*Math.sin(i/3)+i%4))}]} height={n(p,'height')} onRangeChange={range=>c.notify(`Диапазон ${range[0]+1}–${range[1]+1}`)}/>),
  WaffleChart: make([text('label','Подпись','Распределение времени'),number('columns','Колонок',10,2,20,1),number('rows','Строк',10,2,20,1),number('decimals','Знаков процента',0,0,2),number('share','Доля дизайна',42,5,90,1)],(p,c)=><Charts.WaffleChart rows={n(p,'rows')} decimals={n(p,'decimals')} label={s(p,'label')} columns={n(p,'columns')} data={[{label:'Дизайн',value:n(p,'share')},{label:'Остальное',value:100-n(p,'share')}]} onSelect={datum=>c.notify(datum.label)}/>),
  SlopeChart: make([...chartControls('Изменение за квартал'),text('beforeLabel','Раньше','Q1'),text('afterLabel','Сейчас','Q2'),toggle('ranks','Места в рейтинге',true)],(p,c)=><Charts.SlopeChart ranks={b(p,'ranks')} label={s(p,'label')} beforeLabel={s(p,'beforeLabel')} afterLabel={s(p,'afterLabel')} height={n(p,'height')} data={[{label:'Заметки',before:8*n(p,'scale'),after:12*n(p,'scale')},{label:'Задачи',before:14*n(p,'scale'),after:9*n(p,'scale')},{label:'Проекты',before:4*n(p,'scale'),after:7*n(p,'scale')}]} onSelect={datum=>c.notify(datum.label)}/>),
  Sparkline: make([text('label','Подпись','Новые заметки'),number('width','Ширина',180,80,420,10),number('height','Высота',48,24,140,4),number('trend','Наклон',1,-2,3,.2),toggle('interactive','Чтение значений',true),toggle('area','Область под линией',true)],p=><Charts.Sparkline interactive={b(p,'interactive')} area={b(p,'area')} label={s(p,'label')} width={n(p,'width')} height={n(p,'height')} values={[2,3,3,5,4,7,8].map((value,index)=>value+index*n(p,'trend'))}/>),
  Gauge: make([text('label','Подпись','Недельная цель'),option('tone','Семантика',['accent','success','warning','danger']),text('detail','Описание','Выполнено за неделю'),number('value','Значение',68,0,100,1),number('max','Максимум',100,10,200,10),number('height','Высота',210,140,320,10)],(p,c)=><Charts.Gauge tone={s(p,'tone') as Charts.GaugeTone} detail={s(p,'detail')} label={s(p,'label')} value={n(p,'value')} max={n(p,'max')} valueLabel="%" height={n(p,'height')} onValueChange={value=>c.set('value',value)}/>),
  ActivityHeatmap: make([text('label','Подпись','Активность по дням'),number('year','Год',2026,2020,2035,1),number('density','Частота',3,1,10,1),option('weekStart','Начало недели',['Понедельник','Воскресенье']),toggle('quarter','Только первый квартал')],(p,c)=><Charts.ActivityHeatmap dateRange={b(p,'quarter')?[`${n(p,'year')}-01-01`,`${n(p,'year')}-03-31`]:undefined} weekStart={s(p,'weekStart')==='Воскресенье'?0:1} label={s(p,'label')} year={n(p,'year')} data={Array.from({length:365},(_,i)=>{const date=new Date(n(p,'year'),0,i+1);return {date:`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`,value:(i*n(p,'density'))%11};})} onSelect={datum=>c.notify(`${datum.date}: ${datum.value}`)}/>),
  AnimatedCounter: make([text('label','Подпись','Сохранено заметок'),number('value','Значение',1248,0,100000,1),toggle('animate','Анимация',true),number('decimals','Дробная часть',0,0,3),text('prefix','Префикс',''),text('suffix','Суффикс','')],(p,c)=><div style={{display:'flex',alignItems:'center',gap:14}}><Charts.AnimatedCounter decimals={n(p,'decimals')} prefix={s(p,'prefix')} suffix={s(p,'suffix')} label={s(p,'label')} value={n(p,'value')} animate={b(p,'animate')}/><Button size="sm" onClick={()=>c.set('value',n(p,'value')+17)}>Добавить 17</Button></div>),
  Ridgeline: make([...chartControls('Нагрузка по дням'),number('overlap','Перекрытие',.7,.1,1,.1),number('bandwidth','Сглаживание',1,.2,3,.2),toggle('tint','Заливка',true)],(p,c)=><Charts.Ridgeline overlap={n(p,'overlap')} bandwidth={n(p,'bandwidth')} tint={b(p,'tint')} label={s(p,'label')} labels={days} series={chartSeries(n(p,'scale'))} height={n(p,'height')} onLayerSelect={name=>c.notify(name)}/>),
  Treemap: chartSpec('Место проектов',(p,c)=><Charts.Treemap label={s(p,'label')} height={n(p,'height')} data={[{label:'Работа',value:0,children:[{label:'Дизайн',value:42*n(p,'scale')},{label:'Исследование',value:28*n(p,'scale')}]},{label:'Личное',value:0,children:[{label:'Дневник',value:18*n(p,'scale')},{label:'Книги',value:12*n(p,'scale')}]}]} onSelect={datum=>c.notify(datum.label)}/>),
};

/** Separate typed Playground coverage for every Arc-inspired component. */
export function ArcPlayground({ name, notify, surface = 'base' }: { name: ArcComponentName; notify: (message: string) => void; surface?: 'base' | 'canvas' | 'raised' | 'floating' }) {
  const spec = arcPlaygrounds[name], id = useId();
  const initial = () => Object.fromEntries(spec.controls.map(control => [control.key, control.initial])) as Values;
  const [values, setValues] = useState<Values>(initial), [revision, setRevision] = useState(0);
  const set = (key: string, value: Value) => setValues(previous => ({ ...previous, [key]: value }));
  return <section className="catalog-playground cap-surface-boundary" data-surface="canvas" data-component={name} aria-labelledby={`${id}-arc-title`}>
    <div className="playground-layout">
      <div className="playground-preview" data-surface={surface} role="group" aria-label={`${name}: интерактивный пример`} key={revision}><h2 className="cap-sr-only">Интерактивный пример</h2>{spec.render(values, { set, notify })}</div>
      <div className="playground-settings" data-surface="raised">
        <header><h2 id={`${id}-arc-title`}>Параметры</h2><Button variant="ghost" size="sm" onClick={() => { setValues(initial()); setRevision(value => value + 1); }}>Сбросить</Button></header>
        <div className="playground-controls" role="group" aria-label={`Параметры ${name}`}>
          <ControlList controls={spec.controls} render={control => typeof control.initial === 'boolean'
            ? <Checkbox key={control.key} label={control.label} size="sm" checked={b(values,control.key)} onChange={event=>set(control.key,event.target.checked)}/>
            : control.options
              ? <Select key={control.key} label={control.label} size="sm" value={s(values,control.key)} options={control.options.map(value=>({value,label:value||'Не выбрано'}))} onValueChange={value=>set(control.key,value)}/>
              : typeof control.initial === 'number'
                ? <Selection.NumberField key={control.key} label={control.label} size="sm" compact scrubbable value={n(values,control.key)} min={control.min} max={control.max} step={control.step} onValueChange={value=>set(control.key,value)}/>
                : <Input key={control.key} label={control.label} size="sm" value={s(values,control.key)} onChange={event=>set(control.key,event.target.value)}/>
          }/>
        </div>
      </div>
    </div>
  </section>;
}
