import { ResizableExample } from './ResizableExample';
import { useCatalogText, localizeCatalogueFixture } from './catalog-locale';
import { ControlList } from './ControlList';
import { ArcPlayground, arcPlaygrounds } from './PlaygroundArc';
import type { ArcComponentName } from './catalog-arc';
import { useId, useState, type ReactNode } from 'react';
import * as UI from '../src';
import { useIconCatalogue } from './useIconCatalogue';
import { CardComposer, ReorderExample } from './CardComposer';
import { KanbanPlaygroundExample } from './KanbanPlaygroundExample';
import { scheduleEvents } from '../examples/CalendarSchedule';
import type { ComponentName } from './catalog';
import { revisionFiles,revisionRailItems } from './stories-revision';

type Value = string | number | boolean;
type Values = Record<string, Value>;
type Control = { key: string; label: string; initial: Value; options?: readonly string[]; min?: number; max?: number };
type Context = { t: (text:string)=>string; set: (key: string, value: Value) => void; notify: (message: string) => void; id: string; icons: readonly UI.IconOption[] };
type Spec = { controls: Control[]; render: (p: Values, c: Context) => ReactNode };
const option = (key: string, label: string, options: readonly string[], initial = options[0]): Control => ({key,label,options,initial});
const toggle = (key: string, label: string, initial = false): Control => ({key,label,initial});
const text = (key: string, label: string, initial: string): Control => ({key,label,initial});
const number = (key: string, label: string, initial: number, min = 0, max = 100): Control => ({key,label,initial,min,max});
const size = option('size','Размер',['xs','sm','md','lg','xl'],'md');
const focusControls = [number('focusWidth','Толщина',1,1,4),number('focusOffset','Отступ',1,0,4)];
const focusRing = (p: Values) => ({width:n(p,'focusWidth'),offset:n(p,'focusOffset')});
const fieldLabel = [...focusControls,option('variant','Подложка',['surface','ghost']),text('label','Подпись','Название'),option('labelPlacement','Положение подписи',['outside','inside'],'inside'),toggle('showLabel','Показывать подпись',true)];
const fieldProps = (p: Values) => ({focusRing:focusRing(p),variant:s(p,'variant') as 'surface'|'ghost',label:b(p,'showLabel')?s(p,'label'):undefined,labelPlacement:s(p,'labelPlacement') as 'inside'|'outside'});
const contrast = toggle('contrast','Primary-заливка');
const feedbackControls = [option('tone','Статус',['neutral','info','success','warning','danger'],'success'),option('color','Цвет статуса',['auto','inherit',...UI.colors]),option('appearance','Заливка',['neutral','soft','solid']),toggle('feedbackContrast','Усилить контраст'),option('feedbackSurface','Поверхность сообщения',['inherit','base','canvas','raised','floating'])];
const feedbackProps=(p:Values)=>({tone:s(p,'tone') as UI.FeedbackTone,color:s(p,'color')==='auto'?undefined:s(p,'color') as UI.Color|'inherit',appearance:s(p,'appearance') as 'neutral'|'soft'|'solid',contrast:b(p,'feedbackContrast'),surface:s(p,'feedbackSurface') as 'inherit'|'base'|'canvas'|'raised'|'floating'});
const primaryContrast = toggle('contrast','Primary-заливка',true);
const disabled = toggle('disabled','Disabled');
const label = text('label','Текст','Сад идей');
const icon = option('icon','Иконка',UI.iconNames,'folder');
const variant = option('variant','Стиль',['primary','secondary','accent','accent-secondary','outline','ghost','danger'],'secondary');
const color = option('color','Акцент',['inherit',...UI.colors]);
const s = (p: Values, key: string) => String(p[key] ?? '');
const b = (p: Values, key: string) => p[key] === true;
const n = (p: Values, key: string) => Number(p[key]);
const sz = (p: Values) => s(p,'size') as UI.Size;
const hue = (p: Values) => !p.color || p.color === 'inherit' ? undefined : s(p,'color') as UI.Color;
const glyph = (p: Values, c: Context): UI.IconSource => c.icons.find(option=>option.name===s(p,'icon'))?.icon ?? 'folder';
const buttonStyle = (p: Values) => s(p,'variant') as UI.ButtonProps['variant'];
const make = (controls: Control[], render: Spec['render']): Spec => ({controls,render});
const event = (c: Context, name = 'Действие выполнено') => () => c.notify(name);
const menuItems = (c: Context) => [{id:'open',label:c.t('Открыть'),icon:'page' as const,onSelect:event(c,c.t('Объект открыт'))},{id:'copy',label:c.t('Дублировать'),icon:'copy' as const,onSelect:event(c,c.t('Копия создана'))}];
const choices = [{value:'project',label:'Проект'},{value:'note',label:'Заметка'},{value:'book',label:'Книга'}];
const content = 'Здесь можно собрать идеи и вернуться к ним позже.';
const markdown = '# Сад идей\n\nКороткая **заметка** и [ссылка](#Tag).\n\n- Наблюдение\n- Следующий шаг';
const orientation = option('orientation','Направление',['horizontal','vertical']);
const count = text('count','Счётчик','99+');
const boolSlots = [toggle('leading','Иконка слева',true),toggle('trailing','Иконка справа'),toggle('showText','Текст',true)];
const calendarControls = [option('mode','Выбор',['single','range']),text('value','Дата ISO','2026-10-07'),text('rangeEnd','Конец периода',''),option('months','Месяцев',['1','2'],'2'),toggle('showAgenda','Список событий',true),toggle('events','События',true),option('agendaPosition','Расположение событий',['bottom','side']),option('eventEmphasis','Главное в событии',['title','time']),toggle('showEventPreview','Подсказка дня',true),toggle('highlights','Отмеченные даты',true),toggle('limited','Ограничить месяц'),number('fromYear','Годы от',2000,1900,2100),number('toYear','Годы до',2050,2000,2200)];
const calendarProps = (p: Values, c: Context): UI.CalendarSelectionProps => ({
 today:'2026-10-07',defaultMonth:'2026-10',numberOfMonths:Number(s(p,'months')) as 1|2,
 min:b(p,'limited')?'2026-10-01':undefined,max:b(p,'limited')?'2026-10-31':undefined,
 showAgenda:b(p,'showAgenda'),agendaPosition:s(p,'agendaPosition') as 'bottom'|'side',eventEmphasis:s(p,'eventEmphasis') as 'title'|'time',showEventPreview:b(p,'showEventPreview'),
 events:b(p,'events')?localizeCatalogueFixture(scheduleEvents,c.t):[],highlightedDates:b(p,'highlights')?[{date:'2026-10-09',label:c.t('Срок передачи'),color:'orange'},{date:'2026-10-15',label:c.t('Важная дата'),color:'purple'}]:[],
 yearRange:[Math.min(n(p,'fromYear'),n(p,'toYear')),Math.max(n(p,'fromYear'),n(p,'toYear'))],
 ...(s(p,'mode')==='range'?{mode:'range',range:s(p,'value')?{start:s(p,'value'),end:s(p,'rangeEnd')||undefined}:undefined,onRangeChange:(range:UI.CalendarRange)=>{c.set('value',range.start);c.set('rangeEnd',range.end??'');}}:{value:s(p,'value'),onValueChange:(value:string)=>c.set('value',value)}),
});
const actionChildren = (p: Values,c: Context) => <><UI.IconButton icon="filter" label={c.t("Фильтр")} variant="ghost" onClick={event(c,c.t('Фильтр применён'))}/><UI.IconButton icon="list" label={c.t("Список")} variant="ghost" aria-pressed/><UI.IconButton icon="sliders" label={c.t("Настройки")} variant="ghost" onClick={event(c,c.t('Настройки открыты'))}/></>;
const cardControls = [label,toggle('description','Описание',true),option('density','Плотность',['comfortable','compact']),option('orientation','Направление',['vertical','horizontal']),toggle('selectable','Мультивыбор'),toggle('selected','Выбрано'),option('selectionPosition','Угол выбора',['top-start','top-end'])];
const cardProps = (p: Values,c: Context) => ({title:s(p,'label'),description:b(p,'description')?c.t(content):undefined,density:s(p,'density') as 'comfortable'|'compact',orientation:s(p,'orientation') as 'vertical'|'horizontal',selectionPosition:s(p,'selectionPosition') as UI.ContentCardProps['selectionPosition'],selectable:b(p,'selectable'),selected:b(p,'selected'),onSelectedChange:(v:boolean)=>c.set('selected',v),onOpen:event(c,c.t('Карточка открыта'))});
const modalControls = [text('label','Заголовок','Настройки'),option('size','Размер',['sm','md','lg','xl'],'md'),toggle('description','Описание',true),toggle('footer','Нижние действия',true),toggle('dismiss','Закрытие по фону',true)];
const modalContent = (c:Context) => <UI.Field label={c.t("Название")}>{props=><UI.Input {...props} defaultValue={c.t("Сад идей")}/>}</UI.Field>;
const modalProps = (p: Values,c: Context) => ({title:s(p,'label'),open:b(p,'open'),onOpenChange:(v:boolean)=>c.set('open',v),size:s(p,'size') as 'sm'|'md'|'lg'|'xl',description:b(p,'description')?c.t('Настройте параметры проекта.'):undefined,dismissOnOutside:b(p,'dismiss'),footer:b(p,'footer')?<UI.Button onClick={()=>c.set('open',false)}>{c.t("Готово")}</UI.Button>:undefined});

/** One explicit, typed entry per canonical component. Controls mutate real public props. */
export const playgrounds = {
 FileCard: make([option('size','Размер',['sm','md','lg'],'md'),text('name','Имя файла','brand-guidelines.pdf'),text('sizeLabel','Размер файла','248 KB'),text('thumbnail','Превью URL',''),text('mimeType','MIME',''),option('kind','Формат файла',['auto','image','pdf','presentation','document','spreadsheet','archive','audio','video','code','unknown']),toggle('open','Открытие',true),toggle('download','Скачивание'),toggle('remove','Удаление',true),toggle('loading','Загрузка'),disabled],(p,c)=>b(p,'removed')?<UI.Button onClick={()=>c.set('removed',false)}>{c.t('Вернуть файл')}</UI.Button>:<UI.FileCard name={s(p,'name')} sizeLabel={s(p,'sizeLabel')} thumbnail={s(p,'thumbnail')||undefined} mimeType={s(p,'mimeType')||undefined} kind={s(p,'kind')==='auto'?undefined:s(p,'kind') as UI.FileKind} size={s(p,'size') as UI.FileCardProps['size']} disabled={b(p,'disabled')} loading={b(p,'loading')} onOpen={b(p,'open')?event(c,c.t('Файл открыт')):undefined} onDownload={b(p,'download')?event(c,c.t('Файл подготовлен к скачиванию')):undefined} onRemove={b(p,'remove')?()=>c.set('removed',true):undefined}/>),
 Button: make([size,variant,label,icon,...boolSlots,disabled,toggle('loading','Loading')],(p,c)=><UI.Button size={sz(p)} variant={buttonStyle(p)} disabled={b(p,'disabled')} loading={b(p,'loading')} aria-label={!b(p,'showText')?s(p,'label'):undefined} leading={b(p,'leading')?<UI.Icon name={glyph(p,c)}/>:undefined} trailing={b(p,'trailing')?<UI.Icon name="down"/>:undefined} onClick={event(c)}>{b(p,'showText')?s(p,'label'):(!b(p,'leading')&&!b(p,'trailing')?<UI.Icon name={glyph(p,c)}/>:null)}</UI.Button>),
 IconButton: make([size,variant,icon,disabled,toggle('loading','Loading')],(p,c)=><UI.IconButton size={sz(p)} variant={buttonStyle(p)} icon={glyph(p,c)} label={c.t("Действие")} disabled={b(p,'disabled')} loading={b(p,'loading')} onClick={event(c)}/>),
 Icon: make([icon,number('pixels','Размер, px',24,12,64),number('stroke','Толщина штриха',1.65,.5,4)],(p,c)=><UI.Icon name={glyph(p,c)} size={n(p,'pixels')} strokeWidth={n(p,'stroke')}/>),
 ButtonGroup: make([size,orientation,option('appearance','Оформление',['default','framed']),option('color','Цвет',['neutral','inherit',...UI.colors.filter(color=>color!=='neutral')]),toggle('attached','Общая подложка',true),toggle('prefix','Счётчик',true),count],(p,c)=><UI.ButtonGroup appearance={s(p,'appearance') as UI.ButtonGroupProps['appearance']} label={c.t("Действия группы")} color={s(p,'color') as UI.Color|'inherit'} size={sz(p)} orientation={s(p,'orientation') as 'horizontal'|'vertical'} attached={b(p,'attached')} prefix={b(p,'prefix')?s(p,'count'):undefined}>{actionChildren(p,c)}</UI.ButtonGroup>),
 SplitButton: make([size,variant,option('layout','Соединение',['joined','separated']),label,toggle('leading','Иконка слева',true),disabled,toggle('loading','Loading')],(p,c)=><UI.SplitButton label={s(p,'label')} size={sz(p)} variant={buttonStyle(p)} layout={s(p,'layout') as 'joined'|'separated'} leading={b(p,'leading')?<UI.Icon name="plus"/>:undefined} disabled={b(p,'disabled')} loading={b(p,'loading')} items={menuItems(c)} onClick={event(c)}/>),
 ActionBar: make([size,orientation,toggle('roving','Навигация стрелками',true)],(p,c)=><UI.ActionBar label={c.t("Действия")} size={sz(p)} orientation={s(p,'orientation') as 'horizontal'|'vertical'} rovingFocus={b(p,'roving')}>{actionChildren(p,c)}</UI.ActionBar>),
 FloatingActionBar: make([option('size','Размер',['xs','sm','md','lg','xl'],'lg'),orientation,option('variant','Стиль',['surface','divided']),option('position','Положение',['static','sticky']),option('action','Правое действие',['accent','primary','none'],'accent'),toggle('leading','Счётчик слева',true)],(p,c)=>{
  const bar=<UI.FloatingActionBar label={c.t("Плавающие действия")} position="static" size={s(p,'size') as UI.FloatingActionBarProps['size']} orientation={s(p,'orientation') as 'horizontal'|'vertical'} leading={b(p,'leading')?<UI.Counter value="99+" variant="plain"/>:undefined} variant={s(p,'variant') as 'surface'|'divided'} action={s(p,'action')!=='none'?{label:c.t('Готово'),icon:'check',variant:s(p,'action') as 'accent'|'primary',onClick:event(c,c.t('Сохранено'))}:undefined}>{actionChildren(p,c)}</UI.FloatingActionBar>;
  return s(p,'position')==='sticky'?<UI.ScrollArea className="playground-floating-stage" label={c.t("Прокрутка с действиями")} floating={bar}><div className="catalog-long-note">{Array.from({length:8},(_,i)=><p key={i}>{c.t(content)}</p>)}</div></UI.ScrollArea>:<div className="playground-floating-static">{bar}</div>;
 }),
 Kbd: make([text('label','Клавиши','⌘ K')],(p,c)=><UI.Kbd>{s(p,'label')}</UI.Kbd>),
 Input: make([...fieldLabel,size,text('value','Значение',''),text('placeholder','Placeholder','Название'),option('type','Тип',['text','email','password','search']),disabled,toggle('invalid','Ошибка'),toggle('readOnly','Read only')],(p,c)=><UI.Input {...fieldProps(p)} aria-label={b(p,'showLabel')?undefined:c.t("Поле в песочнице")} size={sz(p)} value={s(p,'value')} onChange={e=>c.set('value',e.target.value)} placeholder={s(p,'placeholder')} type={s(p,'type')} disabled={b(p,'disabled')} readOnly={b(p,'readOnly')} aria-invalid={b(p,'invalid')||undefined}/>),
 Textarea: make([...fieldLabel,size,text('value','Значение',content),number('rows','Строки',3,2,10),disabled,toggle('readOnly','Read only')],(p,c)=><UI.Textarea {...fieldProps(p)} size={sz(p)} aria-label={b(p,'showLabel')?undefined:c.t("Заметка в песочнице")} value={s(p,'value')} onChange={e=>c.set('value',e.target.value)} rows={n(p,'rows')} disabled={b(p,'disabled')} readOnly={b(p,'readOnly')}/>),
 Select: make([...fieldLabel,size,option('value','Выбрано',['project','note','book']),toggle('groups','Группы',true),toggle('longOptions','Длинные значения'),disabled,toggle('invalid','Ошибка')],(p,c)=><UI.Select {...fieldProps(p)} aria-label={b(p,'showLabel')?undefined:c.t("Тип объекта в песочнице")} value={s(p,'value')} onValueChange={v=>c.set('value',v)} size={sz(p)} options={choices.map((o,i)=>({...o,label:b(p,'longOptions')?`${c.t(o.label)} — ${c.t("исследование пользовательского опыта")}`:c.t(o.label),group:b(p,'groups')?(i<2?c.t('Объекты'):c.t('Коллекции')):undefined}))} disabled={b(p,'disabled')} aria-invalid={b(p,'invalid')||undefined}/>),
 Field: make([label,toggle('hint','Подсказка',true),toggle('error','Ошибка'),toggle('required','Обязательное')],(p,c)=><UI.Field label={s(p,'label')} hint={b(p,'hint')?c.t('Короткое имя проекта'):undefined} error={b(p,'error')?c.t('Введите название'):undefined} required={b(p,'required')}>{props=><UI.Input {...props}/>}</UI.Field>),
 Checkbox: make([size,primaryContrast,label,toggle('checked','Checked',true),toggle('indeterminate','Indeterminate'),disabled],(p,c)=><UI.Checkbox label={s(p,'label')} contrast={b(p,'contrast')} size={sz(p)} checked={b(p,'checked')} indeterminate={b(p,'indeterminate')} disabled={b(p,'disabled')} onChange={e=>c.set('checked',e.target.checked)}/>),
 Radio: make([size,primaryContrast,option('value','Выбрано',['private','team']),disabled],(p,c)=><fieldset className="playground-radio"><legend className="cap-sr-only">{c.t("Доступ к проекту")}</legend>{['private','team'].map((v,i)=><UI.Radio contrast={b(p,'contrast')} key={v} name={c.id} label={i?c.t('Команда'):c.t('Только я')} value={v} checked={s(p,'value')===v} size={sz(p)} disabled={b(p,'disabled')} onChange={()=>c.set('value',v)}/>)}</fieldset>),
 Switch: make([size,primaryContrast,label,option('variant','Стиль',['accent','neutral']),toggle('checked','Checked',true),disabled],(p,c)=><UI.Switch label={s(p,'label')} size={sz(p)} contrast={b(p,'contrast')} variant={s(p,'variant') as 'accent'|'neutral'} checked={b(p,'checked')} disabled={b(p,'disabled')} onChange={e=>c.set('checked',e.target.checked)}/>),
 Slider: make([size,contrast,number('value','Значение',48),number('step','Шаг',1,1,25),toggle('showValue','Показывать значение',true),disabled],(p,c)=><UI.Slider contrast={b(p,'contrast')} label={c.t("Плотность")} size={sz(p)} value={n(p,'value')} onChange={e=>c.set('value',Number(e.target.value))} step={n(p,'step')} showValue={b(p,'showValue')} disabled={b(p,'disabled')}/>),
 SegmentedControl: make([size,option('variant','Стиль',['surface','outline','accent','ghost']),option('value','Выбрано',['grid','list']),toggle('icons','Иконки',true),toggle('disabled','Второй недоступен')],(p,c)=><UI.SegmentedControl size={sz(p)} variant={s(p,'variant') as UI.SegmentedControlProps['variant']} label={c.t("Представление в песочнице")} value={s(p,'value')} onValueChange={v=>c.set('value',v)} options={['grid','list'].map((v,i)=>({value:v,label:i?c.t('Список'):c.t('Карточки'),icon:b(p,'icons')?<UI.Icon name={v as 'grid'|'list'}/>:undefined,disabled:i===1&&b(p,'disabled')}))}/>),
 Calendar: make(calendarControls,(p,c)=><UI.Calendar {...calendarProps(p,c)} label={c.t("Календарь в песочнице")}/>),
 DatePicker: make(calendarControls,(p,c)=><UI.DatePicker {...calendarProps(p,c)} label={c.t("Дата в песочнице")}/>),
 BottomSheet: make([text('title','Заголовок','Детали проекта'),option('variant','Край',['inset','edge']),number('gap','Отступ от края',12,0,32),option('snap','Высота',['0','1']),toggle('draggable','Перетаскивание',true),toggle('footer','Нижние действия',true)],(p,c)=><><UI.Button onClick={()=>c.set('open',true)}>{c.t("Открыть нижнюю панель")}</UI.Button><UI.BottomSheet open={b(p,'open')} onOpenChange={value=>c.set('open',value)} title={s(p,'title')} variant={s(p,'variant') as 'inset'|'edge'} edgeGap={n(p,'gap')} snap={n(p,'snap')} onSnapChange={value=>c.set('snap',String(value))} draggable={b(p,'draggable')} footer={b(p,'footer')?<UI.Button onClick={()=>c.set('open',false)}>{c.t("Готово")}</UI.Button>:undefined}><UI.Input label={c.t("Название")} defaultValue={c.t("Сад идей")}/><p>{c.t("Перемещайте ручку или используйте стрелки на клавиатуре.")}</p></UI.BottomSheet></>),
 FileTree: make([size,toggle('guides','Направляющие',true),toggle('preview','Предпросмотр',true),toggle('empty','Пустое дерево'),toggle('expanded','Раскрыть папки',true)],(p,c)=><UI.FileTree key={String(b(p,'expanded'))} label={c.t("Файлы проекта")} nodes={b(p,'empty')?[]:localizeCatalogueFixture(revisionFiles,c.t)} size={sz(p)} showGuides={b(p,'guides')} showPreview={b(p,'preview')} defaultExpandedIds={b(p,'expanded')?revisionFiles.filter(node=>node.type==='folder').map(node=>node.id):[]} onSelect={node=>c.notify(node.name)}/>),
 PreviewRail: make([orientation,option('previewSide','Сторона превью',['before','after'],'after'),toggle('preview','Предпросмотр',true),toggle('active','Выделять выбранный'),toggle('empty','Пустой список')],(p,c)=><UI.PreviewRail label={c.t("Разделы проекта")} items={b(p,'empty')?[]:localizeCatalogueFixture(revisionRailItems,c.t)} value={s(p,'selected')||undefined} onValueChange={value=>c.set('selected',value)} orientation={s(p,'orientation') as 'horizontal'|'vertical'} previewSide={s(p,'previewSide') as 'before'|'after'} showPreview={b(p,'preview')} highlightActive={b(p,'active')}/>),
 Chip: make([size,text('label','Текст','Engineering'),option('shape','Форма',['rounded','pill']),toggle('selected','Выбран'),toggle('icon','Иконка',true),toggle('remove','Удаление',true),toggle('count','Счётчик'),disabled],(p,c)=><UI.Chip size={sz(p)} shape={s(p,'shape') as 'rounded'|'pill'} selected={b(p,'selected')} icon={b(p,'icon')?'code':undefined} count={b(p,'count')?12:undefined} disabled={b(p,'disabled')} onClick={()=>c.set('selected',!b(p,'selected'))} onRemove={b(p,'remove')?event(c,c.t('Метка удалена')):undefined}>{s(p,'label')}</UI.Chip>),
 Tag: make([size,option('shape','Форма',['rounded','pill']),option('variant','Стиль',['soft','solid','outline']),label,color,icon,toggle('leading','Иконка слева',true),toggle('showCount','Счётчик',true),count,option('counter','Стиль счётчика',['translucent','plain','accent','white','black']),option('action','Действие',['close','more','none']),toggle('interactive','Интерактивный',true),disabled],(p,c)=><UI.Tag shape={s(p,'shape') as 'rounded'|'pill'} size={sz(p)} variant={s(p,'variant') as 'soft'|'solid'|'outline'} color={hue(p)} icon={b(p,'leading')?glyph(p,c):undefined} count={b(p,'showCount')?s(p,'count'):undefined} counter={{variant:s(p,'counter') as UI.CounterVariant}} interactive={b(p,'interactive')} disabled={b(p,'disabled')} onClick={event(c,c.t('Тег выбран'))} action={s(p,'action')==='none'?undefined:{icon:s(p,'action') as 'close'|'more',label:s(p,'action')==='close'?c.t('Удалить тег'):c.t('Действия тега'),onClick:event(c,s(p,'action')==='close'?c.t('Тег удалён'):c.t('Действия тега'))}}>{s(p,'label')}</UI.Tag>),
 Counter: make([size,text('value','Значение','99+'),option('variant','Стиль',['neutral','translucent','accent','white','black','plain']),option('shape','Форма',['round','rounded']),color],(p,c)=><UI.Counter value={s(p,'value')} size={sz(p)} variant={s(p,'variant') as UI.CounterVariant} shape={s(p,'shape') as 'round'|'rounded'} color={hue(p)}/>),
 TextAction: make([label,toggle('icon','Иконка',true),disabled],(p,c)=><UI.TextAction disabled={b(p,'disabled')} onClick={event(c)}>{b(p,'icon')&&<UI.Icon name="external"/>}{s(p,'label')}</UI.TextAction>),
 ResizableCard: make([number('width','Ширина',360,160,800),number('height','Высота',240,120,800),option('variant','Подложка',['default','subtle','elevated']),toggle('resizable','Изменение размера',true),disabled],(p,c)=><UI.ResizableCard label={c.t("Карточка в песочнице")} size={{width:n(p,'width'),height:n(p,'height')}} onSizeChange={value=>{c.set('width',value.width);c.set('height',value.height);}} variant={s(p,'variant') as UI.ResizableCardProps['variant']} resizable={b(p,'resizable')} disabled={b(p,'disabled')}><h3>{c.t("Сад идей")}</h3><p>{c.t("Потяните за угол карточки или используйте стрелки, когда ручка в фокусе.")}</p><UI.Tag color="neutral" interactive={false}>{c.t("Заметка")}</UI.Tag></UI.ResizableCard>),
 ResizablePanelGroup: make([option('orientation','Ось',['horizontal','vertical']),toggle('withHandle','Показывать ручку',true),toggle('nested','Вложенная группа',true),disabled,number('minSize','Минимальная доля, %',15,0,45)],(p,c)=><ResizableExample orientation={s(p,'orientation') as 'horizontal'|'vertical'} withHandle={b(p,'withHandle')} nested={b(p,'nested')} disabled={b(p,'disabled')} minSize={n(p,'minSize')}/>),
 ContentLayout: make([option('orientation','Ось',['horizontal','vertical']),option('divider','Разделитель',['always','hover','none'],'hover'),toggle('stretch','Растягивать контент',true),toggle('autoStack','Автокомпоновка',true),number('paneHeight','Высота панели',180,100,400),toggle('left','Левая панель',true),toggle('right','Правая панель'),number('leftWidth','Левая ширина',180,160,400),number('rightWidth','Правая ширина',240,160,400),number('contentWidth','Ширина контента',480,200,900)],(p,c)=><UI.ContentLayout collapseAt={b(p,'autoStack')?600:0} minContentSize={200} style={s(p,'orientation')==='vertical'?{height:620}:undefined} orientation={s(p,'orientation') as 'horizontal'|'vertical'} divider={s(p,'divider') as 'always'|'hover'|'none'} stretch={b(p,'stretch')} label={c.t("Документ в песочнице")} contentWidth={n(p,'contentWidth')} left={{label:c.t('Коллекции'),height:n(p,'paneHeight'),onHeightChange:v=>c.set('paneHeight',v),content:<UI.SidebarItem icon="folder" active>{c.t("Проект")}</UI.SidebarItem>,open:b(p,'left'),onOpenChange:v=>c.set('left',v),width:n(p,'leftWidth'),onWidthChange:v=>c.set('leftWidth',v)}} right={{label:c.t('Свойства'),height:n(p,'paneHeight'),onHeightChange:v=>c.set('paneHeight',v),content:<UI.PropertyRow label={c.t("Статус")}>{c.t("В работе")}</UI.PropertyRow>,open:b(p,'right'),onOpenChange:v=>c.set('right',v),width:n(p,'rightWidth'),onWidthChange:v=>c.set('rightWidth',v)}}><div className="catalog-stack"><h3>{c.t("Сад идей")}</h3><p>{c.t("Перетащите разделитель рядом с панелью или нажмите Tab и используйте стрелки. На узком экране автокомпоновка складывает панели.")}</p><UI.ContentCard title={c.t("Следующий шаг")} description={c.t(content)}/></div></UI.ContentLayout>),
 IconPicker: make([size,...focusControls,option('variant','Вид',['combobox','grid']),number('iconSize','Размер иконок',20,12,36),disabled],(p,c)=><UI.IconPicker size={sz(p)} focusRing={focusRing(p)} variant={s(p,'variant') as 'grid'|'combobox'} options={c.icons} value={s(p,'value')} onValueChange={v=>c.set('value',v)} iconSize={n(p,'iconSize')} disabled={b(p,'disabled')} label={c.t("Иконка в песочнице")}/>),
 IconBox: make([size,icon,color],(p,c)=><UI.IconBox icon={glyph(p,c)} color={hue(p)} size={sz(p)}/>),
 Avatar: make([size,text('label','Имя','Анна Иванова')],(p,c)=><UI.Avatar name={s(p,'label')} size={sz(p)}/>),
 Separator: make([orientation,number('length','Длина, px',160,8,600),option('contrast','Контраст',['subtle','normal','strong']),option('reveal','Появление',['always','hover'])],(p,c)=><div style={{padding:20,display:'flex',minWidth:60,minHeight:60,maxWidth:'100%'}}><UI.Separator orientation={s(p,'orientation') as 'horizontal'|'vertical'} length={n(p,'length')} contrast={s(p,'contrast') as 'subtle'|'normal'|'strong'} reveal={s(p,'reveal') as 'always'|'hover'}/></div>),
 Card: make([option('variant','Поверхность',['default','subtle','elevated']),label,toggle('description','Описание',true)],(p,c)=><UI.Card variant={s(p,'variant') as 'default'|'subtle'|'elevated'}><h3>{s(p,'label')}</h3>{b(p,'description')&&<p>{c.t(content)}</p>}</UI.Card>),
 ObjectCard: make([label,icon,color,toggle('description','Описание',true),toggle('meta','Свойства',true),disabled],(p,c)=><UI.ObjectCard title={s(p,'label')} icon={glyph(p,c)} color={hue(p)} description={b(p,'description')?c.t(content):undefined} meta={b(p,'meta')?c.t('Обновлено сегодня'):undefined} disabled={b(p,'disabled')} onClick={event(c,c.t('Объект открыт'))}/>),
 CollectionRow: make([label,icon,color,toggle('meta','Счётчик',true),disabled],(p,c)=><UI.CollectionRow title={s(p,'label')} icon={glyph(p,c)} color={hue(p)} meta={b(p,'meta')?<UI.Counter value="99+" size="xs" variant="plain"/>:undefined} disabled={b(p,'disabled')} onClick={event(c,c.t('Коллекция открыта'))}/>),
 PropertyRow: make([label,text('value','Значение','В работе'),icon,toggle('leading','Иконка',true)],(p,c)=><UI.PropertyRow label={s(p,'label')} icon={b(p,'leading')?glyph(p,c):undefined}>{s(p,'value')}</UI.PropertyRow>),
 Table: make([text('label','Подпись','Проекты'),number('rows','Строки',3,0,8)],(p,c)=><UI.Table caption={s(p,'label')} columns={[c.t('Название'),c.t('Статус')]} rows={Array.from({length:n(p,'rows')},(_,i)=>[`Проект ${i+1}`,<UI.Tag key={i}>{c.t("В работе")}</UI.Tag>])}/>),
 CodeBlock: make([option('variant','Стиль',['auto','surface','outline','filled-outline'],'surface'),option('language','Язык',['text','tsx','ts','js','json','css','bash']),option('color','Цвет',['neutral','inherit',...UI.colors.filter(color=>color!=='neutral')]),text('filename','Название файла','example.tsx'),toggle('lineNumbers','Номера строк',true),toggle('languageSelector','Выбор языка в блоке',true),toggle('copyable','Копирование',true),toggle('wrap','Перенос строк'),toggle('actions','Дополнительные действия',true)],(p,c)=><UI.CodeBlock filename={s(p,'filename')||undefined} lineNumbers={b(p,'lineNumbers')} language={s(p,'language') as UI.CodeBlockProps['language']} onLanguageChange={value=>c.set('language',value)} color={s(p,'color') as UI.CodeBlockProps['color']} showLanguageSelector={b(p,'languageSelector')} variant={s(p,'variant') as UI.CodeBlockProps['variant']} copyable={b(p,'copyable')} wrap={b(p,'wrap')} showActionsMenu={b(p,'actions')} onWrapChange={value=>c.set('wrap',value)}>{'// Счётчик проекта\nconst count = 99;\n<Tag size="sm" count={count}>Проект</Tag>'}</UI.CodeBlock>),
 MarkdownPreview: make([text('value','Markdown',markdown),number('headingOffset','Сдвиг заголовков',1,0,3)],(p,c)=><UI.MarkdownPreview value={s(p,'value')} headingOffset={n(p,'headingOffset') as 0|1|2|3}/>),
  MarkdownEditorV2: make([option('toolbarSize','Размер панели',['xs','sm','md','lg','xl'],'xs'),text('label','Подпись','Заметка'),text('value','Markdown','# Сад идей\n\nЗапишите следующий шаг.'),text('placeholder','Placeholder','Начните писать или введите /'),toggle('comments','Запрос комментария',true),toggle('readOnly','Только чтение'),disabled],(p,c)=><UI.MarkdownEditorV2 toolbarSize={s(p,'toolbarSize') as UI.Size} label={s(p,'label')} value={s(p,'value')} onValueChange={value=>c.set('value',value)} placeholder={s(p,'placeholder')} readOnly={b(p,'readOnly')} disabled={b(p,'disabled')} onCommentRequest={b(p,'comments')?()=>c.notify(c.t('Комментарий запрошен')):undefined}/>),
 MarkdownEditor: make([text('value','Markdown',markdown),option('mode','Режим',['edit','preview','split']),disabled,toggle('readOnly','Read only')],(p,c)=><UI.MarkdownEditor key={s(p,'mode')} label={c.t("Редактор в песочнице")} value={s(p,'value')} onValueChange={v=>c.set('value',v)} defaultMode={s(p,'mode') as 'edit'|'preview'|'split'} disabled={b(p,'disabled')} readOnly={b(p,'readOnly')} onSave={event(c,c.t('Заметка сохранена'))}/>),
 ContentCard: make(cardControls.filter(control=>control.key!=='description'),(p,c)=><CardComposer {...cardProps(p,c)}/>),
 ReorderableList: make([disabled,toggle('cards','Карточки',true)],(p,c)=><ReorderExample disabled={b(p,'disabled')} cards={b(p,'cards')}/>),
 TaskCard: make([...cardControls,color,toggle('completed','Завершена')],(p,c)=><UI.TaskCard {...cardProps(p,c)} color={hue(p)} completed={b(p,'completed')} onCompletedChange={v=>c.set('completed',v)} menuItems={menuItems(c)}/>),
 KanbanColumn: make([label,option('variant','Стиль',['default','framed']),toggle('footer','Нижнее действие'),option('color','Цвет заголовка',['neutral','inherit',...UI.colors.filter(c=>c!=='neutral')]),number('count','Карточки',2,0,5),toggle('action','Кнопка добавления',true)],(p,c)=><UI.KanbanColumn variant={s(p,'variant') as UI.KanbanColumnProps['variant']} icon="clock" footer={b(p,'footer')?<UI.Button variant="ghost" leading="plus" onClick={()=>c.set('count',n(p,'count')+1)}>{c.t("Добавить карточку")}</UI.Button>:undefined} color={s(p,'color') as UI.Color|'inherit'} title={s(p,'label')} count={n(p,'count')} action={b(p,'action')?<UI.IconButton label={c.t("Добавить карточку")} icon="plus" variant="ghost" onClick={()=>c.set('count',n(p,'count')+1)}/>:undefined}>{Array.from({length:n(p,'count')},(_,i)=><UI.TaskCard key={i} title={`Задача ${i+1}`}/>)}</UI.KanbanColumn>),
 KanbanBoard: make([disabled,toggle('add','Добавление',true),option('dragActivation','Начало переноса',['card','handle']),option('columnVariant','Стиль колонок',['default','framed']),toggle('customCards','Слоты карточки')],(p,c)=><KanbanPlaygroundExample dragActivation={s(p,'dragActivation') as UI.KanbanBoardProps['dragActivation']} disabled={b(p,'disabled')} add={b(p,'add')} columnVariant={s(p,'columnVariant') as UI.KanbanColumnProps['variant']} customCards={b(p,'customCards')}/>),
 DailyHeader: make([text('date','Дата ISO','2026-10-07'),toggle('showWeek','Номер недели',true),toggle('tags','Теги',true)],(p,c)=><UI.DailyHeader date={s(p,'date')||'2026-10-07'} showWeek={b(p,'showWeek')} tags={b(p,'tags')?<UI.Tag icon="book">{c.t("Заметки")}</UI.Tag>:undefined}/>),
 SidebarItem: make([label,icon,color,toggle('active','Активен',true),toggle('showCount','Счётчик',true),number('count','Значение',99,0,999),disabled],(p,c)=><UI.SidebarItem color={s(p,'color') as UI.Color|'inherit'} icon={glyph(p,c)} active={b(p,'active')} count={b(p,'showCount')?n(p,'count'):undefined} disabled={b(p,'disabled')} onClick={()=>c.set('active',!b(p,'active'))}>{s(p,'label')}</UI.SidebarItem>),
 Breadcrumbs: make([number('depth','Уровни',3,1,5)],(p,c)=><UI.Breadcrumbs label={c.t("Путь в песочнице")} items={[c.t('Проекты'),c.t('Коллекции'),c.t('Сад идей'),c.t('Заметки'),c.t('Эскиз')].slice(0,n(p,'depth')).map((label,i,all)=>({label,href:i<all.length-1?'#Breadcrumbs':undefined}))}/>),
 Accordion: make([option('variant','Стиль',['default','navigation','bouncy']),label,toggle('open','Раскрыт',true),toggle('long','Длинный контент')],(p,c)=><UI.Accordion variant={s(p,'variant') as UI.AccordionProps['variant']} title={s(p,'label')} open={b(p,'open')} onToggle={e=>c.set('open',e.currentTarget.open)}>{b(p,'long')?Array(5).fill(c.t(content)).join(' '):c.t(content)}</UI.Accordion>),
 Tabs: make([size,option('variant','Стиль',['line','pills','segment','outline','accent','workspace']),option('value','Активная',['overview','notes']),toggle('disabled','Вторая недоступна'),toggle('counts','Счётчики',true),toggle('icons','Иконки вкладок',true),toggle('trailing','Действие справа'),option('firstColor','Акцент первой',['inherit',...UI.colors],'blue'),option('secondColor','Акцент второй',['inherit',...UI.colors],'purple')],(p,c)=><UI.Tabs trailing={b(p,'trailing')?<UI.IconButton icon="plus" label={c.t("Добавить раздел")} variant="ghost" onClick={()=>c.notify(c.t("Раздел добавлен"))}/>:undefined} size={sz(p)} label={c.t("Разделы в песочнице")} variant={s(p,'variant') as UI.TabsProps['variant']} value={s(p,'value')} onValueChange={v=>c.set('value',v)} items={[{value:'overview',label:c.t('Обзор'),icon:b(p,'icons')?'grid':undefined,count:b(p,'counts')?0:undefined,color:s(p,'firstColor') as UI.Color|'inherit',content:<p>{c.t(content)}</p>},{value:'notes',label:c.t('Заметки'),count:b(p,'counts')?24:undefined,color:s(p,'secondColor') as UI.Color|'inherit',content:<p>{c.t("Новая заметка")}</p>,disabled:b(p,'disabled')}]}/>),
 SidebarPanel: make([option('surface','Подложка панели',['base','canvas','raised','floating'],'canvas'),number('width','Ширина',280,160,480),toggle('header','Шапка',true),toggle('footer','Нижний блок',true),toggle('actions','Действия',true),option('footerAlign','Выравнивание действий',['start','center','end','stretch']),toggle('groups','Группы',true),toggle('expanded','Первая группа раскрыта',true),toggle('counts','Счётчики',true),toggle('accents','Акценты пунктов',true)],(p,c)=>{const items=<><UI.SidebarItem icon="folder" active={s(p,'active')!=='notes'} color={b(p,'accents')?'blue':'neutral'} count={b(p,'counts')?3:undefined} onClick={()=>c.set('active','project')}>{c.t("Проект")}</UI.SidebarItem><UI.SidebarItem icon="book" active={s(p,'active')==='notes'} color={b(p,'accents')?'purple':'neutral'} count={b(p,'counts')?24:undefined} onClick={()=>c.set('active','notes')}>{c.t("Заметки")}</UI.SidebarItem></>;return <UI.SidebarPanel surface={s(p,'surface') as 'base'|'canvas'|'raised'|'floating'} label={c.t("Панель в песочнице")} width={n(p,'width')} header={b(p,'header')?c.t('Навигация'):undefined} footerAlign={s(p,'footerAlign') as UI.SidebarPanelProps['footerAlign']} footer={b(p,'footer')?<><span>{c.t("Обновлено сегодня")}</span>{b(p,'actions')&&<UI.FloatingActionBar label={c.t("Действия пространства")} size="sm" position="static"><UI.IconButton label={c.t("Добавить заметку")} icon="plus" variant="ghost" onClick={()=>c.notify(c.t('Заметка добавлена'))}/><UI.IconButton label={c.t("Настройки пространства")} icon="settings" variant="ghost" onClick={()=>c.notify(c.t('Настройки открыты'))}/></UI.FloatingActionBar>}</>:undefined}>{b(p,'groups')?<><UI.Accordion title={c.t("Рабочее пространство")} variant="navigation" open={b(p,'expanded')} onToggle={event=>c.set('expanded',event.currentTarget.open)} expandLabel={c.t("Раскрыть рабочее пространство")} collapseLabel={c.t("Свернуть рабочее пространство")}>{items}</UI.Accordion><UI.Accordion title={c.t("Архив")} variant="navigation" expandLabel={c.t("Раскрыть архив")} collapseLabel={c.t("Свернуть архив")}><UI.SidebarItem icon="folder" count={0}>{c.t("Завершённые")}</UI.SidebarItem></UI.Accordion></>:items}</UI.SidebarPanel>;}),
 ScrollArea: make([option('axis','Направление',['vertical','horizontal','both']),option('scrollbar','Скроллбар',['auto','hidden']),toggle('shadows','Подсказки у краёв',true),toggle('fade','Затухание',true),option('fadeDirection','Направление затухания',['auto','horizontal','vertical','both']),number('fadeSize','Размер затухания, px',20,0,80),number('fadeReveal','Раскрытие у края, px',20,0,80),number('height','Высота',180,80,360)],(p,c)=><UI.ScrollArea label={c.t("Прокрутка в песочнице")} axis={s(p,'axis') as 'vertical'|'horizontal'|'both'} scrollbar={s(p,'scrollbar') as 'auto'|'hidden'} shadows={b(p,'shadows')} fade={b(p,'fade')?(s(p,'fadeDirection')==='auto'?true:s(p,'fadeDirection') as 'horizontal'|'vertical'|'both'):false} fadeSize={n(p,'fadeSize')} fadeReveal={n(p,'fadeReveal')} style={{height:n(p,'height'),width:'100%'}}><div style={{width:s(p,'axis')==='vertical'?'auto':900}}>{Array.from({length:12},(_,i)=><p key={i}>{c.t("Заметка ")}{i+1}. {c.t(content)}</p>)}</div></UI.ScrollArea>),
 Spinner: make([text('label','Доступная подпись','Загрузка'),number('size','Размер, px',20,12,48)],(p,c)=><UI.Spinner label={s(p,'label')} style={{width:n(p,'size'),height:n(p,'size')}}/>),
 Skeleton: make([number('width','Ширина',240,24,600),number('height','Высота',64,16,240),number('radius','Скругление',8,0,40)],(p,c)=><UI.Skeleton style={{width:n(p,'width'),maxWidth:'100%',height:n(p,'height'),borderRadius:n(p,'radius')}}/>),
 Progress: make([number('value','Прогресс',64),text('label','Подпись','Подготовка')],(p,c)=><UI.Progress value={n(p,'value')} label={s(p,'label')}/>),
 Callout: make([color,icon,label,toggle('title','Заголовок',true)],(p,c)=><UI.Callout color={hue(p)} icon={glyph(p,c)} title={b(p,'title')?s(p,'label'):undefined}>{c.t(content)}</UI.Callout>),
 EmptyState: make([label,icon,toggle('showIcon','Показывать иконку',true),toggle('description','Описание',true),toggle('action','Действие',true)],(p,c)=><UI.EmptyState title={s(p,'label')} icon={b(p,'showIcon')?glyph(p,c):false} description={b(p,'description')?c.t(content):undefined} action={b(p,'action')?<UI.Button leading={<UI.Icon name="plus"/>} onClick={event(c,c.t('Объект создан'))}>{c.t("Создать")}</UI.Button>:undefined}/>),
 Toast: make([label,...feedbackControls,toggle('description','Описание',true),toggle('dismiss','Закрытие',true)],(p,c)=>b(p,'hidden')?<UI.Button onClick={()=>c.set('hidden',false)}>{c.t("Показать снова")}</UI.Button>:<UI.Toast {...feedbackProps(p)} title={s(p,'label')} description={b(p,'description')?c.t(content):undefined} onDismiss={b(p,'dismiss')?()=>c.set('hidden',true):undefined}/>),
 StatusBar: make([label,...feedbackControls,option('variant','Стиль',['plain','surface']),toggle('busy','Загрузка'),toggle('leading','Иконка слева',true),toggle('trailing','Счётчик справа')],(p,c)=><UI.StatusBar {...feedbackProps(p)} variant={s(p,'variant') as 'plain'|'surface'} busy={b(p,'busy')} leading={b(p,'leading')?<UI.Icon name="check"/>:undefined} trailing={b(p,'trailing')?<UI.Counter value="99+" size="xs"/>:undefined}>{s(p,'label')}</UI.StatusBar>),
 Alert: make([label,...feedbackControls,toggle('expandable','Раскрытие',true),toggle('expanded','Раскрыт',true),toggle('dismiss','Закрытие')],(p,c)=>b(p,'hidden')?<UI.Button onClick={()=>c.set('hidden',false)}>{c.t("Показать снова")}</UI.Button>:<UI.Alert {...feedbackProps(p)} title={s(p,'label')} expandable={b(p,'expandable')} expanded={b(p,'expanded')} onExpandedChange={v=>c.set('expanded',v)} onDismiss={b(p,'dismiss')?()=>c.set('hidden',true):undefined}>{c.t(content)}</UI.Alert>),
 Dialog: make(modalControls,(p,c)=><><UI.Button onClick={()=>c.set('open',true)}>{c.t("Открыть диалог")}</UI.Button><UI.Dialog {...modalProps(p,c)}>{modalContent(c)}</UI.Dialog></>),
 Drawer: make([...modalControls,option('side','Сторона',['right','left','bottom']),option('variant','Стиль',['inset','edge'])],(p,c)=><><UI.Button onClick={()=>c.set('open',true)}>{c.t("Открыть панель")}</UI.Button><UI.Drawer {...modalProps(p,c)} side={s(p,'side') as 'right'|'left'|'bottom'} variant={s(p,'variant') as 'inset'|'edge'}>{modalContent(c)}</UI.Drawer></>),
 Tooltip: make([text('label','Текст','Создать заметку'),text('caption','Лейбл',''),text('description','Подпись',''),option('variant','Стиль',['default','inverse']),toggle('arrow','Язычок'),option('side','Сторона',['top','bottom']),option('align','Привязка',['start','center','end'],'center'),toggle('shortcut','Клавиши',true),size],(p,c)=><UI.Tooltip content={s(p,'label')} caption={s(p,'caption')||undefined} description={s(p,'description')||undefined} variant={s(p,'variant') as UI.TooltipProps['variant']} arrow={b(p,'arrow')} side={s(p,'side') as 'top'|'bottom'} align={s(p,'align') as 'start'|'center'|'end'} shortcut={b(p,'shortcut')?['⌘','N']:undefined}><UI.IconButton label={c.t("Новая заметка")} icon="plus" size={sz(p)} variant="ghost"/></UI.Tooltip>),
 Menu: make([size,variant,icon,disabled,toggle('danger','Опасное действие'),toggle('unavailable','Недоступный пункт')],(p,c)=><UI.Menu label={c.t("Меню в песочнице")} size={sz(p)} variant={buttonStyle(p)} icon={glyph(p,c)} disabled={b(p,'disabled')} items={[...menuItems(c),{id:'delete',label:c.t('Удалить'),icon:'trash',separator:true,danger:b(p,'danger'),disabled:b(p,'unavailable'),onSelect:event(c,c.t('Объект удалён'))}]}/>),
 Popover: make([size,label,toggle('iconOnly','Кнопка-иконка'),icon,option('side','Сторона',['bottom','top']),option('align','Выравнивание',['start','center','end']),disabled],(p,c)=><UI.Popover label={s(p,'label')} triggerIcon={b(p,'iconOnly')?s(p,'icon') as UI.IconName:undefined} size={sz(p)} side={s(p,'side') as 'bottom'|'top'} align={s(p,'align') as 'start'|'center'|'end'} disabled={b(p,'disabled')}><div className="catalog-stack"><p>{c.t(content)}</p><UI.Tag icon="folder" count="99+">{c.t("Проект")}</UI.Tag><UI.Switch label={c.t("Уведомления")} defaultChecked/></div></UI.Popover>),
 CommandPalette: make([text('placeholder','Placeholder','Найти команду…'),toggle('description','Описания',true),toggle('icons','Иконки',true)],(p,c)=><><UI.Button onClick={()=>c.set('open',true)}>{c.t("Открыть команды")}</UI.Button><UI.CommandPalette open={b(p,'open')} onOpenChange={v=>c.set('open',v)} placeholder={s(p,'placeholder')} items={[c.t('Новая заметка'),c.t('Новый проект'),c.t('Открыть календарь')].map((label,i)=>({id:String(i),label,description:b(p,'description')?c.t('Создание и навигация'):undefined,icon:b(p,'icons')?'page':undefined,onSelect:()=>{c.set('open',false);c.notify(label);}}))}/></>),
} satisfies Record<Exclude<ComponentName,ArcComponentName>,Spec>;

export function Playground({name,notify,surface='base'}:{name:ComponentName;notify:(message:string)=>void;surface?:'base'|'canvas'|'raised'|'floating'}) {
 return Object.hasOwn(arcPlaygrounds,name)?<ArcPlayground name={name as ArcComponentName} notify={notify} surface={surface}/>:<BasePlayground name={name as Exclude<ComponentName,ArcComponentName>} notify={notify} surface={surface}/>;
}
function BasePlayground({name,notify,surface}:{name:Exclude<ComponentName,ArcComponentName>;notify:(message:string)=>void;surface:'base'|'canvas'|'raised'|'floating'}) {
 const translate=useCatalogText();
 const spec:Spec=playgrounds[name], id=useId();
 const icons=useIconCatalogue(name==='IconPicker'||spec.controls.some(control=>control.key==='icon'&&control.options));
 const initial=()=>Object.fromEntries(spec.controls.map(c=>[c.key,typeof c.initial==='string'&&!c.options&&!c.initial.includes('const count')?translate(c.initial):c.initial]));
 const [values,setValues]=useState<Values>(initial),[revision,setRevision]=useState(0);
 const set=(key:string,value:Value)=>setValues(previous=>({...previous,[key]:value}));
 return <section className="catalog-playground cap-surface-boundary" data-surface="canvas" data-component={name} aria-labelledby={`${id}-title`}>
  <div className="playground-layout">
   <div className="playground-preview" data-surface={surface} role="group" aria-label={`${name}: ${translate("Интерактивный пример")}`} key={revision}><h2 className="cap-sr-only">{translate("Интерактивный пример")}</h2>{spec.render(values,{set,notify:message=>notify(translate(message)),id,icons,t:translate})}</div>
   <div className="playground-settings" data-surface="raised">
    <header><h2 id={`${id}-title`}>{translate("Параметры")}</h2><UI.Button variant="ghost" size="sm" onClick={()=>{setValues(initial());setRevision(r=>r+1);}}>{translate("Сбросить")}</UI.Button></header>
    <div className="playground-controls" role="group" aria-label={`${translate("Параметры")} ${name}`}>
     <ControlList controls={spec.controls} render={control=>{
      if(typeof control.initial==='boolean')return <UI.Checkbox key={control.key} label={translate(control.label)} size="sm" checked={b(values,control.key)} onChange={e=>set(control.key,e.target.checked)}/>;
      if(typeof control.initial==='number')return <UI.NumberField key={control.key} label={translate(control.label)} compact size="sm" value={Number(values[control.key])} min={control.min} max={control.max} step={!Number.isInteger(control.initial)?.05:1} onValueChange={value=>set(control.key,value)}/>;
      if(typeof control.initial==='string' && control.initial.includes('\n'))return <UI.Textarea key={control.key} label={translate(control.label)} size="sm" rows={4} value={s(values,control.key)} onChange={e=>set(control.key,e.target.value)}/>;
      if(control.label==='Дата ISO'||control.key==='rangeEnd')return <UI.DatePicker key={control.key} label={translate(control.label)} value={s(values,control.key)} onValueChange={value=>set(control.key,value)}/>;
      return <UI.Field key={control.key} label={translate(control.label)}>{props=>control.key==='icon'&&control.options?<UI.IconPicker {...props} label={translate(control.label)} size="sm" variant="combobox" value={s(values,control.key)} options={icons} onValueChange={value=>set(control.key,value)}/>:control.options?<UI.Select {...props} size="sm" value={s(values,control.key)} options={control.options.map(value=>({value,label:translate(value)}))} onValueChange={value=>set(control.key,value)}/>:<UI.Input {...props} size="sm" value={s(values,control.key)} onChange={e=>set(control.key,e.target.value)}/>}</UI.Field>;
     }}/>
    </div>
   </div>
  </div>
 </section>;
}
