import { useCatalogText, localizeCatalogueFixture } from './catalog-locale';
import { useState } from 'react';
import * as UI from '../src';
import { StorySection, type StoryProps } from './stories-controls';
export function DialogStory({notify}:StoryProps){
 const ct=useCatalogText();
const [size,setSize]=useState<'sm'|'md'|'lg'|'xl'|null>(null),[title,setTitle]=useState(ct('Сад идей')),[long,setLong]=useState(false);return <><StorySection title={ct("Размеры")}><div className="catalog-row">{(['sm','md','lg','xl'] as const).map(value=><UI.Button key={value} onClick={()=>{setLong(false);setSize(value);}}>{ct("Открыть ")}{value}</UI.Button>)}</div></StorySection><StorySection title={ct("Длинное содержимое")}><UI.Button onClick={()=>{setLong(true);setSize('md');}}>{ct("Прокручиваемый диалог")}</UI.Button></StorySection><UI.Dialog open={size!==null} onOpenChange={open=>{if(!open)setSize(null);}} size={size??'md'} title={long?ct('Правила пространства'):ct('Новый проект')} description={long?undefined:ct('Название можно изменить позже.')} footer={<><UI.Button variant="ghost" onClick={()=>setSize(null)}>{ct("Отмена")}</UI.Button><UI.Button variant="primary" disabled={!long&&!title.trim()} onClick={()=>{setSize(null);notify(long?ct('Правила приняты'):`${ct("Создан «")}${title}»`);}}>{long?ct('Готово'):ct('Создать')}</UI.Button></>}>{long?<div className="catalog-stack">{Array.from({length:14},(_,index)=><p key={index}>{index+1}{ct(". Сохраняйте только полезное. Давайте заметкам понятные названия и связывайте идеи между собой.")}</p>)}</div>:<div className="catalog-stack"><UI.Input labelPlacement="inside" label={ct("Название проекта")} value={title} onChange={event=>setTitle(event.target.value)} data-autofocus/><UI.Field label={ct("Тип")}>{props=><UI.Select {...props} defaultValue="personal" options={[{value:'personal',label:ct('Личный проект')},{value:'work',label:ct('Рабочий проект')}]}/>}</UI.Field></div>}</UI.Dialog></>;}
export function DrawerStory({notify}:StoryProps){
 const ct=useCatalogText();
const [side,setSide]=useState<'left'|'right'|'bottom'|null>(null),[name,setName]=useState(ct('Тихое утро')),[variant,setVariant]=useState<'inset'|'edge'>('inset');return <StorySection><div className="catalog-row"><UI.SegmentedControl label={ct("Оформление Drawer")} value={variant} onValueChange={v=>setVariant(v as typeof variant)} options={[{value:"inset",label:ct("С отступами")},{value:"edge",label:ct("В край")}]}/><UI.Button onClick={()=>setSide('right')}>{ct("Справа")}</UI.Button><UI.Button onClick={()=>setSide('left')}>{ct("Слева")}</UI.Button><UI.Button onClick={()=>setSide('bottom')}>{ct("Снизу")}</UI.Button></div><UI.Drawer variant={variant} open={side!==null} onOpenChange={open=>{if(!open)setSide(null);}} side={side??'right'} title={ct("Свойства объекта")} description={ct("Изменения относятся к текущему объекту.")} footer={<><UI.Button variant="ghost" onClick={()=>setSide(null)}>{ct("Отмена")}</UI.Button><UI.Button variant="primary" onClick={()=>{setSide(null);notify(ct('Свойства сохранены'));}}>{ct("Сохранить")}</UI.Button></>}><div className="catalog-stack"><UI.Input labelPlacement="inside" label={ct("Название")} value={name} onChange={event=>setName(event.target.value)} data-autofocus/><UI.Field label={ct("Описание")}>{props=><UI.Textarea {...props} rows={5} placeholder={ct("О чём эта заметка?")}/>}</UI.Field><UI.Switch label={ct("Закрепить в пространстве")}/><UI.PropertyRow label={ct("Тип")}><UI.Tag color="blue">{ct("Заметка")}</UI.Tag></UI.PropertyRow></div></UI.Drawer></StorySection>;}
export function TooltipStory(){
 const ct=useCatalogText();
return <StorySection><div className="catalog-row catalog-tooltip-samples"><UI.Tooltip content={ct("Новая заметка")}><UI.IconButton label={ct("Новая заметка")} icon="plus"/></UI.Tooltip><UI.Tooltip content="Enter Focus Mode" shortcut={['⇧','⌘','M']}><UI.Button leading={<UI.Icon name="sparkle"/>}>Focus Mode</UI.Button></UI.Tooltip><UI.Tooltip caption={ct("Доступ")} content={ct("Приватный объект")} description={ct("Доступен только вам.")} variant="inverse" arrow><UI.Button variant="outline">{ct("Подробная подсказка")}</UI.Button></UI.Tooltip><UI.Tooltip content={ct("Скопировать ссылку")} shortcut={['⌘','L']}><UI.IconButton label={ct("Скопировать ссылку")} icon="external" variant="ghost"/></UI.Tooltip></div></StorySection>;}
export function MenuStory({notify}:StoryProps){
 const ct=useCatalogText();
const items:UI.MenuItem[]=[{id:'remove',label:ct('Убрать из коллекции'),icon:'close',onSelect:()=>notify(ct('Объект убран из коллекции'))},{id:'type',label:ct('Изменить тип'),icon:'layers',separator:true,onSelect:()=>notify(ct('Тип изменён'))},{id:'share',label:ct('Поделиться'),icon:'external',onSelect:()=>notify(ct('Ссылка подготовлена'))},{id:'export',label:ct('Экспорт'),icon:'arrow',onSelect:()=>notify(ct('Экспорт подготовлен'))},{id:'copy',label:ct('Копировать'),icon:'copy',shortcut:'⌘ C',separator:true,onSelect:()=>notify(ct('Копия создана'))},{id:'duplicate',label:ct('Дублировать'),icon:'copy',onSelect:()=>notify(ct('Объект дублирован'))},{id:'unavailable',label:ct('Недоступная команда'),disabled:true},{id:'delete',label:ct('Удалить объект'),icon:'trash',danger:true,onSelect:()=>notify(ct('Объект удалён в примере'))}];return <><StorySection title={ct("Действия объекта")}><div className="catalog-row"><UI.Menu label={ct("Открыть меню объекта")} items={items} variant="outline"/><UI.Menu label={ct("Короткое меню")} icon="down" items={items.slice(0,3)} variant="secondary"/><UI.Menu label={ct("Недоступное меню")} items={items} disabled/></div></StorySection><StorySection title={ct("У края контейнера")}><div className="catalog-edge-menu"><span>{ct("Меню остаётся в пределах окна")}</span><UI.Menu label={ct("Меню справа")} items={items}/></div></StorySection></>;}
export function PopoverStory(){
 const ct=useCatalogText();
const [open,setOpen]=useState(false),[accent,setAccent]=useState<UI.Color>('purple');return <><StorySection title={ct("Настройки рядом с действием")}><UI.Popover label={ct("Вид коллекции")}><div className="catalog-stack"><strong>{ct("Показывать в карточке")}</strong><UI.Switch label={ct("Обложку")} defaultChecked/><UI.Switch label={ct("Свойства")} defaultChecked/><UI.Switch label={ct("Описание")}/></div></UI.Popover></StorySection><StorySection title={ct("Управляемое закрытие")}><UI.Popover label={ct("Выбрать акцент")} open={open} onOpenChange={setOpen}><div className="catalog-stack"><strong>{ct("Акцент объекта")}</strong><div className="catalog-row">{(['blue','purple','teal','rose','amber'] as const).map(color=><UI.Button key={color} data-accent={color} variant={accent===color?'accent':'secondary'} onClick={()=>{setAccent(color);setOpen(false);}}>{color}</UI.Button>)}</div></div></UI.Popover></StorySection></>;}
export function CommandPaletteStory({notify}:StoryProps){
 const ct=useCatalogText();
const [open,setOpen]=useState(false);return <StorySection><UI.Button leading={<UI.Icon name="search"/>} onClick={()=>setOpen(true)}>{ct("Открыть поиск команд")}</UI.Button><UI.CommandPalette open={open} onOpenChange={setOpen} items={[{id:'new-note',label:ct('Новая заметка'),description:ct('Создать пустую страницу'),icon:'page',shortcut:'⌘ N',onSelect:()=>notify(ct('Заметка создана'))},{id:'new-project',label:ct('Новый проект'),description:ct('Собрать идеи в одном месте'),icon:'cube',onSelect:()=>notify(ct('Проект создан'))},{id:'calendar',label:ct('Открыть календарь'),description:ct('Задачи и события дня'),icon:'calendar',onSelect:()=>notify(ct('Календарь открыт'))},{id:'settings',label:ct('Настройки'),description:ct('Внешний вид и поведение'),icon:'settings',onSelect:()=>notify(ct('Настройки открыты'))} ]}/></StorySection>;}
