import { useState } from 'react';
import * as UI from '../src';
import { Sample, StorySection, type StoryProps } from './stories-controls';
const colorSamples: UI.Color[] = ['neutral','blue','purple','teal','rose','amber'];
export function BadgeStory() {return <><StorySection title="Варианты"><div className="catalog-row">{(['soft','solid','outline'] as const).map(variant=><Sample label={variant} key={variant}><UI.Badge variant={variant}>В работе</UI.Badge></Sample>)}</div></StorySection><StorySection title="Локальные моды"><div className="catalog-row">{colorSamples.map(color=><span data-accent={color} key={color}><UI.Badge>{color}</UI.Badge></span>)}</div></StorySection></>;}
export function TagStory() {const [tags,setTags]=useState(['Дизайн','Личное','Исследование']);return <><StorySection title="Метки"><div className="catalog-row">{colorSamples.map(color=><UI.Tag key={color} color={color}>{color}</UI.Tag>)}</div></StorySection><StorySection title="С удалением"><div className="catalog-row">{tags.map(tag=><UI.Tag key={tag} onRemove={()=>setTags(current=>current.filter(value=>value!==tag))}>{tag}</UI.Tag>)}{tags.length<3&&<UI.Button size="sm" variant="ghost" onClick={()=>setTags(['Дизайн','Личное','Исследование'])}>Вернуть метки</UI.Button>}</div></StorySection></>;}
export function TypeLabelStory(){return <StorySection><div className="catalog-row"><UI.TypeLabel icon="page">Заметка</UI.TypeLabel><UI.TypeLabel icon="book" color="purple">Книга</UI.TypeLabel><UI.TypeLabel icon="cube" color="teal">Проект</UI.TypeLabel><UI.TypeLabel icon="check" color="rose">Задача</UI.TypeLabel><UI.TypeLabel icon="heart" color="orange">Встреча</UI.TypeLabel></div></StorySection>;}
export function IconBoxStory(){return <><StorySection title="Размеры"><div className="catalog-row">{(['xs','sm','md','lg'] as const).map(size=><Sample key={size} label={size}><UI.IconBox icon="cube" size={size}/></Sample>)}</div></StorySection><StorySection title="Типы объектов"><div className="catalog-row">{colorSamples.map((color,index)=><UI.IconBox key={color} color={color} icon={(['page','book','cube','folder','check','sun'] as const)[index]}/>)}</div></StorySection></>;}
export function AvatarStory(){const image='data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="80" height="80" viewBox="0 0 80 80"%3E%3Crect width="80" height="80" fill="%23b8ccc3"/%3E%3Ccircle cx="40" cy="30" r="15" fill="%23576b60"/%3E%3Cpath d="M8 80a32 32 0 0 1 64 0" fill="%23576b60"/%3E%3C/svg%3E';return <><StorySection title="Инициалы"><div className="catalog-row">{(['xs','sm','md','lg'] as const).map(size=><Sample key={size} label={size}><UI.Avatar name="Анна Ким" size={size}/></Sample>)}</div></StorySection><StorySection title="Изображение"><div className="catalog-row"><UI.Avatar name="Профиль с изображением" src={image} size="lg"/><UI.Avatar name="Даша"/><UI.Avatar name="Илья Морозов"/></div></StorySection></>;}
export function SeparatorStory(){return <StorySection><div className="catalog-narrow"><p>Сведения о проекте</p><UI.Separator/><p>Связанные заметки</p><UI.Separator/><p>История изменений</p></div></StorySection>;}
export function CardStory(){return <StorySection title="Поверхности"><div className="catalog-cards">{(['default','subtle','elevated'] as const).map(variant=><UI.Card key={variant} variant={variant}><h3>{variant}</h3><p className="catalog-muted">Нейтральный контейнер для содержимого.</p></UI.Card>)}</div></StorySection>;}
export function ObjectCardStory({notify}:StoryProps){return <StorySection><div className="catalog-cards"><UI.ObjectCard title="Сад идей" description="Небольшие шаги к большому проекту." icon="cube" color="teal" meta={<UI.Tag color="teal">Личное</UI.Tag>} onClick={()=>notify('Открыт «Сад идей»')}/><UI.ObjectCard title="Визуальные системы" icon="book" color="purple" cover={<div className="catalog-object-cover"><UI.Icon name="book" size={34}/></div>} meta="12 заметок" onClick={()=>notify('Открыты «Визуальные системы»')}/><UI.ObjectCard title="Архив" description="Пример недоступной карточки." icon="folder" disabled/></div></StorySection>;}
export function CollectionRowStory({notify}:StoryProps){return <StorySection><div className="catalog-stack catalog-narrow"><UI.CollectionRow title="Сад идей" icon="cube" color="teal" meta={<UI.Tag color="teal">Проект</UI.Tag>} onClick={()=>notify('Открыт проект')}/><UI.CollectionRow title="Наблюдения" icon="page" color="blue" meta="Сегодня" onClick={()=>notify('Открыты наблюдения')}/><UI.CollectionRow title="Книги" icon="book" color="purple" onClick={()=>notify('Открыта коллекция книг')}/><UI.CollectionRow title="Архив недоступен" icon="folder" disabled/></div></StorySection>;}
export function PropertyRowStory(){return <StorySection><div className="catalog-narrow"><UI.PropertyRow label="Статус" icon="check"><UI.Tag color="green">В работе</UI.Tag></UI.PropertyRow><UI.PropertyRow label="Автор" icon="page"><span className="catalog-inline"><UI.Avatar name="Анна Ким" size="xs"/>Анна Ким</span></UI.PropertyRow><UI.PropertyRow label="Теги" icon="tag"><UI.Tag color="purple">Исследование</UI.Tag> <UI.Tag color="blue">UI</UI.Tag></UI.PropertyRow><UI.PropertyRow label="Обновлено" icon="calendar">Сегодня</UI.PropertyRow><UI.PropertyRow label="Описание">Значение свойства может занимать несколько строк и переноситься в пределах контейнера.</UI.PropertyRow></div></StorySection>;}
export function TableStory(){return <StorySection><UI.Table caption="Объекты коллекции" columns={['Название','Тип','Статус','Обновлено']} rows={[[<span className="catalog-inline"><UI.IconBox icon="cube" color="teal" size="xs"/>Сад идей</span>,'Проект',<UI.Tag color="green">В работе</UI.Tag>,'Сегодня'],['Тихое утро','Заметка',<UI.Tag>Черновик</UI.Tag>,'Вчера'],['Визуальные системы','Книга',<UI.Tag color="purple">В планах</UI.Tag>,'2 октября']]}/></StorySection>;}
export function CodeBlockStory(){return <><StorySection title="Исходный код"><UI.CodeBlock label="App.tsx">{'import { Button } from "@personal/capacities-ui";\n\nexport function App() {\n  return <Button variant="primary">Создать</Button>;\n}'}</UI.CodeBlock></StorySection><StorySection title="Длинная строка"><UI.CodeBlock label="CSS">{':root { --cap-font-sans: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }'}</UI.CodeBlock></StorySection></>;}
export const markdownExample='## Место для идей\n\nНебольшие шаги помогают **двигаться дальше**. Оставьте место для *новых наблюдений*.\n\n- [x] Собрать референсы\n- [ ] Настроить цвета\n- [ ] Выпустить первую версию\n\n> Меньше шума, больше смысла.\n\nИспользуйте `data-accent="teal"` для локального акцента.\n\n[Документация](https://capacities.io)\n\n```tsx\n<Button variant="accent">Создать</Button>\n```';
export function MarkdownPreviewStory(){return <><StorySection title="Форматированный текст"><UI.MarkdownPreview value={markdownExample} className="catalog-reading"/></StorySection><StorySection title="Пустое содержимое"><UI.MarkdownPreview value=""/></StorySection></>;}
export function MarkdownEditorStory({notify}:StoryProps){const [text,setText]=useState(markdownExample);return <><StorySection title="Редактирование и предпросмотр"><UI.MarkdownEditor label="Заметка проекта" value={text} onValueChange={setText} defaultMode="split" onSave={()=>notify('Заметка сохранена в состоянии примера')}/></StorySection><StorySection title="Только чтение"><UI.MarkdownEditor label="Заметка только для чтения" value="Содержимое этого блока можно прочитать и скопировать." onValueChange={()=>{}} readOnly/></StorySection></>;}
export function ContentCardStory({notify}:StoryProps){const [selected,setSelected]=useState(false),[cover,setCover]=useState(true),[compact,setCompact]=useState(false);return <><StorySection><div className="catalog-row catalog-story-controls"><UI.Switch label="Обложка" checked={cover} onChange={event=>setCover(event.target.checked)}/><UI.Switch label="Компактная" checked={compact} onChange={event=>setCompact(event.target.checked)}/></div><div className="catalog-cards"><UI.ContentCard title="Сад идей" description="Личная коллекция наблюдений и небольших проектов." data-accent="teal" density={compact?'compact':'comfortable'} selected={selected} onSelectedChange={setSelected} onOpen={()=>notify('Проект открыт')} cover={cover?<UI.IconBox icon="cube" color="teal" size="lg"/>:undefined} header={<UI.TypeLabel icon="cube" color="teal">Проект</UI.TypeLabel>} actions={<UI.Menu label="Действия проекта" items={[{id:'copy',label:'Дублировать',icon:'copy',onSelect:()=>notify('Проект дублирован')} ]}/>} metadata="Обновлено сегодня" footer={<><UI.Avatar name="Анна Ким" size="xs"/><UI.Tag color="teal">Личное</UI.Tag></>}/><UI.ContentCard title="Референсы" description="Слоты заголовка, свойств и действий независимы." density={compact?'compact':'comfortable'} orientation="horizontal" cover={cover?<UI.IconBox icon="book" color="purple" size="lg"/>:undefined} footer={<UI.Button variant="outline" size="sm" onClick={()=>notify('Референс добавлен')}>Добавить</UI.Button>}/></div></StorySection></>;}
export function TaskCardStory({notify}:StoryProps){const [done,setDone]=useState(false);return <StorySection><div className="catalog-cards"><UI.TaskCard title="Настроить цветовые моды" completed={done} onCompletedChange={setDone} onOpen={()=>notify('Задача открыта')} menuItems={[{id:'copy',label:'Дублировать',icon:'copy',onSelect:()=>notify('Задача дублирована')},{id:'delete',label:'Удалить',icon:'trash',danger:true,onSelect:()=>notify('Задача удалена в примере')}]} metadata={<><UI.Icon name="calendar" size={13}/><span>Сегодня</span><UI.Icon name="tag" size={13}/></>} footer={<UI.TypeLabel icon="cube" color="teal">UI-kit</UI.TypeLabel>}/><UI.TaskCard title="Собрать референсы" completed onCompletedChange={()=>notify('Это пример завершённой задачи')} footer={<UI.Tag color="purple">Исследование</UI.Tag>}/></div></StorySection>;}
export function KanbanColumnStory({notify}:StoryProps){return <StorySection><div className="catalog-columns"><UI.KanbanColumn title="В работе" count={2} action={<UI.IconButton label="Добавить в колонку" icon="plus" variant="ghost" size="sm" onClick={()=>notify('Задача добавлена в примере')}/>}><UI.TaskCard title="Наметить первый шаг"/><UI.TaskCard title="Собрать идеи"/></UI.KanbanColumn><UI.KanbanColumn title="Готово" count={0} emptyState={<UI.EmptyState title="Пока нет задач" description="Завершённые карточки появятся здесь."/>}/></div></StorySection>;}
export function KanbanBoardStory(){const [items,setItems]=useState<UI.KanbanTask[]>([{id:'first',columnId:'inbox',title:'Собрать идеи',color:'rose'},{id:'second',columnId:'active',title:'Продумать первую версию',color:'teal'}]);const [empty,setEmpty]=useState(false);const columns=[{id:'inbox',title:'Входящие'},{id:'active',title:'В работе'},{id:'done',title:'Готово'}];return <StorySection><div className="catalog-story-controls"><UI.Switch label="Пустая доска" checked={empty} onChange={event=>setEmpty(event.target.checked)}/></div><UI.KanbanBoard label="Задачи проекта" columns={columns} items={empty?[]:items} onMove={(id,columnId)=>setItems(current=>current.map(item=>item.id===id?{...item,columnId,completed:columnId==='done'}:item))} onCompletedChange={(id,completed)=>setItems(current=>current.map(item=>item.id===id?{...item,completed}:item))} onAdd={columnId=>{const id=crypto.randomUUID();setEmpty(false);setItems(current=>[...current,{id,columnId,title:'Новая задача'}]);}}/></StorySection>;}
export function DailyHeaderStory(){const [date,setDate]=useState('2026-09-25');return <><StorySection title="Дата и типы объектов"><UI.DailyHeader date={date} tags={<><UI.TypeLabel icon="check" color="rose">Task</UI.TypeLabel><UI.TypeLabel icon="heart" color="orange">Meeting</UI.TypeLabel><UI.TypeLabel icon="cube" color="teal">Project</UI.TypeLabel></>} actions={<UI.DatePicker label="День" value={date} onValueChange={setDate} today="2026-09-25"/>}/></StorySection><StorySection title="Без номера недели"><UI.DailyHeader date="2026-10-04" showWeek={false} locale="en-US"/></StorySection></>;}
