import { useCatalogText, localizeCatalogueFixture } from './catalog-locale';
import { scheduleEvents, CalendarSchedule } from '../examples/CalendarSchedule';
import { FieldFamily } from './FieldFamily';
import { useId, useState, type ReactNode } from 'react';
import * as UI from '../src';
export interface StoryProps { notify: (message: string) => void }
export function StorySection({ title, children, className = '' }: { title?: string; children: ReactNode; className?: string }) {
 const ct=useCatalogText();

  return <section className={`catalog-story ${className}`}><h2 className={title ? undefined : "cap-sr-only"}>{title ? ct(title) : ct("Пример")}</h2><div className="catalog-story-content">{children}</div></section>;
}
export function Sample({ label, children }: { label: string; children: ReactNode }) {
 const ct=useCatalogText();
 return <div className="catalog-sample"><div>{children}</div><span>{ct(label)}</span></div>; }
const sizes = ['xs', 'sm', 'md', 'lg', 'xl'] as const;
export function ButtonStory({ notify }: StoryProps) {
 const ct=useCatalogText();

  return <><StorySection title={ct("Варианты")}><div className="catalog-row">{(['primary', 'secondary', 'outline', 'ghost', 'accent', 'accent-secondary', 'danger'] as const).map(variant => <Sample label={variant} key={variant}><UI.Button variant={variant} onClick={() => notify(`${ct("Действие: ")}${variant}`)}>{variant === 'danger' ? ct('Удалить') : ct('Сохранить')}</UI.Button></Sample>)}</div></StorySection><StorySection title={ct("Размеры")}><div className="catalog-row">{sizes.map(size => <Sample key={size} label={size}><UI.Button size={size} onClick={() => notify(`${ct("Размер ")}${size}`)}>{ct("Кнопка")}</UI.Button></Sample>)}</div></StorySection><StorySection title={ct("Иконки и состояния")}><div className="catalog-row"><UI.Button leading={<UI.Icon name="plus" />} onClick={() => notify(ct('Новый объект создан'))}>{ct("Создать")}</UI.Button><UI.Button trailing={<UI.Icon name="arrow" />} onClick={() => notify(ct('Следующий шаг'))}>{ct("Продолжить")}</UI.Button><UI.Button disabled>{ct("Недоступно")}</UI.Button><UI.Button loading>{ct("Сохраняем")}</UI.Button></div></StorySection></>;
}
export function IconButtonStory({ notify }: StoryProps) {
 const ct=useCatalogText();
 return <><StorySection title={ct("Варианты")}><div className="catalog-row">{(['secondary', 'outline', 'ghost', 'primary', 'accent', 'accent-secondary', 'danger'] as const).map(variant => <Sample key={variant} label={variant}><UI.IconButton label={`${ct("Поиск: ")}${variant}`} icon="search" variant={variant} onClick={() => notify(ct('Открыт поиск'))} /></Sample>)}</div></StorySection><StorySection title={ct("Размеры и состояния")}><div className="catalog-row">{sizes.map(size => <Sample key={size} label={size}><UI.IconButton label={`${ct("Добавить: ")}${size}`} icon="plus" size={size} onClick={() => notify(ct('Объект добавлен'))} /></Sample>)}<Sample label="disabled"><UI.IconButton icon="trash" label={ct("Удаление недоступно")} disabled /></Sample><Sample label="loading"><UI.IconButton icon="copy" label={ct("Копируем")} loading /></Sample></div></StorySection></>; }
export function IconStory() {
 const ct=useCatalogText();
 const names: UI.IconName[] = ['plus','search','close','check','chevron','down','menu','grid','page','book','cube','calendar','sun','moon','settings','copy','arrow','external','code','folder','tag','sparkle','info','warning','trash','more','filter','list','clock','layers','heart','minus','sort','microphone']; return <><StorySection><div className="catalog-icon-grid">{names.map(name => <Sample key={name} label={name}><UI.Icon name={name} size={20} /></Sample>)}</div></StorySection><StorySection title={ct("Размер")}><div className="catalog-row">{[12,16,20,24].map(size => <Sample key={size} label={`${size} px`}><UI.Icon name="cube" size={size} /></Sample>)}</div></StorySection></>; }
export function ButtonGroupStory({notify}:StoryProps) {
 const ct=useCatalogText();

 const [view,setView]=useState('list');
 return <><StorySection title={ct("Счётчик и представление")}><UI.ButtonGroup label={ct("Представление коллекции")} prefix="99+">
 <UI.Tooltip content="Filter"><UI.IconButton label={ct("Фильтр")} icon="filter" variant="ghost" onClick={()=>notify(ct('Фильтр применён'))}/></UI.Tooltip>
 <UI.Tooltip content={ct("Сортировка")}><UI.IconButton label={ct("Сортировка")} icon="sort" variant="ghost" onClick={()=>notify(ct('Порядок изменён'))}/></UI.Tooltip>
 <UI.IconButton label={ct("Таблица")} icon="table" variant="ghost" aria-pressed={view==='table'} onClick={()=>setView('table')}/>
 <UI.Button variant="ghost" aria-label={ct("Выбрать представление")} leading={<UI.Icon name="list" size={14}/>} trailing={<UI.Icon name="down" size={12}/>} onClick={()=>setView('list')}/>
 <UI.Tooltip content={ct("Настроить представление")}><UI.IconButton label={ct("Настройки представления")} icon="sliders" variant="ghost" onClick={()=>notify(ct('Настройки представления'))}/></UI.Tooltip>
 </UI.ButtonGroup></StorySection><StorySection title={ct("Объединённые селекты")}><UI.ButtonGroup label={ct("Параметры списка")}><UI.Select aria-label={ct("Порядок")} options={[{value:"recent",label:ct("Сначала новые")},{value:"old",label:ct("Сначала старые")}]}/><UI.Select aria-label={ct("Группировка")} options={[{value:"month",label:ct("По месяцам")},{value:"year",label:ct("По годам")}]}/></UI.ButtonGroup></StorySection><StorySection title={ct("Размеры и состояния")}><div className="catalog-stack">{sizes.map(size=><div className="catalog-row" key={size}><span className="muted">{size}</span><UI.ButtonGroup label={`${ct("Группа ")}${size}`} size={size} prefix="99+"><UI.IconButton icon="filter" label={`${ct("Фильтр ")}${size}`} variant="ghost"/><UI.IconButton icon="list" label={`${ct("Список ")}${size}`} variant="ghost"/><UI.IconButton icon="sliders" label={`${ct("Настройки ")}${size}`} variant="ghost" disabled/></UI.ButtonGroup></div>)}</div></StorySection><StorySection title={ct("Раздельная и вертикальная группы")}><div className="catalog-row"><UI.ButtonGroup label={ct("История")} attached={false}><UI.Button onClick={()=>notify(ct('Предыдущая версия'))}>{ct("Назад")}</UI.Button><UI.Button onClick={()=>notify(ct('Следующая версия'))}>{ct("Вперёд")}</UI.Button></UI.ButtonGroup><UI.ButtonGroup label={ct("Масштаб")} orientation="vertical"><UI.IconButton label={ct("Увеличить")} icon="plus"/><UI.IconButton label={ct("Уменьшить")} icon="minus"/></UI.ButtonGroup></div></StorySection></>;
}

export function SplitButtonStory({ notify }: StoryProps) {
 const ct=useCatalogText();
 const items: UI.MenuItem[] = [{id:'note',label:ct('Новая заметка'),icon:'page',onSelect:()=>notify(ct('Заметка создана'))},{id:'project',label:ct('Новый проект'),icon:'cube',onSelect:()=>notify(ct('Проект создан'))},{id:'template',label:ct('Из шаблона'),icon:'copy',separator:true,onSelect:()=>notify(ct('Объект создан из шаблона'))}]; return <><StorySection title={ct("Основное действие и меню")}><div className="catalog-row"><UI.SplitButton label={ct("Создать")} leading={<UI.Icon name="plus"/>} items={items} onClick={()=>notify(ct('Объект создан'))} /><UI.SplitButton label={ct("Экспорт")} variant="secondary" items={[{id:'md',label:'Markdown',onSelect:()=>notify(ct('Выбран Markdown'))},{id:'json',label:'JSON',onSelect:()=>notify(ct('Выбран JSON'))}]} onClick={()=>notify(ct('Экспорт подготовлен'))} /><UI.SplitButton label={ct("Создать")} variant="accent" items={items} onClick={()=>notify(ct('Объект создан'))} /></div></StorySection><StorySection title={ct("Раздельные действия")}><div className="catalog-row"><UI.SplitButton label={ct("Создать")} layout="separated" leading={<UI.Icon name="plus"/>} items={items} onClick={()=>notify(ct('Объект создан'))}/><UI.SplitButton label={ct("Экспорт")} layout="separated" variant="secondary" items={items} onClick={()=>notify(ct('Экспорт подготовлен'))}/></div></StorySection><StorySection title={ct("Состояния")}><div className="catalog-row"><UI.SplitButton label={ct("Недоступно")} items={items} disabled /><UI.SplitButton label={ct("Создаём")} items={items} loading /></div></StorySection></>; }
export function ActionBarStory({ notify }: StoryProps) {
 const ct=useCatalogText();
 const [view,setView]=useState('grid'); return <><StorySection title={ct("Составная панель")}><UI.ActionBar label={ct("Смешанная панель")}><UI.ButtonGroup label={ct("Вид коллекции")} prefix={12}><UI.IconButton label={ct("Фильтровать")} icon="filter" variant="ghost" onClick={()=>notify(ct('Фильтр применён'))}/><UI.IconButton label={ct("Список объектов")} icon="list" variant="ghost"/><UI.IconButton label={ct("Сетка объектов")} icon="grid" aria-pressed variant="secondary"/></UI.ButtonGroup><span style={{flex:1}}/><UI.Popover label={ct("Поиск")}><UI.Input aria-label={ct("Поиск объектов")} placeholder={ct("Название объекта")}/></UI.Popover><UI.SplitButton label={ct("Создать")} leading={<UI.Icon name="plus"/>} onClick={()=>notify(ct('Заметка создана'))} items={[{id:'note',label:ct('Заметка'),onSelect:()=>notify(ct('Заметка создана'))},{id:'project',label:ct('Проект'),onSelect:()=>notify(ct('Проект создан'))}]}/></UI.ActionBar></StorySection><StorySection title={ct("Панель коллекции")}><UI.ActionBar label={ct("Инструменты коллекции")}><UI.IconButton icon="filter" label={ct("Фильтр")} variant="ghost" onClick={()=>notify(ct('Фильтр применён'))} /><UI.IconButton icon="sort" label={ct("Сортировка")} variant="ghost" onClick={()=>notify(ct('Порядок изменён'))} /><UI.IconButton icon="grid" label={ct("Карточки")} variant={view==='grid'?'secondary':'ghost'} aria-pressed={view==='grid'} onClick={()=>setView('grid')} /><UI.IconButton icon="list" label={ct("Список")} variant={view==='list'?'secondary':'ghost'} aria-pressed={view==='list'} onClick={()=>setView('list')} /><UI.Menu label={ct("Действия коллекции")} items={[{id:'copy',label:ct('Дублировать'),icon:'copy',onSelect:()=>notify(ct('Коллекция дублирована'))},{id:'delete',label:ct('Удалить'),icon:'trash',danger:true,onSelect:()=>notify(ct('Коллекция удалена в примере'))}]} /></UI.ActionBar></StorySection><StorySection title={ct("Вертикальная панель")}><UI.ActionBar label={ct("Инструменты редактора")} orientation="vertical"><UI.IconButton label={ct("Текст")} icon="page" variant="ghost" onClick={()=>notify(ct('Режим текста'))} /><UI.IconButton label={ct("Код")} icon="code" variant="ghost" onClick={()=>notify(ct('Режим кода'))} /><UI.IconButton label={ct("Ссылка")} icon="external" variant="ghost" onClick={()=>notify(ct('Ссылка добавлена'))} /></UI.ActionBar></StorySection></>; }
export function FloatingActionBarStory({ notify }: StoryProps) {
 const ct=useCatalogText();

 const [period,setPeriod]=useState('week'),[view,setView]=useState('board');
 const controls=<><UI.IconButton label={ct("Документ")} icon="page" variant="ghost" onClick={()=>notify(ct('Документ открыт'))}/><UI.IconButton label={ct("Настройки")} icon="sliders" variant="ghost" onClick={()=>notify(ct('Настройки открыты'))}/></>;
 return <><StorySection title={ct("Размеры и действия")}><div className="catalog-floating-sizes">{(['sm','md','lg','xl'] as const).map(size=><div className="catalog-floating-example" key={size}><span className="catalog-muted">{size}</span><UI.FloatingActionBar label={`${ct("Действия ")}${size}`} position="static" size={size} leading={<UI.Counter value="99+" variant="plain" size={size==='xl'?'lg':size}/>} trailing={<UI.Button variant="accent" onClick={()=>notify(ct('Заметка сохранена'))}>{ct("Сохранить")}</UI.Button>}>{controls}</UI.FloatingActionBar></div>)}</div></StorySection>
 <StorySection title={ct("Секции и разделители")}><div className="catalog-row"><UI.FloatingActionBar label={ct("Параметры представления")} position="static" size="sm" variant="divided" action={{label:ct('Применить'),icon:'check',variant:'accent',onClick:()=>notify(`${ct("Параметры: ")}${period}, ${view}`)}}><UI.Select aria-label={ct("Период")} variant="ghost" size="sm" style={{width:108,maxWidth:'100%'}} value={period} onValueChange={setPeriod} options={[{value:'week',label:ct('Неделя')},{value:'month',label:ct('Месяц')}]}/><UI.Select aria-label={ct("Вид")} variant="ghost" size="sm" style={{width:108,maxWidth:'100%'}} value={view} onValueChange={setView} options={[{value:'board',label:ct('Доска')},{value:'list',label:ct('Список')}]}/></UI.FloatingActionBar><UI.FloatingActionBar label={ct("Вертикальные действия")} position="static" size="sm" variant="divided" orientation="vertical" action={{label:ct('Готово'),icon:'check',variant:'accent',onClick:()=>notify(ct('Изменения применены'))}}><UI.IconButton label={ct("Добавить")} icon="plus" variant="ghost" onClick={()=>notify(ct('Добавлен блок'))}/><UI.IconButton label={ct("Настройки")} icon="sliders" variant="ghost" onClick={()=>notify(ct('Открыты настройки'))}/></UI.FloatingActionBar></div></StorySection>
 <StorySection title={ct("Поверх прокручиваемой области")}><UI.ScrollArea label={ct("Область с плавающей панелью")} style={{height:280}} floating={<UI.FloatingActionBar label={ct("Действия заметки")} position="static" size="lg" trailing={<UI.Button variant="accent" onClick={()=>notify(ct('Заметка сохранена'))}>{ct("Сохранить")}</UI.Button>}><UI.IconButton icon="copy" label={ct("Копировать")} variant="ghost" onClick={()=>notify(ct('Копия создана'))}/><UI.IconButton icon="more" label={ct("Ещё действия")} variant="ghost" onClick={()=>notify(ct('Действия заметки'))}/></UI.FloatingActionBar>}><div className="catalog-long-note"><h3>{ct("Заметки на полях")}</h3>{Array.from({length:8},(_,i)=><p key={i}>{ct("Мысль ")}{i+1}{ct(". Оставить немного места для следующего шага.")}</p>)}</div></UI.ScrollArea></StorySection></>;
}

export function KbdStory() {
 const ct=useCatalogText();
 return <StorySection><div className="catalog-row"><Sample label={ct("Комбинация")}><span className="catalog-inline"><UI.Kbd>⌘</UI.Kbd><UI.Kbd>K</UI.Kbd></span></Sample><Sample label={ct("Закрыть")}><UI.Kbd>esc</UI.Kbd></Sample><Sample label={ct("Перейти")}><UI.Kbd>↵</UI.Kbd></Sample><Sample label={ct("Навигация")}><span className="catalog-inline"><UI.Kbd>↑</UI.Kbd><UI.Kbd>↓</UI.Kbd></span></Sample></div></StorySection>; }
export function InputStory() {
 const ct=useCatalogText();
 return <><StorySection title={ct("Текст и поиск")}><div className="catalog-fields"><UI.Input aria-label={ct("Название")} placeholder={ct("Название проекта")}/><UI.Input aria-label={ct("Поиск")} type="search" placeholder={ct("Найти заметку…")}/><UI.Input aria-label={ct("Пароль")} type="password" defaultValue="quiet-morning"/></div></StorySection><StorySection title={ct("Размеры")}><div className="catalog-fields">{sizes.map(size=><UI.Input key={size} size={size} aria-label={`${ct("Поле ")}${size}`} placeholder={`${ct("Размер ")}${size}`}/>)}</div></StorySection><StorySection title={ct("Состояния")}><div className="catalog-fields"><UI.Input aria-label={ct("Только чтение")} value={ct("Только для чтения")} readOnly/><UI.Input aria-label={ct("Недоступное поле")} value={ct("Недоступно")} disabled/><UI.Input aria-label={ct("Ошибка")} aria-invalid="true" defaultValue={ct("Некорректное значение")}/></div></StorySection><StorySection title={ct("Общее положение подписи")}><FieldFamily/></StorySection></>; }
export function TextareaStory() {
 const ct=useCatalogText();
 return <><StorySection title={ct("Многострочный ввод")}><div className="catalog-fields"><UI.Textarea aria-label={ct("Описание проекта")} rows={4} placeholder={ct("О чём этот проект?")}/><UI.Textarea aria-label={ct("Заметка")} rows={3} defaultValue={ct("Несколько мыслей, к которым хочется вернуться.")}/></div></StorySection><StorySection title={ct("Состояния")}><div className="catalog-fields"><UI.Textarea aria-label={ct("Недоступное описание")} rows={3} disabled defaultValue={ct("Поле временно недоступно")}/><UI.Textarea aria-label={ct("Описание с ошибкой")} rows={3} aria-invalid="true" defaultValue={ct("Слишком коротко")}/></div></StorySection><StorySection title={ct("Общее положение подписи")}><FieldFamily/></StorySection></>; }
export function SelectStory() {
 const ct=useCatalogText();
 const [value,setValue]=useState('project');const options=[{value:'project',label:ct('Проект'),group:ct('Объекты')},{value:'note',label:ct('Заметка'),group:ct('Объекты')},{value:'book',label:ct('Книга'),group:ct('Коллекции')},{value:'locked',label:ct('Архив'),disabled:true,group:ct('Коллекции')}];return <><StorySection title={ct("Выбор и группы")}><div className="catalog-fields"><UI.Select aria-label={ct("Тип объекта")} value={value} onValueChange={setValue} options={options}/><UI.Select aria-label={ct("Пустой выбор")} placeholder={ct("Выберите тип")} defaultValue=""><option value="" disabled>{ct("Выберите тип")}</option><option value="note">{ct("Заметка")}</option><option value="project">{ct("Проект")}</option></UI.Select></div></StorySection><StorySection title={ct("Размеры")}><div className="catalog-fields">{sizes.map(size=><UI.Select aria-label={`${ct("Выбор ")}${size}`} key={size} size={size} defaultValue="project" options={options}/>)}</div></StorySection><StorySection title={ct("Состояния")}><div className="catalog-fields"><UI.Select aria-label={ct("Недоступный выбор")} disabled defaultValue="project" options={options}/><UI.Select aria-label={ct("Выбор с ошибкой")} aria-invalid="true" defaultValue="note" options={options}/></div></StorySection><StorySection title={ct("Общее положение подписи")}><FieldFamily/></StorySection></>; }
export function FieldStory({notify}:StoryProps) {
 const ct=useCatalogText();
const [name,setName]=useState(''),[sent,setSent]=useState(false); return <><StorySection title={ct("Подпись и подсказка")}><div className="catalog-fields"><UI.Field label={ct("Название")} hint={ct("Короткое имя, которое легко найти")}>{props=><UI.Input {...props} placeholder={ct("Сад идей")}/>}</UI.Field><UI.Field label={ct("Описание")} hint={ct("Необязательное поле")}>{props=><UI.Textarea {...props} rows={3}/>}</UI.Field></div></StorySection><StorySection title={ct("Проверка формы")}><form className="catalog-stack catalog-narrow" noValidate onSubmit={event=>{event.preventDefault();setSent(true);if(name.trim())notify(`${ct("Сохранено: ")}${name}`);}}><UI.Field label={ct("Название проекта")} required error={sent&&!name.trim()?ct('Введите название'):undefined}>{props=><UI.Input {...props} value={name} onChange={event=>setName(event.target.value)}/>}</UI.Field><UI.Button type="submit" variant="primary">{ct("Сохранить")}</UI.Button></form></StorySection></>; }
export function CheckboxStory() {
 const ct=useCatalogText();
const [all,setAll]=useState(false);return <><StorySection title={ct("Размеры")}><div className="catalog-row">{sizes.map(size=><UI.Checkbox key={size} size={size} label={size} defaultChecked/>)}</div></StorySection><StorySection title={ct("Состояния")}><div className="catalog-stack catalog-narrow"><UI.Checkbox label={ct("Показывать заметки")} defaultChecked/><UI.Checkbox label={ct("Добавить в избранное")}/><UI.Checkbox label={ct("Выбрать всё")} checked={all} indeterminate={!all} onChange={e=>setAll(e.target.checked)}/><UI.Checkbox label={ct("Недоступный выбор")} disabled/><UI.Checkbox label={ct("Выбрано и недоступно")} disabled defaultChecked/></div></StorySection></>; }
export function RadioStory() {
 const ct=useCatalogText();
const name=useId();return <><StorySection title={ct("Размеры")}><div className="catalog-row">{sizes.map(size=><UI.Radio key={size} size={size} name={`${name}-${size}`} label={size} defaultChecked/>)}</div></StorySection><StorySection title={ct("Выбор доступа")}><fieldset className="catalog-fieldset"><legend>{ct("Кто видит проект")}</legend><UI.Radio name={name} label={ct("Только я")} value="private" defaultChecked/><UI.Radio name={name} label={ct("По ссылке")} value="link"/><UI.Radio name={name} label={ct("Публичный доступ")} value="public" disabled/></fieldset></StorySection></>; }

export function SwitchStory() {
 const ct=useCatalogText();
const [enabled,setEnabled]=useState(true);return <><StorySection title={ct("Единый Primary")}><div className="catalog-row"><UI.Button variant="primary" onClick={()=>setEnabled(value=>!value)}>{ct("Переключить")}</UI.Button><UI.Checkbox label={ct("Выбор")} checked={enabled} onChange={event=>setEnabled(event.target.checked)}/><UI.Radio label={ct("Выбрано")} name="primary-comparison" checked={enabled} onChange={()=>setEnabled(true)}/><UI.Switch label={ct("Настройка")} checked={enabled} onChange={event=>setEnabled(event.target.checked)}/></div></StorySection><StorySection title={ct("Размеры")}><div className="catalog-row">{sizes.map(size=><UI.Switch key={size} label={size} size={size} defaultChecked/>)}</div></StorySection><StorySection title={ct("Состояния")}><div className="catalog-stack catalog-narrow"><UI.Switch label="Primary" defaultChecked/><UI.Switch label={ct("Vivid — явный выбор")} contrast={false} defaultChecked/><UI.Switch label={ct("Нейтральный")} variant="neutral" defaultChecked/><UI.Switch label={ct("Выключен")}/><UI.Switch label={ct("Недоступная настройка")} disabled/><UI.Switch label={ct("Всегда включено")} defaultChecked disabled/></div></StorySection></>; }
export function SliderStory() {
 const ct=useCatalogText();
const [value,setValue]=useState(48);return <><StorySection title={ct("Размеры")}><div className="catalog-fields">{sizes.map(size=><UI.Slider key={size} size={size} label={`${ct("Размер ")}${size}`} defaultValue={45}/>)}</div></StorySection><StorySection title={ct("Плотность и диапазон")}><div className="catalog-fields"><UI.Slider label={ct("Плотность")} value={value} min={0} max={100} onChange={event=>setValue(Number(event.target.value))}/><UI.Slider label={ct("Шаг 10")} defaultValue={30} min={0} max={100} step={10}/><UI.Slider label={ct("Недоступно")} defaultValue={65} disabled/></div></StorySection></>; }

export function SegmentedControlStory() {
 const ct=useCatalogText();
const [view,setView]=useState('grid'),[period,setPeriod]=useState('week');return <><StorySection title={ct("Представление")}><UI.SegmentedControl label={ct("Представление")} value={view} onValueChange={setView} options={[{value:'grid',label:ct('Карточки'),icon:<UI.Icon name="grid"/>},{value:'list',label:ct('Список'),icon:<UI.Icon name="list"/>},{value:'table',label:ct('Таблица'),disabled:true}]}/></StorySection><StorySection title={ct("Период")}><UI.SegmentedControl label={ct("Период")} value={period} onValueChange={setPeriod} options={[{value:'day',label:ct('День')},{value:'week',label:ct('Неделя')},{value:'month',label:ct('Месяц')}]}/></StorySection></>; }
export function CalendarStory() {
 const ct=useCatalogText();

 const [date,setDate]=useState('2026-10-07'),[range,setRange]=useState<UI.CalendarRange|undefined>({start:'2026-10-28',end:'2026-11-03'});
 return <><StorySection title={ct("Два месяца и период")}><UI.Calendar label={ct("Период проекта")} mode="range" range={range} onRangeChange={setRange} today="2026-10-07" events={localizeCatalogueFixture(scheduleEvents,ct)} highlightedDates={[{date:'2026-10-09',label:ct('Срок передачи'),color:'orange'}]} /></StorySection>
 <StorySection title={ct("События и поверхности")}><CalendarSchedule /></StorySection>
 <StorySection title={ct("Недоступные даты")}><UI.Calendar label={ct("Календарь с ограничениями")} value={date} onValueChange={setDate} today="2026-10-07" min="2026-10-01" max="2026-10-31" isDateUnavailable={day=>['2026-10-10','2026-10-11'].includes(day)}/></StorySection></>;
}
export function DatePickerStory() {
 const ct=useCatalogText();

 const [date,setDate]=useState<string>(),[range,setRange]=useState<UI.CalendarRange|undefined>();
 return <StorySection><div className="catalog-row"><UI.DatePicker label={ct("Выбрать дату")} value={date} onValueChange={setDate} today="2026-10-07" defaultMonth="2026-10" events={localizeCatalogueFixture(scheduleEvents,ct)} showAgenda/><UI.DatePicker label={ct("Выбрать период")} mode="range" range={range} onRangeChange={setRange} today="2026-10-07" defaultMonth="2026-10" events={localizeCatalogueFixture(scheduleEvents,ct)}/></div></StorySection>;
}
