import { scheduleEvents, CalendarSchedule } from '../examples/CalendarSchedule';
import { FieldFamily } from './FieldFamily';
import { useId, useState, type ReactNode } from 'react';
import * as UI from '../src';
export interface StoryProps { notify: (message: string) => void }
export function StorySection({ title, children, className = '' }: { title?: string; children: ReactNode; className?: string }) {
  return <section className={`catalog-story ${className}`}><h2 className={title ? undefined : "cap-sr-only"}>{title ?? "Пример"}</h2><div className="catalog-story-content">{children}</div></section>;
}
export function Sample({ label, children }: { label: string; children: ReactNode }) { return <div className="catalog-sample"><div>{children}</div><span>{label}</span></div>; }
const sizes = ['xs', 'sm', 'md', 'lg', 'xl'] as const;
export function ButtonStory({ notify }: StoryProps) {
  return <><StorySection title="Варианты"><div className="catalog-row">{(['primary', 'secondary', 'outline', 'ghost', 'accent', 'danger'] as const).map(variant => <Sample label={variant} key={variant}><UI.Button variant={variant} onClick={() => notify(`Действие: ${variant}`)}>{variant === 'danger' ? 'Удалить' : 'Сохранить'}</UI.Button></Sample>)}</div></StorySection><StorySection title="Размеры"><div className="catalog-row">{sizes.map(size => <Sample key={size} label={size}><UI.Button size={size} onClick={() => notify(`Размер ${size}`)}>Кнопка</UI.Button></Sample>)}</div></StorySection><StorySection title="Иконки и состояния"><div className="catalog-row"><UI.Button leading={<UI.Icon name="plus" />} onClick={() => notify('Новый объект создан')}>Создать</UI.Button><UI.Button trailing={<UI.Icon name="arrow" />} onClick={() => notify('Следующий шаг')}>Продолжить</UI.Button><UI.Button disabled>Недоступно</UI.Button><UI.Button loading>Сохраняем</UI.Button></div></StorySection></>;
}
export function IconButtonStory({ notify }: StoryProps) { return <><StorySection title="Варианты"><div className="catalog-row">{(['secondary', 'outline', 'ghost', 'primary', 'accent', 'danger'] as const).map(variant => <Sample key={variant} label={variant}><UI.IconButton label={`Поиск: ${variant}`} icon="search" variant={variant} onClick={() => notify('Открыт поиск')} /></Sample>)}</div></StorySection><StorySection title="Размеры и состояния"><div className="catalog-row">{sizes.map(size => <Sample key={size} label={size}><UI.IconButton label={`Добавить: ${size}`} icon="plus" size={size} onClick={() => notify('Объект добавлен')} /></Sample>)}<UI.IconButton icon="trash" label="Удаление недоступно" disabled /><UI.IconButton icon="copy" label="Копируем" loading /></div></StorySection></>; }
export function IconStory() { const names: UI.IconName[] = ['plus','search','close','check','chevron','down','menu','grid','page','book','cube','calendar','sun','moon','settings','copy','arrow','external','code','folder','tag','sparkle','info','warning','trash','more','filter','list','clock','layers','heart','minus','sort','microphone']; return <><StorySection><div className="catalog-icon-grid">{names.map(name => <Sample key={name} label={name}><UI.Icon name={name} size={20} /></Sample>)}</div></StorySection><StorySection title="Размер"><div className="catalog-row">{[12,16,20,24].map(size => <Sample key={size} label={`${size} px`}><UI.Icon name="cube" size={size} /></Sample>)}</div></StorySection></>; }
export function ButtonGroupStory({notify}:StoryProps) {
 const [view,setView]=useState('list');
 return <><StorySection title="Счётчик и представление"><UI.ButtonGroup label="Представление коллекции" prefix="99+">
 <UI.Tooltip content="Filter"><UI.IconButton label="Фильтр" icon="filter" variant="ghost" onClick={()=>notify('Фильтр применён')}/></UI.Tooltip>
 <UI.Tooltip content="Сортировка"><UI.IconButton label="Сортировка" icon="sort" variant="ghost" onClick={()=>notify('Порядок изменён')}/></UI.Tooltip>
 <UI.IconButton label="Таблица" icon="table" variant="ghost" aria-pressed={view==='table'} onClick={()=>setView('table')}/>
 <UI.Button variant="ghost" aria-label="Выбрать представление" leading={<UI.Icon name="list" size={14}/>} trailing={<UI.Icon name="down" size={12}/>} onClick={()=>setView('list')}/>
 <UI.Tooltip content="Настроить представление"><UI.IconButton label="Настройки представления" icon="sliders" variant="ghost" onClick={()=>notify('Настройки представления')}/></UI.Tooltip>
 </UI.ButtonGroup></StorySection><StorySection title="Объединённые селекты"><UI.ButtonGroup label="Параметры списка"><UI.Select aria-label="Порядок" options={[{value:"recent",label:"Сначала новые"},{value:"old",label:"Сначала старые"}]}/><UI.Select aria-label="Группировка" options={[{value:"month",label:"По месяцам"},{value:"year",label:"По годам"}]}/></UI.ButtonGroup></StorySection><StorySection title="Размеры и состояния"><div className="catalog-stack">{sizes.map(size=><div className="catalog-row" key={size}><span className="muted">{size}</span><UI.ButtonGroup label={`Группа ${size}`} size={size} prefix="99+"><UI.IconButton icon="filter" label={`Фильтр ${size}`} variant="ghost"/><UI.IconButton icon="list" label={`Список ${size}`} variant="ghost"/><UI.IconButton icon="sliders" label={`Настройки ${size}`} variant="ghost" disabled/></UI.ButtonGroup></div>)}</div></StorySection><StorySection title="Раздельная и вертикальная группы"><div className="catalog-row"><UI.ButtonGroup label="История" attached={false}><UI.Button onClick={()=>notify('Предыдущая версия')}>Назад</UI.Button><UI.Button onClick={()=>notify('Следующая версия')}>Вперёд</UI.Button></UI.ButtonGroup><UI.ButtonGroup label="Масштаб" orientation="vertical"><UI.IconButton label="Увеличить" icon="plus"/><UI.IconButton label="Уменьшить" icon="minus"/></UI.ButtonGroup></div></StorySection></>;
}

export function SplitButtonStory({ notify }: StoryProps) { const items: UI.MenuItem[] = [{id:'note',label:'Новая заметка',icon:'page',onSelect:()=>notify('Заметка создана')},{id:'project',label:'Новый проект',icon:'cube',onSelect:()=>notify('Проект создан')},{id:'template',label:'Из шаблона',icon:'copy',separator:true,onSelect:()=>notify('Объект создан из шаблона')}]; return <><StorySection title="Основное действие и меню"><div className="catalog-row"><UI.SplitButton label="Создать" leading={<UI.Icon name="plus"/>} items={items} onClick={()=>notify('Объект создан')} /><UI.SplitButton label="Экспорт" variant="secondary" items={[{id:'md',label:'Markdown',onSelect:()=>notify('Выбран Markdown')},{id:'json',label:'JSON',onSelect:()=>notify('Выбран JSON')}]} onClick={()=>notify('Экспорт подготовлен')} /><UI.SplitButton label="Создать" variant="accent" items={items} onClick={()=>notify('Объект создан')} /></div></StorySection><StorySection title="Раздельные действия"><div className="catalog-row"><UI.SplitButton label="Создать" layout="separated" leading={<UI.Icon name="plus"/>} items={items} onClick={()=>notify('Объект создан')}/><UI.SplitButton label="Экспорт" layout="separated" variant="secondary" items={items} onClick={()=>notify('Экспорт подготовлен')}/></div></StorySection><StorySection title="Состояния"><div className="catalog-row"><UI.SplitButton label="Недоступно" items={items} disabled /><UI.SplitButton label="Создаём" items={items} loading /></div></StorySection></>; }
export function ActionBarStory({ notify }: StoryProps) { const [view,setView]=useState('grid'); return <><StorySection title="Составная панель"><UI.ActionBar label="Смешанная панель"><UI.ButtonGroup label="Вид коллекции" prefix={12}><UI.IconButton label="Фильтровать" icon="filter" variant="ghost" onClick={()=>notify('Фильтр применён')}/><UI.IconButton label="Список объектов" icon="list" variant="ghost"/><UI.IconButton label="Сетка объектов" icon="grid" aria-pressed variant="secondary"/></UI.ButtonGroup><span style={{flex:1}}/><UI.Popover label="Поиск"><UI.Input aria-label="Поиск объектов" placeholder="Название объекта"/></UI.Popover><UI.SplitButton label="Создать" leading={<UI.Icon name="plus"/>} onClick={()=>notify('Заметка создана')} items={[{id:'note',label:'Заметка',onSelect:()=>notify('Заметка создана')},{id:'project',label:'Проект',onSelect:()=>notify('Проект создан')}]}/></UI.ActionBar></StorySection><StorySection title="Панель коллекции"><UI.ActionBar label="Инструменты коллекции"><UI.IconButton icon="filter" label="Фильтр" variant="ghost" onClick={()=>notify('Фильтр применён')} /><UI.IconButton icon="sort" label="Сортировка" variant="ghost" onClick={()=>notify('Порядок изменён')} /><UI.IconButton icon="grid" label="Карточки" variant={view==='grid'?'secondary':'ghost'} aria-pressed={view==='grid'} onClick={()=>setView('grid')} /><UI.IconButton icon="list" label="Список" variant={view==='list'?'secondary':'ghost'} aria-pressed={view==='list'} onClick={()=>setView('list')} /><UI.Menu label="Действия коллекции" items={[{id:'copy',label:'Дублировать',icon:'copy',onSelect:()=>notify('Коллекция дублирована')},{id:'delete',label:'Удалить',icon:'trash',danger:true,onSelect:()=>notify('Коллекция удалена в примере')}]} /></UI.ActionBar></StorySection><StorySection title="Вертикальная панель"><UI.ActionBar label="Инструменты редактора" orientation="vertical"><UI.IconButton label="Текст" icon="page" variant="ghost" onClick={()=>notify('Режим текста')} /><UI.IconButton label="Код" icon="code" variant="ghost" onClick={()=>notify('Режим кода')} /><UI.IconButton label="Ссылка" icon="external" variant="ghost" onClick={()=>notify('Ссылка добавлена')} /></UI.ActionBar></StorySection></>; }
export function FloatingActionBarStory({ notify }: StoryProps) {
 const [period,setPeriod]=useState('week'),[view,setView]=useState('board');
 const controls=<><UI.IconButton label="Документ" icon="page" variant="ghost" onClick={()=>notify('Документ открыт')}/><UI.IconButton label="Настройки" icon="sliders" variant="ghost" onClick={()=>notify('Настройки открыты')}/></>;
 return <><StorySection title="Размеры и действия"><div className="catalog-floating-sizes">{(['sm','md','lg','xl'] as const).map(size=><div className="catalog-floating-example" key={size}><span className="catalog-muted">{size}</span><UI.FloatingActionBar label={`Действия ${size}`} position="static" size={size} leading={<UI.Counter value="99+" variant="plain" size={size==='xl'?'lg':size}/>} trailing={<UI.Button variant="accent" onClick={()=>notify('Заметка сохранена')}>Сохранить</UI.Button>}>{controls}</UI.FloatingActionBar></div>)}</div></StorySection>
 <StorySection title="Секции и разделители"><div className="catalog-row"><UI.FloatingActionBar label="Параметры представления" position="static" size="sm" variant="divided" action={{label:'Применить',icon:'check',variant:'accent',onClick:()=>notify(`Параметры: ${period}, ${view}`)}}><UI.Select aria-label="Период" variant="ghost" size="sm" style={{width:108,maxWidth:'100%'}} value={period} onValueChange={setPeriod} options={[{value:'week',label:'Неделя'},{value:'month',label:'Месяц'}]}/><UI.Select aria-label="Вид" variant="ghost" size="sm" style={{width:108,maxWidth:'100%'}} value={view} onValueChange={setView} options={[{value:'board',label:'Доска'},{value:'list',label:'Список'}]}/></UI.FloatingActionBar><UI.FloatingActionBar label="Вертикальные действия" position="static" size="sm" variant="divided" orientation="vertical" action={{label:'Готово',icon:'check',variant:'accent',onClick:()=>notify('Изменения применены')}}><UI.IconButton label="Добавить" icon="plus" variant="ghost" onClick={()=>notify('Добавлен блок')}/><UI.IconButton label="Настройки" icon="sliders" variant="ghost" onClick={()=>notify('Открыты настройки')}/></UI.FloatingActionBar></div></StorySection>
 <StorySection title="Поверх прокручиваемой области"><UI.ScrollArea label="Область с плавающей панелью" style={{height:280}} floating={<UI.FloatingActionBar label="Действия заметки" position="static" size="lg" trailing={<UI.Button variant="accent" onClick={()=>notify('Заметка сохранена')}>Сохранить</UI.Button>}><UI.IconButton icon="copy" label="Копировать" variant="ghost" onClick={()=>notify('Копия создана')}/><UI.IconButton icon="more" label="Ещё действия" variant="ghost" onClick={()=>notify('Действия заметки')}/></UI.FloatingActionBar>}><div className="catalog-long-note"><h3>Заметки на полях</h3>{Array.from({length:8},(_,i)=><p key={i}>Мысль {i+1}. Оставить немного места для следующего шага.</p>)}</div></UI.ScrollArea></StorySection></>;
}

export function KbdStory() { return <StorySection><div className="catalog-row"><Sample label="Комбинация"><span className="catalog-inline"><UI.Kbd>⌘</UI.Kbd><UI.Kbd>K</UI.Kbd></span></Sample><Sample label="Закрыть"><UI.Kbd>esc</UI.Kbd></Sample><Sample label="Перейти"><UI.Kbd>↵</UI.Kbd></Sample><Sample label="Навигация"><span className="catalog-inline"><UI.Kbd>↑</UI.Kbd><UI.Kbd>↓</UI.Kbd></span></Sample></div></StorySection>; }
export function InputStory() { return <><StorySection title="Текст и поиск"><div className="catalog-fields"><UI.Input aria-label="Название" placeholder="Название проекта"/><UI.Input aria-label="Поиск" type="search" placeholder="Найти заметку…"/><UI.Input aria-label="Пароль" type="password" defaultValue="quiet-morning"/></div></StorySection><StorySection title="Размеры"><div className="catalog-fields">{sizes.map(size=><UI.Input key={size} size={size} aria-label={`Поле ${size}`} placeholder={`Размер ${size}`}/>)}</div></StorySection><StorySection title="Состояния"><div className="catalog-fields"><UI.Input aria-label="Только чтение" value="Только для чтения" readOnly/><UI.Input aria-label="Недоступное поле" value="Недоступно" disabled/><UI.Input aria-label="Ошибка" aria-invalid="true" defaultValue="Некорректное значение"/></div></StorySection><StorySection title="Общее положение подписи"><FieldFamily/></StorySection></>; }
export function FloatingFieldStory() { const [value,setValue]=useState(''); return <><StorySection title="Подпись внутри"><div className="catalog-fields"><UI.FloatingField label="Название проекта" value={value} onChange={event=>setValue(event.target.value)} /><UI.FloatingField label="Поиск" leading={<UI.Icon name="search"/>} defaultValue="Сад идей" hint="Подпись остаётся над значением"/></div></StorySection><StorySection title="Состояния"><div className="catalog-fields"><UI.FloatingField label="Почта" type="email" defaultValue="hello" error="Введите адрес электронной почты"/><UI.FloatingField label="Название" defaultValue="Только для чтения" readOnly/><UI.FloatingField label="Недоступное поле" defaultValue="Сад идей" disabled/></div></StorySection><StorySection title="Общее положение подписи"><FieldFamily/></StorySection></>; }
export function TextareaStory() { return <><StorySection title="Многострочный ввод"><div className="catalog-fields"><UI.Textarea aria-label="Описание проекта" rows={4} placeholder="О чём этот проект?"/><UI.Textarea aria-label="Заметка" rows={3} defaultValue="Несколько мыслей, к которым хочется вернуться."/></div></StorySection><StorySection title="Состояния"><div className="catalog-fields"><UI.Textarea aria-label="Недоступное описание" rows={3} disabled defaultValue="Поле временно недоступно"/><UI.Textarea aria-label="Описание с ошибкой" rows={3} aria-invalid="true" defaultValue="Слишком коротко"/></div></StorySection><StorySection title="Общее положение подписи"><FieldFamily/></StorySection></>; }
export function SelectStory() { const [value,setValue]=useState('project');const options=[{value:'project',label:'Проект',group:'Объекты'},{value:'note',label:'Заметка',group:'Объекты'},{value:'book',label:'Книга',group:'Коллекции'},{value:'locked',label:'Архив',disabled:true,group:'Коллекции'}];return <><StorySection title="Выбор и группы"><div className="catalog-fields"><UI.Select aria-label="Тип объекта" value={value} onValueChange={setValue} options={options}/><UI.Select aria-label="Пустой выбор" placeholder="Выберите тип" defaultValue=""><option value="" disabled>Выберите тип</option><option value="note">Заметка</option><option value="project">Проект</option></UI.Select></div></StorySection><StorySection title="Размеры"><div className="catalog-fields">{sizes.map(size=><UI.Select aria-label={`Выбор ${size}`} key={size} size={size} defaultValue="project" options={options}/>)}</div></StorySection><StorySection title="Состояния"><div className="catalog-fields"><UI.Select aria-label="Недоступный выбор" disabled defaultValue="project" options={options}/><UI.Select aria-label="Выбор с ошибкой" aria-invalid="true" defaultValue="note" options={options}/></div></StorySection><StorySection title="Общее положение подписи"><FieldFamily/></StorySection></>; }
export function FieldStory({notify}:StoryProps) {const [name,setName]=useState(''),[sent,setSent]=useState(false); return <><StorySection title="Подпись и подсказка"><div className="catalog-fields"><UI.Field label="Название" hint="Короткое имя, которое легко найти">{props=><UI.Input {...props} placeholder="Сад идей"/>}</UI.Field><UI.Field label="Описание" hint="Необязательное поле">{props=><UI.Textarea {...props} rows={3}/>}</UI.Field></div></StorySection><StorySection title="Проверка формы"><form className="catalog-stack catalog-narrow" noValidate onSubmit={event=>{event.preventDefault();setSent(true);if(name.trim())notify(`Сохранено: ${name}`);}}><UI.Field label="Название проекта" required error={sent&&!name.trim()?'Введите название':undefined}>{props=><UI.Input {...props} value={name} onChange={event=>setName(event.target.value)}/>}</UI.Field><UI.Button type="submit" variant="primary">Сохранить</UI.Button></form></StorySection></>; }
export function CheckboxStory() {const [all,setAll]=useState(false);return <><StorySection title="Размеры"><div className="catalog-row">{sizes.map(size=><UI.Checkbox key={size} size={size} label={size} defaultChecked/>)}</div></StorySection><StorySection title="Состояния"><div className="catalog-stack catalog-narrow"><UI.Checkbox label="Показывать заметки" defaultChecked/><UI.Checkbox label="Добавить в избранное"/><UI.Checkbox label="Выбрать всё" checked={all} indeterminate={!all} onChange={e=>setAll(e.target.checked)}/><UI.Checkbox label="Недоступный выбор" disabled/><UI.Checkbox label="Выбрано и недоступно" disabled defaultChecked/></div></StorySection></>; }
export function RadioStory() {const name=useId();return <><StorySection title="Размеры"><div className="catalog-row">{sizes.map(size=><UI.Radio key={size} size={size} name={`${name}-${size}`} label={size} defaultChecked/>)}</div></StorySection><StorySection title="Выбор доступа"><fieldset className="catalog-fieldset"><legend>Кто видит проект</legend><UI.Radio name={name} label="Только я" value="private" defaultChecked/><UI.Radio name={name} label="По ссылке" value="link"/><UI.Radio name={name} label="Публичный доступ" value="public" disabled/></fieldset></StorySection></>; }

export function SwitchStory() {const [enabled,setEnabled]=useState(true);return <><StorySection title="Единый Primary"><div className="catalog-row"><UI.Button variant="primary" onClick={()=>setEnabled(value=>!value)}>Переключить</UI.Button><UI.Checkbox label="Выбор" checked={enabled} onChange={event=>setEnabled(event.target.checked)}/><UI.Radio label="Выбрано" name="primary-comparison" checked={enabled} onChange={()=>setEnabled(true)}/><UI.Switch label="Настройка" checked={enabled} onChange={event=>setEnabled(event.target.checked)}/></div></StorySection><StorySection title="Размеры"><div className="catalog-row">{sizes.map(size=><UI.Switch key={size} label={size} size={size} defaultChecked/>)}</div></StorySection><StorySection title="Состояния"><div className="catalog-stack catalog-narrow"><UI.Switch label="Primary" defaultChecked/><UI.Switch label="Vivid — явный выбор" contrast={false} defaultChecked/><UI.Switch label="Нейтральный" variant="neutral" defaultChecked/><UI.Switch label="Выключен"/><UI.Switch label="Недоступная настройка" disabled/><UI.Switch label="Всегда включено" defaultChecked disabled/></div></StorySection></>; }
export function SliderStory() {const [value,setValue]=useState(48);return <><StorySection title="Размеры"><div className="catalog-fields">{sizes.map(size=><UI.Slider key={size} size={size} label={`Размер ${size}`} defaultValue={45}/>)}</div></StorySection><StorySection title="Плотность и диапазон"><div className="catalog-fields"><UI.Slider label="Плотность" value={value} min={0} max={100} onChange={event=>setValue(Number(event.target.value))}/><UI.Slider label="Шаг 10" defaultValue={30} min={0} max={100} step={10}/><UI.Slider label="Недоступно" defaultValue={65} disabled/></div></StorySection></>; }

export function SegmentedControlStory() {const [view,setView]=useState('grid'),[period,setPeriod]=useState('week');return <><StorySection title="Представление"><UI.SegmentedControl label="Представление" value={view} onValueChange={setView} options={[{value:'grid',label:'Карточки',icon:<UI.Icon name="grid"/>},{value:'list',label:'Список',icon:<UI.Icon name="list"/>},{value:'table',label:'Таблица',disabled:true}]}/></StorySection><StorySection title="Период"><UI.SegmentedControl label="Период" value={period} onValueChange={setPeriod} options={[{value:'day',label:'День'},{value:'week',label:'Неделя'},{value:'month',label:'Месяц'}]}/></StorySection></>; }
export function CalendarStory() {
 const [date,setDate]=useState('2026-10-07'),[range,setRange]=useState<UI.CalendarRange|undefined>({start:'2026-10-28',end:'2026-11-03'});
 return <><StorySection title="Два месяца и период"><UI.Calendar label="Период проекта" mode="range" range={range} onRangeChange={setRange} today="2026-10-07" events={scheduleEvents} highlightedDates={[{date:'2026-10-09',label:'Срок передачи',color:'orange'}]} /></StorySection>
 <StorySection title="События и поверхности"><CalendarSchedule /></StorySection>
 <StorySection title="Недоступные даты"><UI.Calendar label="Календарь с ограничениями" value={date} onValueChange={setDate} today="2026-10-07" min="2026-10-01" max="2026-10-31" isDateUnavailable={day=>['2026-10-10','2026-10-11'].includes(day)}/></StorySection></>;
}
export function DatePickerStory() {
 const [date,setDate]=useState<string>(),[range,setRange]=useState<UI.CalendarRange|undefined>();
 return <StorySection><div className="catalog-row"><UI.DatePicker label="Выбрать дату" value={date} onValueChange={setDate} today="2026-10-07" defaultMonth="2026-10" events={scheduleEvents} showAgenda/><UI.DatePicker label="Выбрать период" mode="range" range={range} onRangeChange={setRange} today="2026-10-07" defaultMonth="2026-10" events={scheduleEvents}/></div></StorySection>;
}
