import { useCatalogText, localizeCatalogueFixture } from './catalog-locale';
import { lazy, Suspense, useState } from 'react';
import * as UI from '../src';
import { Sample, StorySection, type StoryProps } from './stories-controls';
const LucideGallery=lazy(()=>import('./LucideGallery'));
const sizes=['xs','sm','md','lg','xl'] as const;
export function TagStory({notify}:StoryProps) {
 const ct=useCatalogText();

 const [interactive,setInteractive]=useState(true);
 const [tags,setTags]=useState([ct('Дизайн'),ct('Исследование'),ct('Продукт')]);
 return <><StorySection><UI.Switch label={ct("Интерактивные теги")} checked={interactive} onChange={e=>setInteractive(e.target.checked)}/></StorySection><StorySection title={ct("Один компонент")}><div className="catalog-row">{sizes.map(size=><Sample label={size} key={size}><UI.Tag interactive={interactive} size={size} icon="tag" count={12} onClick={()=>notify(ct('Открыты метки'))} onRemove={()=>notify(ct('Метка удалена'))}>{ct("Дизайн")}</UI.Tag></Sample>)}</div></StorySection><StorySection title={ct("Все акценты")}><div className="catalog-row">{UI.colors.map(color=><UI.Tag interactive={interactive} key={color} color={color} icon="folder" count={8} onClick={()=>notify(color)} onRemove={()=>notify(`${ct("Удалить ")}${color}`)}>{color}</UI.Tag>)}</div></StorySection><StorySection title={ct("Варианты")}><div className="catalog-row">{(['soft','solid','outline'] as const).map(variant=><UI.Tag interactive={interactive} key={variant} variant={variant} icon="page" onClick={()=>notify(variant)}>{variant}</UI.Tag>)}<UI.Tag interactive={interactive} icon="book" count={3} disabled onClick={()=>{}} onRemove={()=>{}}>{ct("Недоступен")}</UI.Tag><UI.Tag interactive={interactive} icon="cube" action={{icon:'more',label:ct('Действия проекта'),onClick:()=>notify(ct('Действия проекта'))}}>{ct("Проект")}</UI.Tag></div></StorySection><StorySection title={ct("Удаление")}><div className="catalog-row">{tags.map(tag=><UI.Tag interactive={interactive} key={tag} onRemove={()=>setTags(current=>current.filter(item=>item!==tag))}>{tag}</UI.Tag>)}{tags.length<3&&<UI.TextAction onClick={()=>setTags([ct('Дизайн'),ct('Исследование'),ct('Продукт')])}>{ct("Вернуть")}</UI.TextAction>}</div></StorySection></>;
}
export function CounterStory(){
 const ct=useCatalogText();
return <>
 <StorySection title={ct("Размеры")}><div className="catalog-counter-samples">{sizes.map(size=><Sample key={size} label={size}><UI.Counter value={128} max={99} size={size}/></Sample>)}</div></StorySection>
 <StorySection title={ct("Стили")}><div className="catalog-counter-colors">{(['translucent','accent','white','black','neutral','plain'] as const).map(variant=><Sample key={variant} label={variant}><UI.Counter value="99+" variant={variant}/></Sample>)}</div></StorySection>
 <StorySection title={ct("Форма и содержимое")}><div className="catalog-row">{(['round','rounded'] as const).map(shape=><div className="catalog-row" key={shape}>{[1,'99+',12345].map(value=><UI.Counter key={value} value={value} shape={shape} size="md"/>)}</div>)}</div></StorySection>
 <StorySection title={ct("В контексте")}><div className="catalog-row"><UI.Tag count="99+" icon="book" counter={{variant:'white',shape:'rounded'}}>{ct("Книги")}</UI.Tag><UI.Tag count="99+" variant="solid" icon="folder" counter={{variant:'translucent'}}>{ct("Проекты")}</UI.Tag><UI.SidebarItem icon="page" count={128}>{ct("Заметки")}</UI.SidebarItem></div></StorySection>
 </>;}
export function TextActionStory({notify}:StoryProps){
 const ct=useCatalogText();
return <StorySection><div className="catalog-row"><UI.TextAction href="#Tag">{ct("Открыть теги")}</UI.TextAction><UI.TextAction onClick={()=>notify(ct('Ссылка скопирована в примере'))}>{ct("Действие")}</UI.TextAction><UI.TextAction disabled>{ct("Недоступно")}</UI.TextAction></div><UI.Breadcrumbs items={[{label:ct('Компоненты'),href:'#Button'},{label:ct('Коллекции'),href:'#CollectionRow'},{label:ct('Сад идей')}]}/></StorySection>;}
export function IconPickerStory(){
 const ct=useCatalogText();
return <StorySection><Suspense fallback={<UI.Spinner label={ct("Загружаем Lucide")}/>}><LucideGallery/></Suspense></StorySection>;}
export function ContentLayoutStory(){
 const ct=useCatalogText();

 const [left,setLeft]=useState(true),[right,setRight]=useState(false),[leftWidth,setLeftWidth]=useState(180),[rightWidth,setRightWidth]=useState(200),[leftHeight,setLeftHeight]=useState(160),[rightHeight,setRightHeight]=useState(160),[contentWidth,setContentWidth]=useState(440),[paneContentWidth,setPaneContentWidth]=useState(240),[orientation,setOrientation]=useState<'horizontal'|'vertical'>('horizontal'),[divider,setDivider]=useState<'always'|'hover'|'none'>('hover');
 return <StorySection><div className="catalog-stack" style={{gap:16}}><div className="catalog-row catalog-story-controls"><UI.IconButton icon="panelLeft" label={ct("Первая панель")} aria-pressed={left} onClick={()=>setLeft(value=>!value)}/><UI.IconButton icon="panelRight" label={ct("Вторая панель")} aria-pressed={right} onClick={()=>setRight(value=>!value)}/><UI.Select aria-label={ct("Ориентация панелей")} size="sm" value={orientation} onValueChange={value=>setOrientation(value as typeof orientation)} options={[{value:'horizontal',label:ct('Горизонтально')},{value:'vertical',label:ct('Вертикально')}]}/><UI.Select aria-label={ct("Разделитель панелей")} size="sm" value={divider} onValueChange={value=>setDivider(value as typeof divider)} options={[{value:'always',label:ct('Всегда')},{value:'hover',label:ct('При наведении')},{value:'none',label:ct('Без линии')}]}/><UI.Popover label={ct("Ширина контента")} triggerContent={<UI.Icon name="sliders"/>}><div className="catalog-stack"><UI.Slider label={ct("Основной контент")} min={240} max={800} step={20} value={contentWidth} onChange={event=>setContentWidth(Number(event.target.value))}/><UI.Slider label={ct("Контент в панелях")} min={120} max={400} step={20} value={paneContentWidth} onChange={event=>setPaneContentWidth(Number(event.target.value))}/></div></UI.Popover></div>
 <UI.ContentLayout collapseAt={600} minContentSize={200} orientation={orientation} divider={divider} contentWidth={contentWidth} style={orientation==='vertical'?{height:760}:undefined} left={{label:ct('Коллекции'),open:left,onOpenChange:setLeft,width:leftWidth,onWidthChange:setLeftWidth,height:leftHeight,onHeightChange:setLeftHeight,contentWidth:paneContentWidth,content:<div className="catalog-stack"><UI.SidebarItem icon="page" count={12} active>{ct("Заметки")}</UI.SidebarItem><UI.SidebarItem icon="book" count={4}>{ct("Книги")}</UI.SidebarItem><UI.Tag icon="folder" count={8}>{ct("Личное")}</UI.Tag></div>}} right={{label:ct('Свойства'),open:right,onOpenChange:setRight,width:rightWidth,onWidthChange:setRightWidth,height:rightHeight,onHeightChange:setRightHeight,contentWidth:paneContentWidth,content:<div className="catalog-stack"><UI.Tag icon="cube" count={3}>{ct("Проект")}</UI.Tag><UI.Input label={ct("Название")} defaultValue={ct("Сад идей")}/><UI.Checkbox label={ct("Закрепить")}/></div>}}><div className="catalog-stack"><UI.Breadcrumbs items={[{label:ct('Коллекции'),href:'#CollectionRow'},{label:ct('Сад идей')}]}/><h3>{ct("Сад идей")}</h3><p className="catalog-muted">{ct("Панели работают по обеим осям. Разделитель меняет размер перетаскиванием и стрелками независимо от видимости линии.")}</p><UI.ContentCard title={ct("Сад идей")} description={ct("Карточка занимает доступную ширину и сохраняет собственную высоту.")}/><UI.CodeBlock label="workspace.tsx" language="tsx">{'<ContentLayout orientation="vertical" divider="hover"\n  left={collections} right={properties}>\n  {document}\n</ContentLayout>'}</UI.CodeBlock></div></UI.ContentLayout></div></StorySection>;
}

export function ResizableCardStory(){
 const ct=useCatalogText();

 const [size,setSize]=useState({width:360,height:240});
 return <StorySection title={ct("Размер под содержимое")}><div className="catalog-stack"><p className="catalog-muted">{ct("Потяните за правый нижний угол. Tab и стрелки позволяют изменить размер с клавиатуры.")}</p><UI.ResizableCard label={ct("Заметка о проекте")} size={size} onSizeChange={setSize}><div className="catalog-stack"><UI.Tag color="neutral" icon="page" interactive={false}>{ct("Заметка")}</UI.Tag><h3>{ct("Сад идей")}</h3><p>{ct("Собирайте заметки, референсы и следующие шаги. Содержимое переносится по ширине карточки.")}</p></div></UI.ResizableCard><span className="catalog-muted" role="status">{size.width} × {size.height} px</span></div></StorySection>;
}
