import { useState } from 'react';
import { Button, Select } from '../src';
import { AnnouncementBar, CardStack, TextShimmer, ToastStack, type ToastStackItem } from '../src/components/messages';
import { Sample, StorySection } from './stories-controls';

export function ToastStackStory(){const [direction,setDirection]=useState<'up'|'down'|'left'|'right'>('down');const [items,setItems]=useState<ToastStackItem[]>([{id:'saved',title:'Changes saved',description:'Your workspace is up to date.',tone:'success'},{id:'undo',title:'Item archived',description:'It is in the archive.',tone:'info',contrast:true,action:{label:'Undo',onAction:()=>setItems(v=>v.filter(x=>x.id!=='undo'))}}]);return <StorySection><div className="catalog-narrow catalog-stack"><Select label="Направление раскрытия" value={direction} onValueChange={value=>setDirection(value as typeof direction)} options={['up','down','left','right'].map(value=>({value,label:value}))}/><ToastStack position="inline" expandDirection={direction} items={items} onDismiss={id=>setItems(v=>v.filter(x=>x.id!==id))}/><Button size="sm" onClick={()=>setItems(v=>[...v,{id:crypto.randomUUID(),title:'New update',description:'A sample notification.'}])}>Add notification</Button></div></StorySection>}
export function AnnouncementBarStory(){const [index,setIndex]=useState(0),[open,setOpen]=useState(true),[details,setDetails]=useState(false);return <StorySection><div className="catalog-stack"><AnnouncementBar label="Объявления рабочего пространства" open={open} onOpenChange={setOpen} index={index} onIndexChange={setIndex} autoPlay={false} controls messages={[{id:'release',message:'A new workspace update is ready.',action:{label:'See what changed',onClick:()=>setDetails(true)}},{id:'offer',message:'Your early access ends in:',countdown:{to:Date.now()+86400000,label:'Early access time left'}}]}/>{details&&<p role="status">The update adds faster search and saved filters.</p>}<Button size="sm" variant="ghost" onClick={()=>setOpen(true)}>Show announcement</Button></div></StorySection>}
export function CardStackStory(){const [direction,setDirection]=useState<'up'|'down'|'left'|'right'>('down');const cards=[{id:'plan',title:'Недельный план',body:'Спокойный ритм задач на неделю.'},{id:'archive',title:'Визуальный архив',body:'Место для референсов и заметок.'},{id:'metrics',title:'Панель прогресса',body:'Ключевые результаты в одном месте.'}];const [decisions,setDecisions]=useState<string[]>([]);return <StorySection title="Разбор карточек"><div className="catalog-stack"><p className="catalog-muted">Потяните карточку влево или вправо, используйте стрелки и отменяйте последнее решение.</p><Select label="Направление раскрытия карточек" value={direction} onValueChange={value=>setDirection(value as typeof direction)} options={['up','down','left','right'].map(value=>({value,label:value}))}/><CardStack review expandDirection={direction} items={cards} getKey={card=>card.id} getLabel={card=>card.title} labels={{left:'Пропустить',right:'Оставить'}} onDecide={(card,side)=>setDecisions(current=>[...current,`${card.title}: ${side==='right'?'оставить':'пропустить'}`])} onUndo={()=>setDecisions(current=>current.slice(0,-1))} onReset={()=>setDecisions([])} renderEmpty={reset=><div className="catalog-stack"><p>Все идеи просмотрены.</p><Button size="sm" onClick={reset}>Начать заново</Button></div>} renderCard={card=><article className="catalog-card" style={{padding:20}}><h3>{card.title}</h3><p>{card.body}</p></article>}/><span className="catalog-muted" role="status">{decisions.length?decisions.at(-1):'Решений пока нет'}</span></div></StorySection>}
export function TextShimmerStory(){const [active,setActive]=useState(true);return <StorySection><Sample label="Background work"><div className="catalog-stack"><TextShimmer as="p" active={active}>Gathering related notes…</TextShimmer><Button size="sm" variant="ghost" onClick={()=>setActive(v=>!v)}>{active?'Finish':'Resume'} work</Button></div></Sample></StorySection>}
