import { TabsGroupsExample } from './TabsGroupsExample';
import { useCatalogText, localizeCatalogueFixture } from './catalog-locale';
import { useState } from 'react';
import * as UI from '../src';
function OverflowTabsExample(){
 const ct=useCatalogText();
const [value,setValue]=useState('0');return <StorySection title={ct("Переполнение")}><div style={{maxWidth:340,width:'100%'}}><UI.Tabs label={ct("Разделы с прокруткой")} variant="pills" value={value} onValueChange={setValue} items={[ct('Все'),ct('Запланировано'),ct('В работе'),ct('Открыто'),ct('Завершено'),ct('Метки'),ct('Дедлайны')].map((label,index)=>({value:String(index),label,content:`${ct("Раздел: ")}${label}`}))}/></div></StorySection>;}
import { StorySection, type StoryProps } from './stories-controls';
export function SpinnerStory(){
 const ct=useCatalogText();
return <StorySection><div className="catalog-row"><UI.Spinner label={ct("Загрузка")}/><span className="catalog-inline"><UI.Spinner label={ct("Загрузка заметок")}/>{ct("Загружаем заметки")}</span><UI.Button loading>{ct("Сохраняем")}</UI.Button></div></StorySection>;}
export function SkeletonStory(){
 const ct=useCatalogText();
return <><StorySection title={ct("Карточка")}><div className="catalog-skeleton-card"><UI.Skeleton style={{width:40,height:40,borderRadius:'var(--cap-radius-base)'}}/><UI.Skeleton style={{width:'70%',height:18}}/><UI.Skeleton style={{width:'100%',height:12}}/><UI.Skeleton style={{width:'82%',height:12}}/></div></StorySection><StorySection title={ct("Строки")}><div className="catalog-stack catalog-narrow">{[1,2,3].map(row=><div className="catalog-inline" key={row}><UI.Skeleton style={{width:28,height:28,flexShrink:0}}/><UI.Skeleton style={{width:`${90-row*12}%`,height:13}}/></div>)}</div></StorySection></>;}
export function ProgressStory(){
 const ct=useCatalogText();
const [value,setValue]=useState(48);return <><StorySection title={ct("Прогресс операции")}><div className="catalog-stack catalog-narrow"><UI.Progress label={ct("Обработка заметок")} value={value}/><div className="catalog-row"><UI.Button variant="ghost" size="sm" onClick={()=>setValue(current=>Math.min(100,current+10))} disabled={value===100}>{ct("Продвинуть на 10%")}</UI.Button><UI.Button variant="ghost" size="sm" onClick={()=>setValue(0)}>{ct("Сбросить")}</UI.Button><span className="catalog-muted">{value}%</span></div></div></StorySection><StorySection title={ct("Границы")}><div className="catalog-stack catalog-narrow"><UI.Progress label={ct("Начало")} value={0}/><UI.Progress label={ct("Завершено")} value={100}/></div></StorySection></>;}
export function CalloutStory(){
 const ct=useCatalogText();
return <StorySection><div className="catalog-stack"><UI.Callout title={ct("Небольшая подсказка")} color="blue">{ct("Добавьте несколько связанных заметок, чтобы вернуться к контексту позже.")}</UI.Callout><UI.Callout title={ct("Синхронизация завершена")} icon="check" color="green">{ct("Все изменения доступны на этом устройстве.")}</UI.Callout><UI.Callout title={ct("Проверьте данные")} icon="warning" color="amber">{ct("У объекта пока нет названия.")}</UI.Callout><UI.Callout color="neutral">{ct("Нейтральный блок без заголовка.")}</UI.Callout></div></StorySection>;}
export function EmptyStateStory({notify}:StoryProps){
 const ct=useCatalogText();
const [created,setCreated]=useState(false);return <><StorySection title={ct("Первый объект")}>{created?<div className="catalog-empty-created"><UI.IconBox icon="page"/><strong>{ct("Первая заметка")}</strong><UI.Button variant="ghost" size="sm" onClick={()=>setCreated(false)}>{ct("Вернуть пустое состояние")}</UI.Button></div>:<UI.EmptyState icon="folder" title={ct("Здесь пока пусто")} description={ct("Создайте первую заметку, чтобы начать коллекцию.")} action={<UI.Button leading={<UI.Icon name="plus"/>} onClick={()=>setCreated(true)}>{ct("Новая заметка")}</UI.Button>}/>}</StorySection><StorySection title={ct("Нет результатов")}><UI.EmptyState icon="search" title={ct("Ничего не найдено")} description={ct("Попробуйте другой запрос или сбросьте фильтры.")} action={<UI.Button variant="ghost" onClick={()=>notify(ct('Фильтры сброшены'))}>{ct("Сбросить фильтры")}</UI.Button>}/></StorySection></>;}
export function ToastStory(){
 const ct=useCatalogText();
const [shown,setShown]=useState(true);return <StorySection><div className="catalog-stack catalog-narrow">{shown?<UI.Toast title={ct("Заметка сохранена")} description={ct("Можно продолжать работу.")} onDismiss={()=>setShown(false)}/>:<UI.Button onClick={()=>setShown(true)}>{ct("Показать уведомление")}</UI.Button>}<UI.Toast surface="inherit" tone="info" color="violet" contrast title={ct("Ссылка скопирована")}/><UI.Toast surface="inherit" tone="warning" appearance="soft" title={ct("Требуется внимание")}/><UI.Toast surface="inherit" tone="danger" appearance="solid" title={ct("Операция остановлена")}/></div></StorySection>;}
export function StatusBarStory(){
 const ct=useCatalogText();
const [busy,setBusy]=useState(false);return <><StorySection title={ct("Состояние документа")}><div className="catalog-stack"><UI.StatusBar tone="success" trailing={ct("Обновлено сейчас")}>{ct("Все изменения сохранены")}</UI.StatusBar><UI.StatusBar tone="info" busy={busy} trailing={<UI.Button size="xs" variant="ghost" onClick={()=>setBusy(!busy)}>{busy?ct('Завершить'):ct('Начать')}</UI.Button>}>{busy?ct('Синхронизируем…'):ct('Готово к синхронизации')}</UI.StatusBar><UI.StatusBar tone="warning" variant="surface" contrast>{ct("Нет подключения к интернету")}</UI.StatusBar><UI.StatusBar tone="danger" appearance="solid">{ct("Не удалось сохранить изменения")}</UI.StatusBar></div></StorySection><StorySection title={ct("Нейтральный")}><UI.StatusBar trailing="UTF-8">{ct("Markdown · 248 символов")}</UI.StatusBar></StorySection></>;}
export function AlertStory(){
 const ct=useCatalogText();
const [visible,setVisible]=useState(true);return <><StorySection title={ct("Раскрывающийся блок")}><div className="catalog-stack"><UI.Alert title={ct("Все изменения синхронизированы")} tone="success" expandable defaultExpanded>{ct("Данные сохранены на этом устройстве и отправлены на сервер.")}</UI.Alert><UI.Alert title={ct("Обновления с других устройств получены")} tone="success" expandable>{ct("Можно продолжать работу с актуальной версией документа.")}</UI.Alert></div></StorySection><StorySection title={ct("Тон и закрытие")}><div className="catalog-stack"><UI.Alert title={ct("Осталась одна незаполненная деталь")} tone="warning">{ct("Добавьте название проекта.")}</UI.Alert>{visible?<UI.Alert title={ct("Не удалось сохранить")} tone="danger" onDismiss={()=>setVisible(false)}>{ct("Повторите попытку после восстановления соединения.")}</UI.Alert>:<UI.Button variant="ghost" onClick={()=>setVisible(true)}>{ct("Вернуть ошибку")}</UI.Button>}<UI.Alert title={ct("Подсказка")} tone="info" color="violet" contrast>{ct("Карточки можно перемещать через меню действий.")}</UI.Alert><UI.Alert title={ct("Примечание")} tone="neutral" appearance="soft">{ct("Нейтральный блок сообщения.")}</UI.Alert></div></StorySection></>;}
export function SidebarItemStory(){
 const ct=useCatalogText();
const [active,setActive]=useState('notes');return <StorySection><nav aria-label={ct("Разделы пространства")} className="catalog-sidebar-example">{[{id:'today',label:ct('Сегодня'),icon:'calendar' as const},{id:'notes',label:ct('Заметки'),icon:'page' as const,count:24,color:'purple' as const},{id:'projects',label:ct('Проекты'),icon:'cube' as const,count:3,color:'blue' as const}].map(item=><UI.SidebarItem key={item.id} icon={item.icon} count={item.count} color={item.color} active={active===item.id} onClick={()=>setActive(item.id)}>{item.label}</UI.SidebarItem>)}<UI.SidebarItem icon="folder" disabled>{ct("Архив")}</UI.SidebarItem></nav></StorySection>;}
export function BreadcrumbsStory(){
 const ct=useCatalogText();
return <><StorySection title={ct("Путь к объекту")}><UI.Breadcrumbs label={ct("Путь объекта")} items={[{label:ct('Компоненты'),href:'#Button'},{label:ct('Коллекции'),href:'#CollectionRow'},{label:ct('Сад идей')}]}/></StorySection><StorySection title={ct("Короткий путь")}><UI.Breadcrumbs label={ct("Раздел")} items={[{label:ct('Библиотека'),href:'#Card'},{label:ct('Заметки')}]}/></StorySection></>;}
export function AccordionStory(){
 const ct=useCatalogText();
const [active,setActive]=useState<string|null>('notes');return <><StorySection><div className="catalog-stack"><UI.Accordion title={ct("Что входит в набор?")} open>{ct("Компоненты интерфейса, темы, акцентные моды, шрифты и инструкции для разработки.")}</UI.Accordion><UI.Accordion title={ct("Как подключить стили?")}>{ct("Импортируйте styles.css один раз в точке входа приложения.")}</UI.Accordion></div></StorySection><StorySection title={ct("Плавное раскрытие")}><div className="catalog-stack">{[{id:'notes',title:ct('Заметки'),text:ct('Сохраняйте наблюдения и связывайте их с проектами.')},{id:'projects',title:ct('Проекты'),text:ct('Следующий шаг, материалы и решения в одном месте.')},{id:'archive',title:ct('Архив'),text:ct('Завершённые проекты остаются доступными.')}].map(item=><UI.Accordion key={item.id} variant="bouncy" icon="folder" title={item.title} open={active===item.id} onOpenChange={open=>setActive(open?item.id:null)}>{item.text}</UI.Accordion>)}</div></StorySection></>;}
export function TabsStory(){
 const ct=useCatalogText();
const [line,setLine]=useState('details'),[pills,setPills]=useState('all');return <><StorySection title={ct("Линия")}><UI.Tabs label={ct("Сведения об объекте")} value={line} onValueChange={setLine} items={[{value:'details',label:ct('Описание'),content:ct('Краткое описание проекта и следующего шага.')},{value:'links',label:ct('Связи'),count:12,color:'blue',content:<UI.Tag icon="page" color="blue">{ct("Связанная заметка")}</UI.Tag>},{value:'history',label:ct('История'),count:0,color:'purple',content:ct('Объект создан сегодня.')},{value:'access',label:ct('Доступ'),disabled:true,content:null}]}/></StorySection><StorySection title={ct("Сегменты")}><UI.Tabs label={ct("Содержимое дня")} variant="pills" value={pills} onValueChange={setPills} items={[{value:'all',label:ct('Всё'),content:ct('Все объекты этого дня.')},{value:'note',label:ct('Заметка'),content:ct('Место для ежедневной заметки.')},{value:'tasks',label:ct('Задачи'),content:ct('Пока нет задач.')},{value:'created',label:ct('Создано в этот день'),content:ct('Здесь появятся новые объекты.')}]}/></StorySection><OverflowTabsExample/><StorySection title={ct("Рабочие разделы и группы")}><TabsGroupsExample/></StorySection></>;}
export function SidebarPanelStory({notify}:StoryProps){
 const ct=useCatalogText();

 const [active,setActive]=useState(ct('Заметки')),[footerAlign,setFooterAlign]=useState<UI.SidebarPanelProps['footerAlign']>('end');
 const groups:{title:string;items:{label:string;count?:number;color?:UI.Color}[]}[]=[{title:ct('Работа'),items:[{label:ct('Сегодня'),count:0},{label:ct('Заметки'),count:24,color:'purple'},{label:ct('Проекты'),count:3,color:'blue'}]},{title:ct('Библиотека'),items:[{label:ct('Книги'),count:12,color:'amber'},{label:ct('Встречи'),count:2},{label:ct('Игры')},{label:ct('Люди')},{label:ct('Идеи'),count:104,color:'teal'},{label:ct('Вдохновение')}]},{title:ct('Архив'),items:[{label:ct('Завершённые'),count:8}]}];
 return <StorySection><div className="catalog-sidebar-panel-demo"><UI.SidebarPanel label={ct("Моё пространство")} header={ct("Моё пространство")} footerAlign={footerAlign} footer={<><span>{ct("Обновлено сегодня")}</span><UI.FloatingActionBar label={ct("Настройки пространства")} size="sm" position="static"><UI.IconButton label={ct("Профиль")} icon="page" variant="ghost" onClick={()=>notify(ct('Профиль открыт'))}/><UI.IconButton label={ct("Настройки")} icon="settings" variant="ghost" onClick={()=>notify(ct('Настройки открыты'))}/><UI.Menu label={ct("Ещё")} items={[{id:'new',label:ct('Новая коллекция'),icon:'plus',onSelect:()=>notify(ct('Коллекция добавлена'))} ]}/></UI.FloatingActionBar></>}>{groups.map((group,index)=><UI.Accordion key={group.title} title={group.title} variant="navigation" open={index<2} expandLabel={`${ct("Раскрыть: ")}${group.title}`} collapseLabel={`${ct("Свернуть: ")}${group.title}`}>{group.items.map(item=><UI.SidebarItem key={item.label} icon={item.label===ct('Сегодня')?'calendar':'folder'} color={item.color} count={item.count} active={active===item.label} onClick={()=>setActive(item.label)}>{item.label}</UI.SidebarItem>)}</UI.Accordion>)}</UI.SidebarPanel><div className="catalog-sidebar-panel-content"><h3>{active}</h3><p>{ct("Группы раскрываются независимо. Шапка и компактные действия остаются на месте при прокрутке списка.")}</p><UI.Select label={ct("Выравнивание нижнего блока")} value={footerAlign} onValueChange={value=>setFooterAlign(value as UI.SidebarPanelProps['footerAlign'])} options={[{value:'start',label:ct('Слева')},{value:'center',label:ct('По центру')},{value:'end',label:ct('Справа')},{value:'stretch',label:ct('На всю ширину')}]}/></div></div></StorySection>;
}
export function ScrollAreaStory(){
 const ct=useCatalogText();
return <><StorySection title={ct("Вертикальная прокрутка")}><UI.ScrollArea label={ct("Список заметок")} style={{height:250,maxWidth:480}}><div className="catalog-scroll-list">{Array.from({length:16},(_,index)=><div key={index}><UI.Icon name="page"/><span>{ct("Заметка ")}{String(index+1).padStart(2,'0')}</span><span>{ct("Сегодня")}</span></div>)}</div></UI.ScrollArea></StorySection><StorySection title={ct("Горизонтальная прокрутка")}><UI.ScrollArea label={ct("Коллекции")} axis="horizontal"><div className="catalog-scroll-cards">{Array.from({length:8},(_,index)=><UI.Card key={index}><UI.IconBox icon="folder"/><strong>{ct("Коллекция ")}{index+1}</strong></UI.Card>)}</div></UI.ScrollArea></StorySection><StorySection title={ct("Без теней")}><UI.ScrollArea label={ct("Простой список")} shadows={false} style={{height:130}}><div className="catalog-scroll-list">{Array.from({length:8},(_,index)=><div key={index}>{ct("Элемент ")}{index+1}</div>)}</div></UI.ScrollArea></StorySection></>;}
