import { lazy, Suspense, useState } from 'react';
import * as UI from '../src';
import { Sample, StorySection, type StoryProps } from './stories-controls';
const LucideGallery=lazy(()=>import('./LucideGallery'));
const sizes=['xs','sm','md','lg','xl'] as const;
export function TagStory({notify}:StoryProps) {
 const [interactive,setInteractive]=useState(true);
 const [tags,setTags]=useState(['Дизайн','Исследование','Продукт']);
 return <><StorySection><UI.Switch label="Интерактивные теги" checked={interactive} onChange={e=>setInteractive(e.target.checked)}/></StorySection><StorySection title="Один компонент"><div className="catalog-row">{sizes.map(size=><Sample label={size} key={size}><UI.Tag interactive={interactive} size={size} icon="tag" count={12} onClick={()=>notify('Открыты метки')} onRemove={()=>notify('Метка удалена')}>Дизайн</UI.Tag></Sample>)}</div></StorySection><StorySection title="Все акценты"><div className="catalog-row">{UI.colors.map(color=><UI.Tag interactive={interactive} key={color} color={color} icon="folder" count={8} onClick={()=>notify(color)} onRemove={()=>notify(`Удалить ${color}`)}>{color}</UI.Tag>)}</div></StorySection><StorySection title="Варианты"><div className="catalog-row">{(['soft','solid','outline'] as const).map(variant=><UI.Tag interactive={interactive} key={variant} variant={variant} icon="page" onClick={()=>notify(variant)}>{variant}</UI.Tag>)}<UI.Tag interactive={interactive} icon="book" count={3} disabled onClick={()=>{}} onRemove={()=>{}}>Недоступен</UI.Tag><UI.Tag interactive={interactive} icon="cube" action={{icon:'more',label:'Действия проекта',onClick:()=>notify('Действия проекта')}}>Проект</UI.Tag></div></StorySection><StorySection title="Удаление"><div className="catalog-row">{tags.map(tag=><UI.Tag interactive={interactive} key={tag} onRemove={()=>setTags(current=>current.filter(item=>item!==tag))}>{tag}</UI.Tag>)}{tags.length<3&&<UI.TextAction onClick={()=>setTags(['Дизайн','Исследование','Продукт'])}>Вернуть</UI.TextAction>}</div></StorySection></>;
}
export function CounterStory(){return <>
 <StorySection title="Размеры"><div className="catalog-counter-samples">{sizes.map(size=><Sample key={size} label={size}><UI.Counter value={128} max={99} size={size}/></Sample>)}</div></StorySection>
 <StorySection title="Стили"><div className="catalog-counter-colors">{(['translucent','accent','white','black','neutral','plain'] as const).map(variant=><Sample key={variant} label={variant}><UI.Counter value="99+" variant={variant}/></Sample>)}</div></StorySection>
 <StorySection title="Форма и содержимое"><div className="catalog-row">{(['round','rounded'] as const).map(shape=><div className="catalog-row" key={shape}>{[1,'99+',12345].map(value=><UI.Counter key={value} value={value} shape={shape} size="md"/>)}</div>)}</div></StorySection>
 <StorySection title="В контексте"><div className="catalog-row"><UI.Tag count="99+" icon="book" counter={{variant:'white',shape:'rounded'}}>Книги</UI.Tag><UI.Tag count="99+" variant="solid" icon="folder" counter={{variant:'translucent'}}>Проекты</UI.Tag><UI.SidebarItem icon="page" count={128}>Заметки</UI.SidebarItem></div></StorySection>
 </>;}
export function TextActionStory({notify}:StoryProps){return <StorySection><div className="catalog-row"><UI.TextAction href="#Tag">Открыть теги</UI.TextAction><UI.TextAction onClick={()=>notify('Ссылка скопирована в примере')}>Действие</UI.TextAction><UI.TextAction disabled>Недоступно</UI.TextAction></div><UI.Breadcrumbs items={[{label:'Компоненты',href:'#Button'},{label:'Коллекции',href:'#CollectionRow'},{label:'Сад идей'}]}/></StorySection>;}
export function IconPickerStory(){return <StorySection><Suspense fallback={<UI.Spinner label="Загружаем Lucide"/>}><LucideGallery/></Suspense></StorySection>;}
export function ContentLayoutStory(){
 const [left,setLeft]=useState(true),[right,setRight]=useState(true),[leftWidth,setLeftWidth]=useState(180),[rightWidth,setRightWidth]=useState(200),[leftHeight,setLeftHeight]=useState(160),[rightHeight,setRightHeight]=useState(160),[contentWidth,setContentWidth]=useState(440),[paneContentWidth,setPaneContentWidth]=useState(240),[orientation,setOrientation]=useState<'horizontal'|'vertical'>('horizontal'),[divider,setDivider]=useState<'always'|'hover'|'none'>('hover');
 return <StorySection><div className="catalog-stack" style={{gap:16}}><div className="catalog-row catalog-story-controls"><UI.IconButton icon="panelLeft" label="Первая панель" aria-pressed={left} onClick={()=>setLeft(value=>!value)}/><UI.IconButton icon="panelRight" label="Вторая панель" aria-pressed={right} onClick={()=>setRight(value=>!value)}/><UI.Select aria-label="Ориентация панелей" size="sm" value={orientation} onValueChange={value=>setOrientation(value as typeof orientation)} options={[{value:'horizontal',label:'Горизонтально'},{value:'vertical',label:'Вертикально'}]}/><UI.Select aria-label="Разделитель панелей" size="sm" value={divider} onValueChange={value=>setDivider(value as typeof divider)} options={[{value:'always',label:'Всегда'},{value:'hover',label:'При наведении'},{value:'none',label:'Без линии'}]}/><UI.Popover label="Ширина контента" triggerContent={<UI.Icon name="sliders"/>}><div className="catalog-stack"><UI.Slider label="Основной контент" min={240} max={800} step={20} value={contentWidth} onChange={event=>setContentWidth(Number(event.target.value))}/><UI.Slider label="Контент в панелях" min={120} max={400} step={20} value={paneContentWidth} onChange={event=>setPaneContentWidth(Number(event.target.value))}/></div></UI.Popover></div>
 <UI.ContentLayout orientation={orientation} divider={divider} contentWidth={contentWidth} style={orientation==='vertical'?{height:760}:undefined} left={{label:'Коллекции',open:left,onOpenChange:setLeft,width:leftWidth,onWidthChange:setLeftWidth,height:leftHeight,onHeightChange:setLeftHeight,contentWidth:paneContentWidth,content:<div className="catalog-stack"><UI.SidebarItem icon="page" count={12} active>Заметки</UI.SidebarItem><UI.SidebarItem icon="book" count={4}>Книги</UI.SidebarItem><UI.Tag icon="folder" count={8}>Личное</UI.Tag></div>}} right={{label:'Свойства',open:right,onOpenChange:setRight,width:rightWidth,onWidthChange:setRightWidth,height:rightHeight,onHeightChange:setRightHeight,contentWidth:paneContentWidth,content:<div className="catalog-stack"><UI.Tag icon="cube" count={3}>Проект</UI.Tag><UI.Input label="Название" defaultValue="Сад идей"/><UI.Checkbox label="Закрепить"/></div>}}><div className="catalog-stack"><UI.Breadcrumbs items={[{label:'Коллекции',href:'#CollectionRow'},{label:'Сад идей'}]}/><h3>Сад идей</h3><p className="catalog-muted">Панели работают по обеим осям. Разделитель меняет размер перетаскиванием и стрелками независимо от видимости линии.</p><UI.ContentCard title="Сад идей" description="Карточка занимает доступную ширину и сохраняет собственную высоту."/><UI.CodeBlock label="workspace.tsx" language="tsx">{'<ContentLayout orientation="vertical" divider="hover"\n  left={collections} right={properties}>\n  {document}\n</ContentLayout>'}</UI.CodeBlock></div></UI.ContentLayout></div></StorySection>;
}
