import { useCatalogText, localizeCatalogueFixture } from './catalog-locale';
import { useState } from 'react';
import * as UI from '../src';
import { ReorderExample } from './CardComposer';
import { Sample, StorySection, type StoryProps } from './stories-controls';
const colorSamples: UI.Color[] = ['neutral','blue','purple','teal','rose','amber'];
export function IconBoxStory(){
 const ct=useCatalogText();
return <><StorySection title={ct("Размеры")}><div className="catalog-row">{(['xs','sm','md','lg','xl'] as const).map(size=><Sample key={size} label={size}><UI.IconBox icon="cube" size={size}/></Sample>)}</div></StorySection><StorySection title={ct("Типы объектов")}><div className="catalog-row">{colorSamples.map((color,index)=><UI.IconBox key={color} color={color} icon={(['page','book','cube','folder','check','sun'] as const)[index]}/>)}</div></StorySection></>;}
export function AvatarStory(){
 const ct=useCatalogText();
const image='data:image/svg+xml,%3Csvg xmlns="http://www.w3.org/2000/svg" width="80" height="80" viewBox="0 0 80 80"%3E%3Crect width="80" height="80" fill="%23b8ccc3"/%3E%3Ccircle cx="40" cy="30" r="15" fill="%23576b60"/%3E%3Cpath d="M8 80a32 32 0 0 1 64 0" fill="%23576b60"/%3E%3C/svg%3E';return <><StorySection title={ct("Инициалы")}><div className="catalog-row">{(['xs','sm','md','lg','xl'] as const).map(size=><Sample key={size} label={size}><UI.Avatar name={ct("Анна Ким")} size={size}/></Sample>)}</div></StorySection><StorySection title={ct("Изображение")}><div className="catalog-row"><UI.Avatar name={ct("Профиль с изображением")} src={image} size="lg"/><UI.Avatar name={ct("Даша")}/><UI.Avatar name={ct("Илья Морозов")}/></div></StorySection></>;}
export function SeparatorStory(){
 const ct=useCatalogText();
return <StorySection><div className="catalog-narrow"><p>{ct("Сведения о проекте")}</p><UI.Separator/><p>{ct("Связанные заметки")}</p><UI.Separator/><p>{ct("История изменений")}</p></div></StorySection>;}
export function CardStory(){
 const ct=useCatalogText();
return <StorySection title={ct("Поверхности")}><div className="catalog-cards">{(['default','subtle','elevated'] as const).map(variant=><UI.Card key={variant} variant={variant}><h3>{variant}</h3><p className="catalog-muted">{ct("Нейтральный контейнер для содержимого.")}</p></UI.Card>)}</div></StorySection>;}
export function ObjectCardStory({notify}:StoryProps){
 const ct=useCatalogText();
return <StorySection><div className="catalog-cards"><UI.ObjectCard title={ct("Сад идей")} description={ct("Небольшие шаги к большому проекту.")} icon="cube" color="teal" meta={<UI.Tag color="teal">{ct("Личное")}</UI.Tag>} onClick={()=>notify(ct('Открыт «Сад идей»'))}/><UI.ObjectCard title={ct("Визуальные системы")} icon="book" color="purple" cover={<div className="catalog-object-cover"><UI.Icon name="book" size={34}/></div>} meta={ct("12 заметок")} onClick={()=>notify(ct('Открыты «Визуальные системы»'))}/><UI.ObjectCard title={ct("Архив")} description={ct("Пример недоступной карточки.")} icon="folder" disabled/></div></StorySection>;}
export function CollectionRowStory({notify}:StoryProps){
 const ct=useCatalogText();
return <StorySection><div className="catalog-stack catalog-narrow"><UI.CollectionRow title={ct("Сад идей")} icon="cube" color="teal" meta={<UI.Tag color="teal">{ct("Проект")}</UI.Tag>} onClick={()=>notify(ct('Открыт проект'))}/><UI.CollectionRow title={ct("Наблюдения")} icon="page" color="blue" meta={ct("Сегодня")} onClick={()=>notify(ct('Открыты наблюдения'))}/><UI.CollectionRow title={ct("Книги")} icon="book" color="purple" onClick={()=>notify(ct('Открыта коллекция книг'))}/><UI.CollectionRow title={ct("Архив недоступен")} icon="folder" disabled/></div></StorySection>;}
export function PropertyRowStory(){
 const ct=useCatalogText();
return <StorySection><div className="catalog-narrow"><UI.PropertyRow label={ct("Статус")} icon="check"><UI.Tag color="green">{ct("В работе")}</UI.Tag></UI.PropertyRow><UI.PropertyRow label={ct("Автор")} icon="page"><span className="catalog-inline"><UI.Avatar name={ct("Анна Ким")} size="xs"/>{ct("Анна Ким")}</span></UI.PropertyRow><UI.PropertyRow label={ct("Теги")} icon="tag"><UI.Tag color="purple">{ct("Исследование")}</UI.Tag> <UI.Tag color="blue">UI</UI.Tag></UI.PropertyRow><UI.PropertyRow label={ct("Обновлено")} icon="calendar">{ct("Сегодня")}</UI.PropertyRow><UI.PropertyRow label={ct("Описание")}>{ct("Значение свойства может занимать несколько строк и переноситься в пределах контейнера.")}</UI.PropertyRow></div></StorySection>;}
export function TableStory(){
 const ct=useCatalogText();
return <StorySection><UI.Table caption={ct("Объекты коллекции")} columns={[ct('Название'),ct('Тип'),ct('Статус'),ct('Обновлено')]} rows={[[<span className="catalog-inline"><UI.IconBox icon="cube" color="teal" size="xs"/>{ct("Сад идей")}</span>,ct('Проект'),<UI.Tag color="green">{ct("В работе")}</UI.Tag>,ct('Сегодня')],[ct('Тихое утро'),ct('Заметка'),<UI.Tag>{ct("Черновик")}</UI.Tag>,ct('Вчера')],[ct('Визуальные системы'),ct('Книга'),<UI.Tag color="purple">{ct("В планах")}</UI.Tag>,ct('2 октября')]]}/></StorySection>;}
export function CodeBlockStory(){
 const ct=useCatalogText();
const [wrap,setWrap]=useState(false);return <><StorySection title={ct("Исходный код")}><UI.CodeBlock label="App.tsx" defaultLanguage="tsx">{'import { Button } from "@personal/capacities-ui";\n\nexport function App() {\n  return <Button variant="primary">Создать</Button>;\n}'}</UI.CodeBlock></StorySection><StorySection title={ct("Акцентная заливка")}><UI.CodeBlock defaultLanguage="json" color="inherit" variant="surface">{'{\n  "project": "Сад идей",\n  "count": 99,\n  "archived": false\n}'}</UI.CodeBlock></StorySection><StorySection title={ct("Длинная строка")}><UI.CodeBlock label="tokens.css" defaultLanguage="css" wrap={wrap} onWrapChange={setWrap}>{':root { --cap-font-sans: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }'}</UI.CodeBlock></StorySection></>;}
export const markdownExample='## Место для идей\n\nНебольшие шаги помогают **двигаться дальше**. Оставьте место для *новых наблюдений*.\n\n- [x] Собрать референсы\n- [ ] Настроить цвета\n- [ ] Выпустить первую версию\n\n> Меньше шума, больше смысла.\n\nИспользуйте `data-accent="teal"` для локального акцента.\n\n[Документация](https://capacities.io)\n\n```tsx\n<Button variant="accent">Создать</Button>\n```';
export function MarkdownPreviewStory(){
 const ct=useCatalogText();
return <><StorySection title={ct("Форматированный текст")}><UI.MarkdownPreview value={localizeCatalogueFixture(markdownExample,ct)} className="catalog-reading"/></StorySection><StorySection title={ct("Пустое содержимое")}><UI.MarkdownPreview value=""/></StorySection></>;}
export function MarkdownEditorStory({notify}:StoryProps){
 const ct=useCatalogText();
const [text,setText]=useState(localizeCatalogueFixture(markdownExample,ct));return <><StorySection title={ct("Редактирование и предпросмотр")}><UI.MarkdownEditor label={ct("Заметка проекта")} value={text} onValueChange={setText} defaultMode="split" onSave={()=>notify(ct('Заметка сохранена в состоянии примера'))}/></StorySection><StorySection title={ct("Только чтение")}><UI.MarkdownEditor label={ct("Заметка только для чтения")} value={ct("Содержимое этого блока можно прочитать и скопировать.")} onValueChange={()=>{}} readOnly/></StorySection></>;}
export function ContentCardStory({notify}:StoryProps){
 const ct=useCatalogText();
const [selected,setSelected]=useState(false),[cover,setCover]=useState(true),[compact,setCompact]=useState(false),[selectable,setSelectable]=useState(false);return <><StorySection><div className="catalog-row catalog-story-controls" style={{marginBlockEnd:16}}><UI.Switch label={ct("Выбор карточки")} checked={selectable} onChange={event=>setSelectable(event.target.checked)}/><UI.Switch label={ct("Обложка")} checked={cover} onChange={event=>setCover(event.target.checked)}/><UI.Switch label={ct("Компактная")} checked={compact} onChange={event=>setCompact(event.target.checked)}/></div><div className="catalog-cards"><UI.ContentCard title={ct("Сад идей")} description={ct("Личная коллекция наблюдений и небольших проектов.")} data-accent="teal" density={compact?'compact':'comfortable'} selectable={selectable} selected={selected} onSelectedChange={setSelected} onOpen={()=>notify(ct('Проект открыт'))} cover={cover?<UI.IconBox icon="cube" color="teal" size="lg"/>:undefined} header={<UI.Tag icon="cube" color="teal">{ct("Проект")}</UI.Tag>} actions={<UI.Menu label={ct("Действия проекта")} items={[{id:'copy',label:ct('Дублировать'),icon:'copy',onSelect:()=>notify(ct('Проект дублирован'))} ]}/>} metadata={ct("Обновлено сегодня")} footer={<><UI.Avatar name={ct("Анна Ким")} size="xs"/><UI.Tag color="teal">{ct("Личное")}</UI.Tag></>}/><UI.ContentCard title={ct("Референсы")} description={ct("Слоты заголовка, свойств и действий независимы.")} density={compact?'compact':'comfortable'} orientation="horizontal" cover={cover?<UI.IconBox icon="book" color="purple" size="lg"/>:undefined} footer={<UI.Button variant="outline" size="sm" onClick={()=>notify(ct('Референс добавлен'))}>{ct("Добавить")}</UI.Button>}/></div></StorySection></>;}
export function TaskCardStory({notify}:StoryProps){
 const ct=useCatalogText();
const [done,setDone]=useState(false);return <StorySection><div className="catalog-cards"><UI.TaskCard title={ct("Настроить цветовые моды")} completed={done} onCompletedChange={setDone} onOpen={()=>notify(ct('Задача открыта'))} menuItems={[{id:'copy',label:ct('Дублировать'),icon:'copy',onSelect:()=>notify(ct('Задача дублирована'))},{id:'delete',label:ct('Удалить'),icon:'trash',danger:true,onSelect:()=>notify(ct('Задача удалена в примере'))}]} metadata={<><UI.Icon name="calendar" size={13}/><span>{ct("Сегодня")}</span><UI.Icon name="tag" size={13}/></>} footer={<UI.Tag icon="cube" color="teal">UI-kit</UI.Tag>}/><UI.TaskCard title={ct("Собрать референсы")} completed onCompletedChange={()=>notify(ct('Это пример завершённой задачи'))} footer={<UI.Tag color="purple">{ct("Исследование")}</UI.Tag>}/></div></StorySection>;}
export function KanbanColumnStory({notify}:StoryProps){
 const ct=useCatalogText();
return <StorySection><div className="catalog-columns"><UI.KanbanColumn title={ct("В работе")} color="blue" count={2} action={<UI.IconButton label={ct("Добавить в колонку")} icon="plus" variant="ghost" size="sm" onClick={()=>notify(ct('Задача добавлена в примере'))}/>}><UI.TaskCard title={ct("Наметить первый шаг")}/><UI.TaskCard title={ct("Собрать идеи")}/></UI.KanbanColumn><UI.KanbanColumn title={ct("Готово")} color="teal" count={0} emptyState={<UI.EmptyState title={ct("Пока нет задач")} description={ct("Завершённые карточки появятся здесь.")}/>}/></div></StorySection>;}
export function KanbanBoardStory(){
 const ct=useCatalogText();
const [items,setItems]=useState<UI.KanbanTask[]>([{id:'first',columnId:'inbox',title:ct('Собрать идеи'),color:'rose'},{id:'second',columnId:'active',title:ct('Продумать первую версию'),color:'teal'}]);const [empty,setEmpty]=useState(false);const columns: UI.KanbanLane[]=[{id:'inbox',title:ct('Входящие')},{id:'active',title:ct('В работе'),color:'blue'},{id:'done',title:ct('Готово'),color:'teal'}];return <StorySection><div className="catalog-story-controls" style={{marginBlockEnd:16}}><UI.Switch label={ct("Пустая доска")} checked={empty} onChange={event=>setEmpty(event.target.checked)}/></div><UI.KanbanBoard label={ct("Задачи проекта")} columns={columns} items={empty?[]:items} onMove={(id,columnId)=>setItems(current=>current.map(item=>item.id===id?{...item,columnId,completed:columnId==='done'}:item))} onCompletedChange={(id,completed)=>setItems(current=>current.map(item=>item.id===id?{...item,completed}:item))} onAdd={columnId=>{const id=crypto.randomUUID();setEmpty(false);setItems(current=>[...current,{id,columnId,title:ct('Новая задача')}]);}}/></StorySection>;}
export function DailyHeaderStory(){
 const ct=useCatalogText();
const [date,setDate]=useState('2026-09-25');return <><StorySection title={ct("Дата и типы объектов")}><UI.DailyHeader date={date} tags={<><UI.Tag icon="check" color="rose">Task</UI.Tag><UI.Tag icon="heart" color="orange">Meeting</UI.Tag><UI.Tag icon="cube" color="teal">Project</UI.Tag></>} actions={<UI.DatePicker label={ct("День")} value={date} onValueChange={setDate} today="2026-09-25"/>}/></StorySection><StorySection title={ct("Без номера недели")}><UI.DailyHeader date="2026-10-04" showWeek={false} locale="en-US"/></StorySection></>;}

export function ReorderableListStory(){
 const ct=useCatalogText();
return <><StorySection title={ct("Строки")}><ReorderExample/></StorySection><StorySection title={ct("Ручка внутри карточки")}><ReorderExample cards/></StorySection></>;}
